#import "statements.typ": (
  corollary, definition, lemma, proof, proposition, theorem,
)

#[
  #import "main-defs.typ": V, ix, nx, ref-suffix, source
  #source(25, "12")
  = Weyl Groups <ch:weyl-groups>
  In the present chapter we shall describe some properties of certain finite
  groups of orthogonal #ix("reflections")transformations which are generated by
  reflections. Such reflection groups, called Weyl groups, play a crucial rôle
  in the theory of groups of Lie type—indeed there is a sense in which the Weyl
  group may be regarded as the ‘skeleton’ of the corresponding group of Lie
  type. In order to define the Weyl groups we #ix(
    "root systems",
  )#nx("Phi", [$Phi$], group: "greek-φ")[A root system]introduce the concept of
  a root system. We do this axiomatically, but the way in which such root
  systems arise naturally in the theory of Lie algebras is explained in
  @ch:simple-lie-algebras[chapter].

  == Systems of Roots <sec:root-systems>
  #nx("Phi-plus", [$Phi^+$], group: "greek-φ")[The set of positive roots in
    $Phi$]#nx("succ", [$succ$], group: "relations")[A total order relation on
    $frak(V)$]#nx("RR", [$RR$], group: "latin-r")[The real number field]Let #V
  be a Euclidean space of finite dimension $l$. For each non-zero vector $r$ of
  #V we denote #nx("w-r", [$w_r$], group: "latin-w")[The reflection in the
    hyperplane orthogonal to the root $r$]by $w_r$ the reflection in the
  hyperplane orthogonal to $r$. This is the linear map defined by $w_r (r)=-r$
  and $w_r (x)=x$ for all $x$ with $(r,x)=0$. If $x$ is any vector in #V we have
  $ w_r (x)=x-frac(2(r,x), lr((r,r))) r. $ <eq:root-systems-reflection>

  #definition()[
    A subset $Phi$ of #V is called a system of roots in #V if the following
    axioms are satisfied:
    #enum(
      numbering: "(i)",
      indent: 1.1em,
      body-indent: 0.5em,
      [$Phi$ is a finite set of non-zero vectors.],
      [#metadata((
          kind: "anchor",
          statement: "def:root-system",
        )) <def:root-system-ii> $Phi$ spans #V.],
      [#metadata((
          kind: "anchor",
          statement: "def:root-system",
        )) <def:root-system-iii> If $r,s in Phi$ then $w_r (s) in Phi$.],
      [#metadata((
          kind: "anchor",
          statement: "def:root-system",
        )) <def:root-system-iv> If $r,s in Phi$ then $2(r,s)\/(r,r)$ is a
        rational integer.],
      [#metadata((
          kind: "anchor",
          statement: "def:root-system",
        )) <def:root-system-v> #footnote[@def:root-system-v[Axiom (v)] is
          sometimes omitted in the definition of a root system, but the present
          definition is the most convenient for our purposes.] If
        $r,lambda r in Phi$, where $lambda in RR$, then $lambda=plus.minus 1$.],
    )
  ] <def:root-system>

  We observe that if $r in Phi$ then $-r in Phi$ also. This follows from
  @def:root-system-iii[(iii)] since $w_r (r)=-r$.

  #source(26, "13")
  Let $Phi$ be a #ix("Weyl group, of a root system")root system. We denote by
  #nx(
    "generated-group",
    [$chevron.l dots chevron.r$],
    group: "symbols",
    after: "order-group",
    locator: false,
  )[The group generated by a given set of elements]$W(Phi)$ the group generated
  by the reflections $w_r$ for all $r in Phi$. $W(Phi)$ #nx(
    "W",
    [$W$],
    group: "latin-w",
  )[A Weyl group]is called the Weyl group of $Phi$. It is clearly a group of
  orthogonal transformations of #V. Each element of $W$ transforms $Phi$ into
  itself, by @def:root-system-iii[axiom (iii)]. $W$ operates faithfully on
  $Phi$, by @def:root-system-ii[axiom (ii)]. Since $Phi$ is a finite set, $W$ is
  therefore a finite group.

  Now although $Phi$ spans #V, $Phi$ is not linearly independent. Thus $Phi$
  contains a proper subset which is a basis for #V. We shall show that $Phi$
  contains a subset $Pi$ satisfying the following conditions:
  #enum(
    numbering: "(i)",
    indent: 1.1em,
    body-indent: 0.5em,
    [$Pi$ is linearly independent.],
    [Every root in $Phi$ is a linear combination of roots in $Pi$ with
      coefficients which are either all non-negative or all non-positive.],
  )
  A subset $Pi$ of $Phi$ satisfying (i), (#ix(
    "fundamental system of roots",
  )#nx("Pi", [$Pi$], group: "greek-π")[A fundamental system of roots]ii) is
  called a fundamental system of roots. If
  $ Pi=lr({r_1,r_2,dots.c,r_l}) $ <eq:root-systems-fundamental-basis>
  and $r in Phi$ then we have
  $ r=sum_(i=1)^l lambda_i r_i, $ <eq:root-systems-root-coordinates>
  where $lambda_i in RR$ and either $lambda_i>=0$ for all $i$ or $lambda_i<=0$
  for all $i$.

  In order to prove the existence of a fundamental system of roots we endow the
  space #V with a total ordering. Let $frak(V)^+$ be a subset of #V satisfying
  the conditions:
  #enum(
    numbering: "(i)",
    indent: 1.1em,
    body-indent: 0.5em,
    [If $v in frak(V)^+$ and $lambda>0$ then $lambda v in frak(V)^+$.],
    [If $v_1,v_2 in frak(V)^+$ then $v_1+v_2 in frak(V)^+$.],
    [For each $v in frak(V)$ exactly one of the conditions $v in frak(V)^+$,
      $-v in frak(V)^+$, $v=0$, holds.],
  )
  Such a subset $frak(V)^+$ can be obtained, for example, by choosing a basis
  $v_1,v_2,dots.c,v_l$ of #V and taking for $frak(V)^+$ the set of all vectors
  $ sum_(i=1)^l lambda_i v_i $ <eq:root-systems-lexicographic-vector>
  in which the first non-zero coefficient $lambda_i$ is positive.

  #ix("ordering of vector space")We now introduce an order relation $succ$ by
  defining $v_1 succ v_2$ whenever $v_1-v_2 in frak(V)^+$. This is a total
  ordering on #V compatible with addition and with scalar multiplication by
  positive elements of $RR$.

  #block()[
    A subset of $Phi$ #ix("positive systems of roots")is called a positive
    system of roots if it has the form $Phi ∩ frak(V)^+$ for some total ordering
    of #V. If $Pi$ is a fundamental system of roots there is just one positive
    system of roots containing it. For we can certainly choose an ordering for
    which $Pi subset frak(V)^+$.
  ]
  #block(sticky: true)[
    But then any root #source(27, "14")$r in Phi$ of form
  ]
  $ sum_(r_i in Pi) lambda_i r_i $ <eq:root-systems-positive-combination>
  with $lambda_i>=0$ for all $i$ will satisfy $r in frak(V)^+$, and each root
  for which $lambda_i<=0$ for all $i$ satisfies $-r in frak(V)^+$. Thus
  $Phi ∩ frak(V)^+$ is determined by $Pi$.

  We now prove the existence of a fundamental system of roots in $Phi$.

  #proposition()[
    Every positive system of roots in $Phi$ contains a fundamental system.
  ] <p:fundamental-system-existence>

  #proof[
    Let $Phi^+$ be a positive system in $Phi$. Then there is some total ordering
    of #V for which $Phi^+=Phi ∩ frak(V)^+$. Let $Pi$ be a subset of $Phi^+$
    satisfying the conditions:
    #enum(
      numbering: "(i)",
      indent: 1.1em,
      body-indent: 0.5em,
      [Every root in $Phi^+$ is a linear combination of roots in $Pi$ with
        non-negative coefficients.],
      [No subset of $Pi$ satisfies (i).],
    )
    Such a subset $Pi$ certainly exists, since $Phi^+$ itself satisfies (i).

    We show that a subset $Pi$ satisfying (i), (ii) is a fundamental system. To
    do this it is sufficient to prove that $Pi$ is linearly independent. However
    we prove first that $(r,s)<=0$ for any two distinct roots $r,s$ of $Pi$.
    Suppose, if possible, that $(r,s)>0$. Then $w_r (s)=s-lambda r$, where
    $lambda>0$. If $w_r (s) in Phi^+$ we have
    $
      w_r (s)=sum_(r_i in Pi) alpha_i r_i,
    $ <eq:fundamental-system-existence-reflected-positive>
    where each $alpha_i>=0$. Thus
    $
      s=lambda r+sum_(r_i in Pi) alpha_i r_i, quad lambda>0, quad alpha_i>=0.
    $ <eq:fundamental-system-existence-positive-expansion>
    The coefficient of $s$ on the right-hand side must be less than 1, otherwise
    $
      lambda r+sum_(r_i in Pi) alpha_i r_i-s
    $ <eq:fundamental-system-existence-positive-contradiction>
    would be in $frak(V)^+$. Thus $s$ can be expressed as a linear combination
    with non-negative coefficients of the remaining roots in $Pi$, a
    contradiction. On the other hand, if $-w_r (s) in Phi^+$ we have
    $
      -w_r (s)=sum_(r_i in Pi) alpha_i r_i
    $ <eq:fundamental-system-existence-reflected-negative>
    #block(sticky: true)[with $alpha_i>=0$, whence]
    $
      lambda r=s+sum_(r_i in Pi) alpha_i r_i, quad lambda>0, quad alpha_i>=0.
    $ <eq:fundamental-system-existence-negative-expansion>
    #source(28, "15")
    The coefficient of $r$ on the right-hand side must be less than $lambda$,
    thus $r$ can be expressed as a linear combination with non-negative
    coefficients of the remaining roots in $Pi$, which again gives a
    contradiction. Thus $(r,s)<=0$.

    It is now easy to prove that $Pi$ is linearly independent. Any linear
    relation involving the elements of $Pi$ can be written in the form
    $
      sum alpha_i r_i=sum beta_i s_i, quad alpha_i>=0, quad beta_i>=0,
    $ <eq:fundamental-system-existence-linear-relation>
    where $r_i,s_i$ are distinct elements of $Pi$. Let
    $v=sum alpha_i r_i=sum beta_i s_i$. Then
    $
      (v,v)=sum_(i,j) alpha_i beta_j (r_i,s_j)<=0.
    $ <eq:fundamental-system-existence-squared-norm>
    Thus $v=0$. Since $r_i,s_i$ are in $frak(V)^+$ this implies that
    $alpha_i=0$, $beta_i=0$ for all $i$. Hence $Pi$ is a fundamental system of
    roots.
  ]

  #proposition()[
    Every positive system of roots in $Phi$ contains just one fundamental
    system. Thus there is a one-one correspondence between positive systems and
    fundamental systems in $Phi$.
  ] <p:fundamental-system-uniqueness>

  #proof[
    Suppose $lr({r_1,r_2,dots.c,r_l})$ and $lr({s_1,s_2,dots.c,s_l})$ are two
    fundamental systems in $Phi^+$. Then
    $
      r_i=sum_(j=1)^l alpha_(i j) s_j, quad s_i=sum_(j=1)^l beta_(i j) r_j,
    $ <eq:fundamental-system-uniqueness-basis-change>
    where $alpha_(i j)>=0$, $beta_(i j)>=0$. $(alpha_(i j))$ and $(beta_(i j))$
    are inverse matrices. For each $i$ there exists $j$ with $alpha_(i j)!=0$.
    Since
    $
      sum_(m=1)^l alpha_(i m) beta_(m k)=0
    $ <eq:fundamental-system-uniqueness-off-diagonal>
    for all $k!=i$, we have $beta_(j k)=0$ for all $k!=i$. Hence
    $beta_(j i)!=0$. This implies similarly that $alpha_(i k)=0$ for $k!=j$.
    Thus $(alpha_(i j))$ is a monomial matrix. By numbering $s_1,s_2,dots.c,s_l$
    suitably we may assume $(alpha_(i j))$ is diagonal. Since $r_i,s_i in Phi^+$
    we have $alpha_(i i)>0$ for each $i$. By @def:root-system-v[#ref-suffix[
      (v)]], $alpha_(i i)=1$ for each $i$. Thus $s_i=r_i$.
  ]

  #corollary()[
    If $Pi=lr({r_1,r_2,dots.c,r_l})$ is a fundamental system in $Phi$, then
    $(r_i,r_j)<=0$ for all $i!=j$.
  ] <cor:fundamental-root-inner-products>

  #proof(qed: false)[
    This was true of the fundamental system constructed in
    @p:fundamental-system-existence, and every fundamental system arises in this
    way for some ordering.

  ]

  We now choose a fundamental system $Pi$ and corresponding positive #source(
    29,
    "16",
  )system $Phi^+$, and keep them fixed in the following discussion. (The
  relation between the different fundamental systems will be described later.)
  The roots in $Phi^+$ will be called positive #nx(
    "Phi-minus",
    [$Phi^-$],
    group: "greek-φ",
    after: "Phi-plus",
  )[The set of negative roots in $Phi$]roots and the remainder negative roots.
  The set of negative roots will be denoted by $Phi^-$.

  #lemma()[
    Let $r in Pi$. Then $w_r$ transforms $r$ into $-r$ but every other positive
    root into a positive root.
  ] <l:simple-reflection-positive-roots>

  #proof[
    Let $s in Phi^+$ with $s!=r$. Then
    $
      s=sum_(r_i in Pi) alpha_i r_i
    $ <eq:simple-reflection-positive-roots-positive-expansion>
    with $alpha_i>=0$. By @def:root-system-v[#ref-suffix[ (v)]] there is some
    $alpha_i>0$ corresponding to $r_i!=r$. The coefficient of $r_i$ in $w_r (s)$
    is therefore also positive. Thus $w_r (s) in Phi^+$.
  ]

  #proposition()[
    Each root in $Phi$ is a linear combination of roots in $Pi$ with rational
    integer coefficients.
  ] <p:integral-root-coordinates>

  #proof[
    It is sufficient to prove this for roots in $Phi^+$. Let $r in Phi^+$. If
    $r in Pi$ the result is trivially true, so we assume $r ∉ Pi$. Then
    $
      r=sum_(r_i in Pi) lambda_i r_i,
    $ <eq:integral-root-coordinates-root-coordinates>
    where each $lambda_i>=0$ and at least two $lambda_i$ are positive. Now there
    is some $r_i in Pi$ for which $(r_i,r)>0$. For if all $(r_i,r)<=0$ we would
    have
    $
      (r,r)=sum lambda_i (r_i,r)<=0,
    $ <eq:integral-root-coordinates-norm-contradiction>
    a contradiction. Choose $r_i in Pi$ with $(r_i,r)>0$. Then
    $
      w_(r_i)(r)=r-frac(2(r_i,r), lr((r_i,r_i))) r_i.
    $ <eq:integral-root-coordinates-height-reflection>
    $w_(r_i)(r)$ differs from $r$ in only one coefficient when expressed as a
    linear combination of roots in $Pi$. Thus at least one coefficient of
    $w_(r_i)(r)$ is positive, and so $w_(r_i)(r) in Phi^+$.

    We define $h(r)$, the height of $r$, by $h(r)=sum lambda_i$. Then
    $h(w_(r_i)(r))<h(r)$. Thus for each positive root which is not fundamental
    there #ix("height of a root")#nx(
      "h-height",
      [$h(r)$],
      group: "latin-h",
      after: "h-r-lambda",
    )[The height of a root $r$]is another positive root of smaller height.
    Therefore the positive roots of minimal height are the fundamental roots,
    which have height 1.

    We prove our result by induction on $h(r)$. It is true for roots of
    height 1. Given $r in Phi^+$ with $r ∉ Pi$, choose $r_i$ as above. Then
    $w_(r_i)(r)$ is an integral #source(30, "17")combination of roots in $Pi$,
    by induction. Thus $r$ is also, since
    $
      r=w_(r_i)(r)+frac(2(r_i,r), lr((r_i,r_i))) r_i
    $ <eq:integral-root-coordinates-integral-step>
    and $2(r_i,r)\/(r_i,r_i)$ is a rational integer, by
    @def:root-system-iv[#ref-suffix[ (iv)]].
  ]

  #corollary()[
    With respect to the basis $Pi$ of #V, each element of $W$ is represented by
    a matrix with rational integer coefficients.
  ] <cor:integral-weyl-matrices>

  #proof(qed: false)[
    If $r_i in Pi$, $w(r_i) in Phi$ so is an integral combination of the basis
    elements.
  ]

  #proposition()[
    (i) Every root in $Phi$ is the image of some root in $Pi$ under some element
    of $W$.
    #parbreak()
    (ii) $W$ #ix("fundamental reflection")is generated by the fundamental
    reflections $w_r$ for $r in Pi$.
  ] <p:fundamental-reflections-generate>

  #proof[
    Let $W_0$ be the subgroup of $W$ generated by the reflections $w_r$ for
    $r in Pi$. We show that every root in $Phi$ has the form $w(s)$ for some
    $w in W_0$, $s in Pi$. Let $r in Phi^+$. If $h(r)=1$, $r$ can certainly be
    expressed in the required form, so we use induction on $h(r)$. If $h(r)>1$
    there is a root $r_i in Pi$ such that $(r_i,r)>0$. Then
    $w_(r_i)(r) in Phi^+$ and $h(w_(r_i)(r))<h(r)$, as in the proof of
    @p:integral-root-coordinates. By induction $w_(r_i)(r)=w'(s)$ for some
    $w' in W_0$, $s in Pi$. Hence $r=w_(r_i) w'(s)$ and $w_(r_i) w' in W_0$. The
    negative roots can also be expressed in the required form since
    $
      -r=w_(r_i) w'(-s)=w_(r_i) w' w_s (s)
    $ <eq:fundamental-reflections-generate-negative-root>
    and $w_(r_i) w' w_s in W_0$.

    #block(sticky: true)[
      We now show that $W_0=W$. Since $W$ is generated by the reflections $w_r$
      for $r in Phi$, it is sufficient to show that $w_r in W_0$. Now $r=w(s)$
      for some $s in Pi$ and $w in W_0$. It follows that $w_r=w w_s w^(-1)$. For
    ]
    $
      w w_s w^(-1)(x) & = w(w^(-1)(x)-frac(2(s,w^(-1)(x)), lr((s,s))) s) \
                      & = x-frac(2(r,x), lr((r,r))) r \
                      & = w_r (x).
    $ <eq:fundamental-reflections-generate-conjugation>
    Hence $w_r in W_0$ and $W_0=W$.
  ]

]

#[
  #import "main-defs.typ": V, ix, nx, ref-suffix, source
  #source(31, "18")
  == The Length Function <sec:length-function>
  #nx("H-r", [$H_r$], group: "latin-h")[The hyperplane orthogonal to a root
    $r$]#ix("length function")#nx("l-w", [$l(w)$], group: "latin-l")[The length
    of an element $w$ of the Weyl group]Having established that every element of
  the Weyl group $W$ is a product of fundamental reflections $w_r$, $r in Pi$,
  we denote by $l(w)$ the minimal length of any expression of $w$ of this form.
  Thus $l(1)=0$ and $l(w_r)=1$ for $r in Pi$. We shall show that $l(w)$ can also
  be described in quite a different way. We define for each $w in W$ an integer
  $n(w)$ given by
  $ n(w)=abs(Phi^+ ∩ w^(-1)(Phi^-)). $ <eq:length-function-inversion-count>
  Thus $n(w)$ is the number of positive roots transformed by $w$ into negative
  roots. We first derive some elementary properties of the function $n(w)$.

  #lemma()[
    Let $r in Pi$ and $w in W$. Then
    #enum(
      numbering: "(i)",
      indent: 1.1em,
      body-indent: 0.5em,
      [#metadata((
          kind: "anchor",
          statement: "l:reflection-inversion-count",
        )) <l:reflection-inversion-count-i> $n(w_r w)=n(w)+1$ if
        $w^(-1)(r) in Phi^+$,],
      [#metadata((
          kind: "anchor",
          statement: "l:reflection-inversion-count",
        )) <l:reflection-inversion-count-ii> $n(w_r w)=n(w)-1$ if
        $w^(-1)(r) in Phi^-$,],
      [#metadata((
          kind: "anchor",
          statement: "l:reflection-inversion-count",
        )) <l:reflection-inversion-count-iii> $n(w w_r)=n(w)+1$ if
        $w(r) in Phi^+$,],
      [#metadata((
          kind: "anchor",
          statement: "l:reflection-inversion-count",
        )) <l:reflection-inversion-count-iv> $n(w w_r)=n(w)-1$ if
        $w(r) in Phi^-$.],
    )
  ] <l:reflection-inversion-count>

  #proof[
    By @l:simple-reflection-positive-roots $w_r$ changes the sign of only two
    roots $r$ and $-r$. Thus $n(w_r w)=n(w) plus.minus 1$ and
    $n(w w_r)=n(w) plus.minus 1$. Now $n(w_r w)=n(w)+1$ if and only if
    $r in w(Phi^+)$, thus proving @l:reflection-inversion-count-i[(i)] and
    @l:reflection-inversion-count-ii[(ii)], and $n(w w_r)=n(w)+1$ if and only if
    $w(r) in Phi^+$, proving @l:reflection-inversion-count-iii[(iii)] and
    @l:reflection-inversion-count-iv[(iv)].
  ]

  We now show that $l(w)=n(w)$.

  #theorem()[
    #block(breakable: false)[
      The minimal length of an expression of $w$ as a product of fundamental
      reflections is equal to the number of positive roots transformed by $w$
      into negative roots.
    ]
  ] <th:length-and-inversions>

  #proof[
    #block(
      sticky: true,
    )[ Let $w$ be an element of $W$ with $l(w)=k$. Then $w$ has an expression]
    $
      w=w_(r_1) w_(r_2) dots.c w_(r_k), quad r_i in Pi.
    $ <eq:length-and-inversions-word>
    #block(sticky: true)[By @l:reflection-inversion-count we have]
    $
      n(w)<=n(w_(r_1) w)+1<=n(w_(r_2) w_(r_1) w)+2<=dots.c<=k.
    $ <eq:length-and-inversions-bound>
    Thus $n(w)<=l(w)$.

    #block(sticky: true)[
      Suppose, if possible, that $n(w)<k$. Then by
      @l:reflection-inversion-count-iii[#ref-suffix[ (iii)]] there is an integer
      $j<=k-1$ such that
    ]
    $
      w_(r_1) w_(r_2) dots.c w_(r_j)(r_(j+1)) in Phi^-.
    $ <eq:length-and-inversions-negative-step>
    #source(32, "19")
    It follows that there is some integer $i<=j$ such that
    $
              w_(r_(i+1)) dots.c w_(r_j)(r_(j+1)) & in Phi^+, \
      w_(r_i) w_(r_(i+1)) dots.c w_(r_j)(r_(j+1)) & in Phi^-.
    $ <eq:length-and-inversions-sign-change>
    Since $w_(r_i)$ changes the sign of only $r_i$, $-r_i$, we have
    $
      w_(r_(i+1)) dots.c w_(r_j)(r_(j+1))=r_i.
    $ <eq:length-and-inversions-simple-root>
    It follows that
    $
      w_(r_i)=w_(r_(i+1)) dots.c w_(r_j) w_(r_(j+1)) w_(r_j) dots.c
      w_(r_(i+1))
    $ <eq:length-and-inversions-conjugate>
    and so
    $
      w_(r_(i+1)) dots.c w_(r_(j+1))=w_(r_i) dots.c w_(r_j).
    $ <eq:length-and-inversions-deletion>
    We can now make use of this relation to shorten the original expression for
    $w$.
    $
      w & = w_(r_1) dots.c w_(r_k) \
        & = w_(r_1) dots.c w_(r_i) w_(r_i) dots.c w_(r_j)
          w_(r_(j+2)) dots.c w_(r_k) \
        & = w_(r_1) dots.c w_(r_(i-1)) w_(r_(i+1)) dots.c w_(r_j) w_(r_(j+2))
          dots.c w_(r_k).
    $ <eq:length-and-inversions-shorter-word>
    Thus we have an expression for $w$ as a product of $k-2$ fundamental
    reflections. Thus $l(w)<k$, a contradiction. Hence $n(w)=l(w)$.
  ]

  #block(breakable: false)[
    #corollary()[
      If $w in W$ satisfies $w(Pi)=Pi$ then $w=1$.
    ] <cor:fundamental-system-stabilizer>

    #proof[
      If $w(Pi)=Pi$ then $w(Phi^+)=Phi^+$ and so $n(w)=0$. Thus $l(w)=0$ and so
      $w=1$.
    ]

  ]

  We now discuss the way in which different fundamental systems in $Phi$ are
  related to one another.

  #theorem()[
    If $Pi$ is a fundamental system in $Phi$, so is $w(Pi)$ for any $w in W$.
    Given any two fundamental systems $Pi_1$, $Pi_2$ in $Phi$ there is exactly
    one element $w in W$ such that $w(Pi_1)=Pi_2$.
  ] <th:fundamental-systems-conjugate>

  #proof[
    Let $Phi^+$ be the positive system containing $Pi$. Then
    $Phi^+=Phi ∩ frak(V)^+$ for some total ordering on #V. $w(frak(V)^+)$ also
    defines a total ordering on #V and the positive roots with respect to this
    ordering are
    $
      w(Phi^+)=Phi ∩ w(frak(V)^+).
    $ <eq:fundamental-systems-conjugate-positive-image>
    $w(Pi)$ is clearly the fundamental system contained in $w(Phi^+)$.

    We now show that for any two fundamental systems $Pi_1$, $Pi_2$ there
    #source(
      33,
      "20",
    )is some element $w in W$ for which $w(Pi_1)=Pi_2$. Let $Phi_1^+$, $Phi_2^+$
    be the positive systems containing $Pi_1$, $Pi_2$. We use induction on
    $n=abs(Phi_1^+ ∩ Phi_2^-)$. If $n=0$ we have $Phi_1^+=Phi_2^+$ and so
    $Pi_1=Pi_2$. Thus we may assume $n>0$. Then $Pi_1 ∩ Phi_2^-$ is not empty.
    For if every root in $Pi_1$ were in $Phi_2^+$ the same would apply to every
    root in $Phi_1^+$. Let $r in Pi_1 ∩ Phi_2^-$. Then $w_r (Phi_1^+)$ is the
    set of roots obtained from $Phi_1^+$ by replacing $r$ by $-r$. Hence
    $
      abs(w_r (Phi_1^+) ∩ Phi_2^-)=n-1.
    $ <eq:fundamental-systems-conjugate-induction>
    Now $w_r (Pi_1)$ is the fundamental system contained in $w_r (Phi_1^+)$ so,
    by induction, there exists $w' in W$ with $w' w_r (Pi_1)=Pi_2$. Thus
    $w(Pi_1)=Pi_2$ where $w=w' w_r$.

    Finally we prove the uniqueness of $w$. Suppose $w_1(Pi_1)=Pi_2$ and
    $w_2(Pi_1)=Pi_2$. Then $w_2^(-1) w_1(Pi_1)=Pi_1$ and so by
    @cor:fundamental-system-stabilizer $w_2^(-1) w_1=1$. Thus there is a unique
    element of $W$ transforming $Pi_1$ into $Pi_2$.
  ]

  #corollary()[
    The number of fundamental systems in $Phi$ is equal to the order of $W$.
  ] <cor:number-of-fundamental-systems>

  #proof[
    Let $Pi$ be a fixed fundamental system. Then $w(Pi)$ gives each fundamental
    system exactly once as $w$ runs through $W$.
  ]

  #block(breakable: false)[
    #nx("w-0", [$w_0$], group: "latin-w", after: "w-r")[The element of $W$ which
      transforms each positive root to a negative root]#proposition()[
      Let $Phi^+$ be a positive system in $Phi$ and $Phi^-$ the corresponding
      negative system. Then there is a unique element $w_0 in W$ such that
      $w_0(Phi^+)=Phi^-$. Moreover $w_0$ is an element of order 2.
    ] <p:longest-weyl-element>

    #proof[
      $Phi^+$ is the positive system in $Phi$ corresponding to some total
      ordering of #V, and $Phi^-$ is the positive system corresponding to the
      reverse ordering. By @p:fundamental-system-uniqueness and
      @th:fundamental-systems-conjugate there exists a unique element $w_0 in W$
      with $w_0(Phi^+)=Phi^-$. Since $w_0^2(Phi^+)=Phi^+$ we have $w_0^2=1$, so
      that $w_0$ is an element of order 2.
    ]

  ]
]

#[
  #import "main-defs.typ": V, ix, nx, ref-suffix, source
  // Original page 20 continues from length.typ; its page anchor is already
  // present.
  #heading(level: 2)[
    A Geometrical Interpretation of the Fundamental Systems
  ] <sec:fundamental-systems-geometrical-interpretation>

  #ix("fundamental system of roots")For each root $r in Phi$ we denote by $H_r$
  the hyperplane orthogonal to $r$. Thus $x in H_r$ if and only if $(r,x)=0$.
  #block(sticky: true)[Now the hyperplanes are closed subsets of #V, thus]
  $
    union.big_(r in Phi) H_r
  $ <eq:fundamental-systems-geometrical-interpretation-hyperplanes>
  is closed and its complement
  $
    frak(V)-union.big_(r in Phi) H_r
  $ <eq:fundamental-systems-geometrical-interpretation-complement>
  #source(34, "21")
  is open in #V. It is disconnected, two points being in the same connected
  component if and only if they lie on the same side of each reflecting
  hyperplane. The connected components of
  $
    frak(V)-union.big_(r in Phi) H_r
  $ <eq:fundamental-systems-geometrical-interpretation-chambers>
  #ix("chamber")#nx("C", [$C$], group: "latin-c", after: "CC")[A chamber]are
  called chambers.

  Let $C$ be any chamber in #V and $delta(C)$ be the boundary of $C$. Then the
  hyperplanes $H_r$ such that $H_r ∩ delta(C)$ is not contained in any proper
  subspace of $H_r$ are called the bounding hyperplanes, or walls, of $C$.

  Let $Pi=lr({r_1,r_2,dots.c,r_l})$ be a fundamental system in $Phi$. Then the
  set $C$ of vectors $x in frak(V)$ with $(r_i,x)>0$ for $i=1,2,dots.c,l$ is a
  chamber. For if $H_r$ is any reflecting hyperplane, we may assume
  $r in Phi^+$, and so $(r,x)>0$ for each $x in C$. Thus all vectors in $C$ lie
  on the same side of each reflecting hyperplane. We show that the bounding
  hyperplanes of $C$ are
  $
    H_(r_1),H_(r_2),dots.c,H_(r_l).
  $ <eq:fundamental-systems-geometrical-interpretation-walls>

  Now $H_(r_i) ∩ delta(C)$ consists of the vectors $x$ for which $(r_i,x)=0$ and
  $(r_j,x)>=0$ for all $j!=i$. Since $r_1,r_2,dots.c,r_l$ are linearly
  independent, $H_(r_i) ∩ delta(C)$ is not contained in any proper subspace of
  $H_(r_i)$. On the other hand, let $r$ be a positive root which is not
  fundamental. Then
  $
    r=sum_(i=1)^l lambda_i r_i,
  $ <eq:fundamental-systems-geometrical-interpretation-root-expansion>
  where each $lambda_i>=0$ and at least two $lambda_i$ are positive. If
  $x in H_r ∩ delta(C)$ then
  $
    sum_(i=1)^l lambda_i (r_i,x)=0,
  $ <eq:fundamental-systems-geometrical-interpretation-wall-equation>
  whence $(r_i,x)=0$ whenever $lambda_i>0$. Thus $H_r ∩ delta(C)$ is contained
  in a proper subspace of $H_r$. Therefore the bounding hyperplanes of $C$ are
  $H_(r_1),H_(r_2),dots.c,H_(r_l)$ and the roots $r_1,r_2,dots.c,r_l$ may be
  characterized as those roots in $Phi$ which are orthogonal to the bounding
  hyperplanes of $C$ and point into $C$ (viz., $r_i$ lies on the same side of
  the hyperplane $H_(r_i)$ as $C$ does).

  The following proposition describes the relation between the set of chambers
  #ix("fundamental system of roots")and the set of fundamental systems.

  #proposition()[
    #block(sticky: true)[
      The roots orthogonal to the bounding hyperplanes of a chamber and pointing
      into the chamber form a fundamental system. Moreover, every fundamental
      system arises in this way from some chamber.
    ]
    #source(35, "22")
  ] <p:chambers-and-fundamental-systems>

  #proof[
    Let $w$ be an element of $W$. Since $w(H_r)=H_(w(r))$, $w$ permutes the
    reflecting hyperplanes. It follows that if $C$ is a chamber so is $w(C)$.
    Thus the Weyl group operates on the set of chambers. We show that this
    operation is transitive.

    Let $Pi$ be a fundamental system in $Phi$ and $C$ be the chamber defined by
    $(r_i,x)>0$ for all $r_i in Pi$. Let $C'$ be any chamber and $v$ be a vector
    in $C'$. Let $Phi^+$ be the positive system containing $Pi$ and let
    $Phi^+=Phi ∩ frak(V)^+$, where $frak(V)^+$ is the set of positive elements
    with respect to a total ordering $prec$. Consider the set of transforms
    $w(v)$ of $v$ by elements of $W$. Let $v'$ be the greatest of all these
    transforms with respect to the ordering $prec$. Then we have
    $
      w_(r_i)(v')=v'-frac(2(r_i,v'), lr((r_i,r_i))) r_i, quad r_i in Pi,
    $ <eq:chambers-and-fundamental-systems-maximal-vector>
    and since $w_(r_i)(v') ≼ v'$ we have $(r_i,v')>=0$. Since this holds for all
    $r_i in Pi$, $v'$ must be in the closure $overline(C)$ of $C$.

    Let $v'=w(v)$. Then $v'$ is in the chamber $w(C')$. However, the only
    chamber intersecting $overline(C)$ is $C$. Thus $w(C')$, which intersects
    $overline(C)$, must be equal to $C$. It follows that $W$ operates
    transitively on the set of chambers.

    Now since $C'=w^(-1)(C)$, the roots orthogonal to the bounding hyperplanes
    of $C'$ and pointing into $C'$ form the set $w^(-1)(Pi)$, which is a
    fundamental system. Conversely, any fundamental system has this form for
    some $w in W$ by @th:fundamental-systems-conjugate.
  ]

  #block(breakable: false)[
    #corollary()[
      Given any two chambers $C_1,C_2$ there is a unique element $w in W$ such
      that $w(C_1)=C_2$.
    ] <cor:simply-transitive-chamber-action>

    #proof(qed: false)[
      Let $Pi_1,Pi_2$ be the fundamental systems corresponding to $C_1,C_2$, as
      in @p:chambers-and-fundamental-systems. Then $w(Pi_1)=Pi_2$, and $w$ is
      unique by @th:fundamental-systems-conjugate.
    ]
  ]

  #corollary()[
    The number of chambers is equal to the order of $W$.
  ] <cor:number-of-chambers>

  #proposition()[
    #block(sticky: true)[
      Let $C$ be a chamber in #V. For each $v in frak(V)$ there is a unique
      vector $v' in overline(C)$ such that $v$ can be transformed into $v'$ by
      some element of $W$.
    ]
  ] <p:closed-chamber-orbit-representative>

  #proof(qed: false)[
    Every vector in #V lies in the closure of some chamber. Since $W$ operates
    transitively on the set of chambers, the given vector $v$ can #source(
      36,
      "23",
    )be transformed into $overline(C)$ by some element of $W$. Suppose
    $w_1(v)=v_1$, $w_2(v)=v_2$, where $v_1,v_2 in overline(C)$. Then
    $w_2 w_1^(-1)(v_1)=v_2$.

    We shall show that if $w(v_1)=v_2$, where $v_1,v_2 in overline(C)$, then
    $v_1=v_2$. We prove this by induction on $l(w)$, the result being clear if
    $l(w)=0$. Suppose $l(w)>0$. Then there is some $r in Pi$ such that
    $w(r) in Phi^-$. Hence
    $
      0<=(v_1,r)=(v_2,w(r))<=0.
    $ <eq:closed-chamber-orbit-representative-orthogonality>
    It follows that $(v_1,r)=0$, whence $w_r (v_1)=v_1$. But now
    $w w_r (v_1)=v_2$ and $l(w w_r)=l(w)-1$ by @l:reflection-inversion-count.
    Thus $v_1=v_2$ by induction.
  ]

  #corollary()[
    If $C$ is a chamber in #V, its closure $overline(C)$ contains just one
    element of each orbit of #V under $W$.
  ] <cor:closed-chamber-fundamental-region>

  When we are considering a fixed fundamental system, as is the case in most of
  the discussion to follow, the corresponding chamber will be called the
  fundamental chamber. @cor:closed-chamber-fundamental-region[Corollary] shows
  that its closure is a ‘fundamental region’ for #V under the action of $W$.
]

#[
  #import "main-defs.typ": bib-ref, ix, nx, ref-suffix, source
  // The first paragraph shares original page 23 with chambers.typ.
  == Definitions by Generators and Relations <sec:weyl-group-presentations>

  In the present section we describe two quite distinct ways in #ix(
    "generators and relations, for Chevalley group",
    sub: "for Weyl group",
  )#ix(
    "generators and relations, for Chevalley group",
    sub: "for Weyl group",
  )which a Weyl group can be defined by generators and relations. Let $Pi$ be a
  fundamental system in $Phi$. Then the fundamental reflections $w_r$,
  $r in Pi$, generate $W$ by @p:fundamental-reflections-generate. Let
  $r,s in Pi$ and $m_(r s)$ be the order of $w_r w_s$. In particular $m_(r r)=1$
  for each $r in Pi$. Then $(w_r w_s)^(m_(r s))=1$ is a set of relations in $W$,
  and we show it is in fact a system of defining relations.

  #ix(
    "Steinberg’s theorems, on automorphisms of finite Chevalley groups",
    sub: "on generators and relations for the Weyl group",
  )#theorem()[
    #block(sticky: true)[
      $W$ is defined as an abstract group by generators $w_r$, $r in Pi$,
      subject to relations $(w_r w_s)^(m_(r s))=1$.
    ]
  ] <th:weyl-coxeter-presentation>

  #proof[
    The following beautiful proof of this theorem is due to R. Steinberg.
    Suppose the result is false and let
    $
      w_(r_1) w_(r_2) dots.c w_(r_k)=1, quad r_i in Pi,
    $ <eq:weyl-coxeter-presentation-minimal-relation>
    be a relation of minimal length $k$ which is not a consequence of the given
    relations. Now each reflection has determinant $-1$, thus $det w_r=-1$ and
    $det(w_(r_1) w_(r_2) dots.c w_(r_k))=(-1)^k$. It follows that $k$ is even,
    and we write #source(
      37,
      "24",
    )$k=2m$. Thus
    $
      w_(r_1) w_(r_2) dots.c w_(r_m) w_(r_(m+1))=w_(r_(2m))
      w_(r_(2m-1)) dots.c
      w_(r_(m+2))
    $ <eq:weyl-coxeter-presentation-halves>
    and so $l(w_(r_1) w_(r_2) dots.c w_(r_(m+1)))<m+1$. By
    @l:reflection-inversion-count there is an integer $j<=m$ such that
    $w_(r_1) w_(r_2) dots.c w_(r_j)(r_(j+1)) in Phi^-$. Therefore there is some
    integer $i<=j$ for which
    $
              w_(r_(i+1)) dots.c w_(r_j)(r_(j+1)) & in Phi^+, \
      w_(r_i) w_(r_(i+1)) dots.c w_(r_j)(r_(j+1)) & in Phi^-.
    $ <eq:weyl-coxeter-presentation-sign-change>
    Since $r_i in Pi$ this implies
    $
      w_(r_(i+1)) dots.c w_(r_j)(r_(j+1))=r_i.
    $ <eq:weyl-coxeter-presentation-simple-image>
    Thus
    $
      w_(r_i)=w_(r_(i+1)) dots.c w_(r_j) w_(r_(j+1)) w_(r_j) dots.c
      w_(r_(i+1))
    $ <eq:weyl-coxeter-presentation-conjugation>
    and therefore
    $
      w_(r_(i+1)) dots.c w_(r_(j+1))=w_(r_i) dots.c w_(r_j).
    $ <eq:weyl-coxeter-presentation-exchange>
    #block()[
      This is a relation of length $2(j-i+1)$. If this length is less than $2m$,
      the relation is a consequence of the given relations. By using this
      relation and the relations $w_(r_i)^2=1$ we have
    ]
    $
      w_(r_1) dots.c w_(r_k)=w_(r_1) dots.c w_(r_(i-1)) w_(r_(i+1))
      dots.c w_(r_j)
      w_(r_(j+2)) dots.c w_(r_k).
    $ <eq:weyl-coxeter-presentation-deletion>
    The relation
    $w_(r_1) dots.c w_(r_(i-1)) w_(r_(i+1)) dots.c w_(r_j) w_(r_(j+2)) dots.c
    w_(r_k)=1$
    has length less than $k$, so can be deduced from the given relations, and
    hence
    $
      w_(r_1) dots.c w_(r_k)=1
    $ <eq:weyl-coxeter-presentation-shorter-consequence>
    can be deduced from the given relations also. This is a contradiction, and
    so we must have $2(j-i+1)=2m$, whence $j=m$, $i=1$. It follows that
    $w_(r_2) dots.c w_(r_m)(r_(m+1))=r_1$.

    However the relation $w_(r_1) dots.c w_(r_k)=1$ is equivalent to the
    relation $w_(r_2) dots.c w_(r_k) w_(r_1)=1$. Therefore
    $w_(r_3) dots.c w_(r_(m+1))(r_(m+2))=r_2$. Hence
    $
      w_(r_2)=w_(r_3) dots.c w_(r_(m+1)) w_(r_(m+2)) w_(r_(m+1))
      dots.c w_(r_3)
    $ <eq:weyl-coxeter-presentation-cyclic-conjugation>
    and so
    $
      w_(r_3) dots.c w_(r_(m+2))=w_(r_2) dots.c w_(r_(m+1)).
    $ <eq:weyl-coxeter-presentation-cyclic-exchange>
    Now this relation cannot be deduced from the given relations. For, by using
    it, $w_(r_1) dots.c w_(r_k)$ can be proved equal to the shorter expression
    $w_(r_1) w_(r_3) dots.c w_(r_(m+1)) w_(r_(m+3)) dots.c w_(r_k)$, and
    $w_(r_1) w_(r_3) dots.c w_(r_(m+1)) w_(r_(m+3)) dots.c w_(r_k)=1$ can be
    deduced from the given relations. Thus we have another relation of length
    $2m$ which cannot be deduced from the given relations, and #source(
      38,
      "25",
    )may be written in the form
    $
      w_(r_3) w_(r_2) w_(r_3) w_(r_4) dots.c w_(r_(m+1)) w_(r_(m+2))
      w_(r_(m+1)) dots.c w_(r_4)=1.
    $ <eq:weyl-coxeter-presentation-new-minimal-relation>
    As before we obtain $w_(r_2) dots.c w_(r_m)(r_(m+1))=r_3$. However we
    already have $w_(r_2) dots.c w_(r_m)(r_(m+1))=r_1$, therefore $r_1=r_3$.

    We may now write the relation $w_(r_1) dots.c w_(r_k)=1$ in equivalent forms
    by cyclic permutation of $r_1,dots.c,r_k$, and deduce that
    $
      r_1 & = r_3 = dots.c = r_(2m-1), \
      r_2 & = r_4 = dots.c = r_(2m).
    $ <eq:weyl-coxeter-presentation-alternating-roots>
    Putting $r_1=r$ and $r_2=s$, the relation $w_(r_1) dots.c w_(r_k)=1$ becomes
    $(w_r w_s)^m=1$. Thus $m$ must be a multiple of the order $m_(r s)$ of
    $w_r w_s$. But then $(w_r w_s)^m=1$ is a consequence of
    $(w_r w_s)^(m_(r s))=1$, which is one of the given relations. Thus we have a
    contradiction, and the theorem is proved.
  ]

  #definition()[
    A group defined by generators and relations
    $G=lr(⟨a_i; (a_i a_j)^(m_(i j))=1⟩)$, where $m_(i i)=1$, #ix(
      "Coxeter group",
    )is called a Coxeter group.
  ] <def:coxeter-group>

  Thus every Weyl group is a Coxeter group. Most but not all of the finite
  Coxeter groups are Weyl groups (cf. Bourbaki #bib-ref("bourbaki1968")).

  The second definition of $W$ by generators and relations involves the set of
  all reflections $w_r$, $r in Phi$. The proof is also due to Steinberg.

  #theorem()[
    #block(sticky: true)[
      $W$ is defined as an abstract group by generators $w_r$, $r in Phi$,
      subject to relations $w_r^2=1$ and $w_r w_s w_r=w_(w_r (s))$.
    ]
  ] <th:all-reflections-presentation>

  #proof[
    We show first that the abstract group defined by the given generators and
    relations is generated by the elements $w_r$ for $r in Pi$. This is
    certainly true of the Weyl group $W$. In fact if $r$ is any root in $Phi$ we
    have
    $
      r=w_(r_1) w_(r_2) dots.c w_(r_k)(s)
    $ <eq:all-reflections-presentation-root-orbit>
    for suitable roots $r_1,dots.c,r_k,s in Pi$, by
    @p:fundamental-reflections-generate. Thus
    $
      w_r=w_(r_1) dots.c w_(r_k) w_s w_(r_k) dots.c w_(r_1).
    $ <eq:all-reflections-presentation-reflection-conjugation>
    We show that this relation, which expresses an arbitrary reflection as a
    product of fundamental reflections, is a consequence of the given relations.
    This is clear, since the given relations imply
    $
                  w_(r_k) w_s w_(r_k) & = w_(s_1), quad "where"
                                        s_1=w_(r_k)(s), \
      w_(r_(k-1)) w_(s_1) w_(r_(k-1)) & = w_(s_2), quad "where"
                                        s_2=w_(r_(k-1))
                                        w_(r_k)(s),
    $ <eq:all-reflections-presentation-iterated-relations>
    #source(39, "26")
    and hence
    $
      w_(r_1) dots.c w_(r_k) w_s w_(r_k) dots.c w_(r_1)=w_r.
    $ <eq:all-reflections-presentation-generation>
    Thus the group defined by the given generators and relations is generated by
    the $w_r$ for $r in Pi$.

    Now any relation involving the generators $w_r$, $r in Phi$, can be
    expressed, using the given relations, in the form
    $
      w_(r_1) w_(r_2) dots.c w_(r_k)=1, quad r_i in Pi.
    $ <eq:all-reflections-presentation-relation>
    #block(sticky: true)[
      We show by induction on $k$ that such a relation is a consequence of the
      given relations. This is clear if $k=0$, so assume $k>0$. Since
    ]
    $
      l(w_(r_1) w_(r_2) dots.c w_(r_k))<k,
    $ <eq:all-reflections-presentation-length>
    #block(sticky: true)[
      there exists an integer $j<=k-1$ such that
    ]
    $
      l(w_(r_1) dots.c w_(r_j) w_(r_(j+1)))=l(w_(r_1) dots.c w_(r_j))-1.
    $ <eq:all-reflections-presentation-descent>
    Then by @l:reflection-inversion-count we have
    $w_(r_1) dots.c w_(r_j)(r_(j+1)) in Phi^-$. Hence there exists an integer
    $i<=j$ such that
    $
              w_(r_(i+1)) dots.c w_(r_j)(r_(j+1)) & in Phi^+, \
      w_(r_i) w_(r_(i+1)) dots.c w_(r_j)(r_(j+1)) & in Phi^-.
    $ <eq:all-reflections-presentation-sign-change>
    Since $r_i in Pi$ this implies that
    $w_(r_(i+1)) dots.c w_(r_j)(r_(j+1))=r_i$ and therefore
    $
      w_(r_i)=w_(r_(i+1)) dots.c w_(r_j) w_(r_(j+1)) w_(r_j) dots.c
      w_(r_(i+1)).
    $ <eq:all-reflections-presentation-conjugation>
    Now this relation is clearly a consequence of the given relations. Thus so
    is the relation
    $
      w_(r_i) dots.c w_(r_j)=w_(r_(i+1)) dots.c w_(r_(j+1)).
    $ <eq:all-reflections-presentation-exchange>
    However the relation $w_(r_1) dots.c w_(r_k)=1$ can be proved equivalent,
    using this relation, to the shorter relation
    $
      w_(r_1) dots.c w_(r_(i-1)) w_(r_(i+1)) dots.c w_(r_j) w_(r_(j+2)) dots.c
      w_(r_k)=1.
    $ <eq:all-reflections-presentation-deletion>
    This can be deduced from the given relations by induction, so
    $w_(r_1) dots.c w_(r_k)=1$ can be deduced from the given relations also, and
    the theorem is proved.
  ]

]

#[
  #import "main-defs.typ": V, ix, nx, ref-suffix, source
  #source(40, "27")
  == Parabolic Subgroups of a Weyl Group <sec:weyl-parabolic-subgroups>

  #ix(
    "parabolic subgroups, of a group with $(B,N)$-pair",
    sub: "of a Weyl group",
  )We shall now discuss certain subgroups of a Weyl group which are themselves
  Weyl groups of certain subsystems of the root system $Phi$. Let $Pi$ be a
  fundamental system in $Phi$ and $Phi^+$ be the corresponding positive system.
  Let $J$ be a subset of $Pi$. We define $frak(V)_J$ to be the subspace of #V
  spanned by $J$; $Phi_J$ to be $Phi ∩ frak(V)_J$; and $W_J$ to be #nx(
    "W-J",
    [$W_J$],
    group: "latin-w",
    after: "w-0",
  )[The subgroup of $W$ generated by the fundamental reflections $w_r$ for $r$
    in
    $J$]the subgroup of $W$ generated by the fundamental reflections $w_r$ with
  $r in J$.

  #nx("J", [$J$], group: "latin-j")[A subset of the set $Pi$ of fundamental
    roots]#nx("Phi-J", [$Phi_J$], group: "greek-φ", after: "Phi-minus")[The set
    of roots in $Phi$ which lie in the subspace $frak(V)_J$]#nx(
    "frak-V-J",
    [$frak(V)_J$],
    group: "latin-v",
  )[The subspace of $frak(V)$ spanned by a set $J$ of fundamental
    roots]#proposition()[
    #block(breakable: false)[
      $Phi_J$ is a system of roots in $frak(V)_J$. $J$ is a fundamental system
      in $Phi_J$. The Weyl group of $Phi_J$ is $W_J$.
    ]
  ] <p:parabolic-root-system>

  #proof[
    #block(sticky: true)[
      It is clear that $Phi_J$ spans $frak(V)_J$. If $r,s in Phi_J$, then
    ]
    $
      w_r (s)=s-frac(2(r,s), lr((r,r))) r
    $ <eq:parabolic-root-system-reflection>
    is in $Phi_J$ also. Thus $Phi_J$ is a system of roots in $frak(V)_J$.

    Now $J$ is a linearly independent set and every root in $Phi_J$ is a linear
    combination of elements of $J$. Since $J$ is a subset of $Pi$ the
    coefficients in such a linear combination must be all non-negative or all
    non-positive. Thus $J$ is a fundamental system in $Phi_J$. The Weyl group of
    $Phi_J$ is generated by its fundamental reflections $w_r$, $r in J$, so is
    $W_J$.
  ]

  The subgroups $W_J$ and their conjugates in $W$ are called parabolic subgroups
  of $W$.

  #proposition()[
    #block(sticky: true)[
      The subgroups $W_J$ for distinct subsets $J$ of $Pi$ are all distinct.
    ]
  ] <p:distinct-parabolic-subgroups>

  #proof[
    Suppose $J,K$ are distinct subsets of $Pi$ and that $W_J=W_K$. Assume,
    without loss of generality, that there is a root $r$ in $K$ but not in $J$.
    Then
    $
      w_r (x)-x=-frac(2(r,x), lr((r,r))) r.
    $ <eq:distinct-parabolic-subgroups-displacement>
    Now $w_r in W_J$ and so $w_r (x)-x in frak(V)_J$ for each $x in frak(V)$.
    Choosing $x$ so that $(r,x)!=0$, we have $r in frak(V)_J$. This is a
    contradiction since the fundamental roots are linearly independent.
  ]

  #source(41, "28")
  #lemma()[
    #block(sticky: true)[
      Let $v$ be a vector in $overline(C)$, the closure of the fundamental
      chamber, and let $w$ be an element of $W$ such that $w(v)=v$. Then
      $w in W_J$, where $J$ is the set of roots in $Pi$ orthogonal to $v$.
    ]
  ] <l:closed-chamber-vector-stabilizer>

  #proof(qed: false)[
    We use induction on $l(w)$. If $l(w)=0$ the result is clear. If $l(w)>0$
    there is a root $r in Pi$ such that $w(r) in Phi^-$. Then
    $
      0<=(r,v)=(w(r),v)<=0
    $ <eq:closed-chamber-vector-stabilizer-orthogonality>
    since $v in overline(C)$. Hence $(r,v)=0$ and $w_r (v)=v$. But now
    $w w_r (v)=v$ and
    $ l(w w_r)=l(w)-1 $ <eq:closed-chamber-vector-stabilizer-descent>
    by @l:reflection-inversion-count. Thus $w w_r in W_J$ by induction, whence
    $w in W_J$.
  ]

  #block(breakable: false)[
    #corollary()[
      Let $v$ be any vector in #V and $w$ be an element of $W$ such that
      $w(v)=v$. Then $w$ is a product of reflections corresponding to roots
      orthogonal to $v$.
    ] <cor:vector-stabilizer-reflections>

    #proof[
      Choose a fundamental system so that $v$ is in the closure of the
      fundamental chamber, and apply @l:closed-chamber-vector-stabilizer.
    ]

  ]
  #theorem()[
    #block(sticky: true)[
      Let $w in W$ and $frak(U)$ be the subspace of #V of all vectors fixed by
      $w$. Then $w$ is a product of reflections corresponding to roots in the
      #nx(
        "orthogonal-complement",
        [$perp$],
        group: "symbols",
        locator: false,
      )[The orthogonal subspace of a given subspace]orthogonal complement
      $frak(U)^perp$ of $frak(U)$.
    ]
  ] <th:fixed-space-reflection-factorization>

  #proof[
    Let $v_1,dots.c,v_k$ be a basis for $frak(U)$. We must show that $w$ is a
    product of reflections corresponding to roots orthogonal to
    $v_1,dots.c,v_k$. We shall prove more generally that if $w$ fixes any finite
    set of vectors $v_1,dots.c,v_k$ then $w$ is a product of reflections
    corresponding to roots orthogonal to $v_1,dots.c,v_k$. We proceed by
    induction on $k$, the result being true for $k=1$ by
    @cor:vector-stabilizer-reflections.

    Choose a fundamental system $Pi$ so that $v_k$ is in the closure of the
    fundamental chamber, and let $J$ be the set of fundamental roots orthogonal
    to $v_k$. Consider the decomposition
    $
      frak(V)=frak(V)_J ⊕ frak(V)_J^perp
    $ <eq:fixed-space-reflection-factorization-orthogonal-decomposition>
    and let $v_i=v'_i+v''_i$, where $v'_i in frak(V)_J$,
    $v''_i in frak(V)_J^perp$. Now $w in W_J$ by
    @l:closed-chamber-vector-stabilizer, and therefore $w(v''_i)=v''_i$. Since
    $w(v_i)=v_i$ we have also $w(v'_i)=v'_i$. Now $W_J$ is a Weyl group
    operating on $frak(V)_J$ and the element $w$ of $W_J$ fixes
    $
      v'_1,v'_2,dots.c,v'_(k-1).
    $ <eq:fixed-space-reflection-factorization-projections>
    #source(42, "29")
    Thus $w$ is a product of reflections corresponding to roots in $frak(V)_J$
    orthogonal to $v'_1,dots.c,v'_(k-1)$, by induction. These roots are all
    orthogonal to
    $
      v_1,v_2,dots.c,v_k,
    $ <eq:fixed-space-reflection-factorization-fixed-vectors>
    so the theorem is proved.
  ]

  #theorem()[
    #block(sticky: true)[
      Let $J,K$ be subsets of $Pi$. Then:
      #enum(
        numbering: "(i)",
        indent: 1.1em,
        body-indent: 0.5em,
        [the subgroup of $W$ generated by $W_J,W_K$ is $W_(J union K)$.],
        [$W_J ∩ W_K=W_(J ∩ K)$.],
      )
    ]
  ] <th:parabolic-join-and-intersection>

  #proof(qed: false)[
    The statement (i) is clear from the definitions of $W_J,W_K$. In statement
    (ii) it is clear that $W_(J ∩ K) subset.eq W_J ∩ W_K$. Let $w in W_J ∩ W_K$.
    We must show that $w in W_(J ∩ K)$. Now $w(v)=v$ for each
    $v in frak(V)_J^perp$, also for each $v in frak(V)_K^perp$. Thus $w$ fixes
    every vector in $frak(V)_J^perp+frak(V)_K^perp$.

    #block(sticky: true)[Now]
    $
      frak(V)_J^perp+frak(V)_K^perp subset.eq frak(V)_(J ∩ K)^perp.
    $ <eq:parabolic-join-and-intersection-complement-inclusion>
    #block(sticky: true)[Also]
    $
      dim(frak(V)_J^perp+frak(V)_K^perp)
      &= dim frak(V)_J^perp+dim frak(V)_K^perp-dim(
        frak(V)_J^perp ∩
        frak(V)_K^perp
      ) \
      &= dim frak(V)_J^perp+dim frak(V)_K^perp-dim(frak(V)_J+frak(V)_K)^perp \
      &= l-dim frak(V)_J+l-dim frak(V)_K-l+dim(frak(V)_J+frak(V)_K) \
      &= l-dim(frak(V)_J ∩ frak(V)_K)=l-dim frak(V)_(J ∩ K) \
      &= dim frak(V)_(J ∩ K)^perp.
    $ <eq:parabolic-join-and-intersection-dimensions>
    Hence $frak(V)_J^perp+frak(V)_K^perp=frak(V)_(J ∩ K)^perp$.

    Now $w$ fixes every vector in $frak(V)_(J ∩ K)^perp$, so is a product of
    reflections corresponding to roots in $frak(V)_(J ∩ K)$ by
    @th:fixed-space-reflection-factorization. Thus $w in W_(J ∩ K)$.
  ]

  #block(breakable: false)[
    #corollary()[
      The subgroups $W_J$ form a lattice of $2^l$ subgroups in $W$.
    ] <cor:parabolic-subgroup-lattice>

    #proof[
      This follows from @p:distinct-parabolic-subgroups and
      @th:parabolic-join-and-intersection.
    ]

  ]
  We now show that there is a natural way of choosing a system of
  representatives of the left cosets $w W_J$ of $W_J$ in $W$. Let $D_J$ be the
  set of elements $w in W$ such that $w(r) in Phi^+$ for all $r in J$. $D_J$ is
  a subset, although not generally a subgroup, of $W$.

  #source(43, "30")
  #nx("D-J", [$D_J$], group: "latin-d")[The set of distinguished coset
    representatives of $W_J$ in $W$]#theorem()[
    #block(breakable: false)[
      Let $J$ be a subset of $Pi$. Then each element of $W$ has a unique
      expression of the form $w=d_J w_J$, where $d_J in D_J$ and $w_J in W_J$.
      Furthermore, we have $l(w)=l(d_J)+l(w_J)$.
    ]
  ] <th:parabolic-coset-factorization>

  #proof[
    We show first that each element of $W$ can be expressed in the form
    $w=d_J w_J$, where $d_J in D_J$, $w_J in W_J$ and $l(w)=l(d_J)+l(w_J)$. If
    $l(w)=0$, $1=1 dot 1$ is the required factorization, thus we assume $l(w)>0$
    and use induction on $l(w)$. If $w in D_J$ then $w=w dot 1$ is the required
    factorization. If $w ∉ D_J$ there is a root $r in J$ such that
    $w(r) in Phi^-$. Then
    $ l(w w_r)=l(w)-1 $ <eq:parabolic-coset-factorization-descent>
    by @l:reflection-inversion-count. By induction we have $w w_r=d_J w_J$ with
    $l(d_J)+l(w_J)=l(w w_r)$. Thus $w=d_J w_J w_r$, where $d_J in D_J$,
    $w_J w_r in W_J$ and $l(d_J)+(l(w_J)+1)=l(w)$. Now $l(w_J w_r)<=l(w_J)+1$;
    however if $l(w_J w_r)<l(w_J)+1$ there would be an expression for $w$ as a
    product of fundamental reflections of length less than $l(d_J)+l(w_J)+1$, a
    contradiction. Hence $l(w_J w_r)=l(w_J)+1$ and $l(d_J)+l(w_J w_r)=l(w)$.

    We now prove the uniqueness of the factorization $w=d_J w_J$. Suppose we
    have
    $
      d_J w_J=d'_J w'_J,
    $ <eq:parabolic-coset-factorization-two-factorizations>
    where $d_J,d'_J in D_J$ and $w_J,w'_J in W_J$. Then
    $d'_J=d_J w_J (w'_J)^(-1)$. Suppose $w_J (w'_J)^(-1)!=1$. By
    @p:parabolic-root-system $W_J$ is the Weyl group of the root system $Phi_J$
    with fundamental system $J$. Thus there exists $r in J$ such that
    $w_J (w'_J)^(-1)(r) in Phi_J^-$. Thus $d_J w_J (w'_J)^(-1)(r) in Phi^-$.
    However $d'_J (r) in Phi^+$, and so we have a contradiction. This shows that
    $w'_J=w_J$ and $d'_J=d_J$.
  ]

  #corollary()[
    In each coset $w W_J$ there is a unique element of $D_J$. The length of this
    element is smaller than the length of any other element in $w W_J$.
  ] <cor:distinguished-coset-representatives>

  The elements #ix("distinguished coset representatives")of $D_J$ are called
  distinguished coset representatives of $W_J$ in $W$.
]

#[
  #import "main-defs.typ": V, ix, nx, ref-suffix, source
  // Original page 30 continues from parabolic.typ.
  == The Coxeter Complex <sec:coxeter-complex>

  #ix("Coxeter complex")The parabolic subgroups of a Weyl group $W$ can be
  described geometrically in terms of the Coxeter complex of $W$. This is a
  family of subsets of #V defined as follows. We introduce an equivalence
  relation on #V writing $x tilde y$ if, for each hyperplane $H_r$, $r in Phi$,
  the points $x,y$ are either both in #source(44, "31")$H_r$ or both not in
  $H_r$ but on the same side of $H_r$. The points in #V fall into equivalence
  classes with respect to this relation, and the set of these equivalence
  classes is the Coxeter complex.

  If, for each root $r in Phi^+$, we define
  $
        H_r^+ & = lr({v; (r,v)>0}), \
        H_r^- & = lr({v; (r,v)<0}), \
    H_r=H_r^0 & = lr({v; (r,v)=0}),
  $ <eq:coxeter-complex-half-spaces>
  then the Coxeter complex is the collection of all non-empty subsets of #V of
  the form
  $
    inter.big_(r in Phi^+) H_r^(epsilon_r), quad epsilon_r=+,-,"or" 0.
  $ <eq:coxeter-complex-cells>
  #block(sticky: true)[
    #metadata((kind: "anchor")) <def:fundamental-faces>#nx(
      "C-J",
      [$C_J$],
      group: "latin-c",
      after: "C",
      definition: [@def:fundamental-faces],
    )[The element of the Coxeter complex associated with a set $J$ of
      fundamental roots] Observe that every element of the Coxeter complex lies
    in the closure of some chamber. Choosing a fundamental system $Pi$, the
    elements of the Coxeter complex contained in the closure of the fundamental
    chamber are those of the form
  ]
  $
    C_J=lr(
      {v; vec(
          delim: #none, (v,r)=0 quad "for" r in J, (v,r)>0 quad
          "for" r in Pi-J
        )}
    ),
  $ <eq:coxeter-complex-fundamental-faces>
  where $J$ is any subset of $Pi$.

  Let $w$ be an element of $W$. Then $w$ transforms each reflecting hyperplane
  into another, so transforms each set $H_r^(epsilon_r)$ into a set
  $H_s^(epsilon_s)$. Thus if $frak(K)$ is an element of the Coxeter complex so
  is $w(frak(K))$. We therefore have an operation of the Weyl group on the
  Coxeter complex.

  #proposition()[
    #block(sticky: true)[
      The stabilizer of $C_J$ in $W$ is $W_J$.
    ]
  ] <p:fundamental-face-stabilizer>

  #proof[
    It is clear that an element $w in W_J$ stabilizes $C_J$. In fact, since
    $C_J$ is contained in the hyperplane $H_r$ for all $r in J$, $w$ fixes each
    vector in $C_J$.

    #block(sticky: true)[
      Suppose $w$ is an element in $W$ such that $w(C_J)=C_J$. We may write $w$
      in the form $w=d_J w_J$, $d_J in D_J$, $w_J in W_J$, as in
      @th:parabolic-coset-factorization. Then
    ]
    $
      C_J=w(C_J)=d_J w_J (C_J)=d_J (C_J).
    $ <eq:fundamental-face-stabilizer-stabilizer>
    Suppose $d_J!=1$. Then there is a root $r in Pi$ such that
    $d_J (r) in Phi^-$. $r$ cannot be in $J$, by definition of $D_J$. Thus
    $r in Pi-J$. Let $v$ be a vector in $C_J$. Then $(v,r)>0$ and so
    $(d_J (v),-d_J (r))<0$. However $d_J (v) in C_J$, so lies in the closure
    $overline(C)$ of the fundamental chamber, and $-d_J (r) in Phi^+$. Thus
    $(d_J (v),-d_J (r))>=0$ and we have a contradiction. Hence $d_J=1$ and
    $w in W_J$.
  ]

  #source(45, "32")
  #corollary()[
    Every element of $W$ which transforms $C_J$ into itself transforms every
    vector in $C_J$ into itself.
  ] <cor:face-stabilizer-fixes-pointwise>

  #proposition()[
    #block(sticky: true)[
      Each element of the Coxeter complex can be transformed into exactly one
      element $C_J$ by an element of the Weyl group.
    ]
  ] <p:coxeter-face-orbit-representative>

  #proof[
    Let $frak(K)$ be an element of the Coxeter complex. $frak(K)$ is contained
    in the closure of some chamber $C'$ and there is an element $w in W$ such
    that $w(C')=C$, the fundamental chamber. Hence
    $w(frak(K)) subset.eq overline(C)$, and so $w(frak(K))=C_J$ for some subset
    $J$ of $Pi$.

    In order to prove the uniqueness of $J$ it is sufficient to show that
    $w(C_J)=C_(overline(J))$ implies $J=overline(J)$. We write $w=d_J w_J$ as in
    @th:parabolic-coset-factorization. Then $d_J (C_J)=C_(overline(J))$. Suppose
    $d_J!=1$. Then there is a root $r in Pi-J$ such that $d_J (r) in Phi^-$. Let
    $v$ be a vector in $C_J$. Then $(v,r)>0$ and $(d_J (v),-d_J (r))<0$. But
    $d_J (v) in C_(overline(J))$ so is in the closure of the fundamental
    chamber. Also $-d_J (r) in Phi^+$, therefore $(d_J (v),-d_J (r))>=0$ and we
    have a contradiction. Thus $d_J=1$ and $C_J=C_(overline(J))$.
  ]

  We may now obtain the #ix(
    "parabolic subgroups, of a group with $(B,N)$-pair",
    sub: "of a Weyl group",
  )required geometrical description of the parabolic subgroups of the Weyl
  group.

  #block(breakable: false)[
    #proposition()[
      The parabolic subgroups of $W$ are the stabilizers in $W$ of the elements
      of the Coxeter complex.
    ] <p:coxeter-face-stabilizers>

    #proof[
      Let $frak(K)$ be an element of the Coxeter complex. Then $frak(K)=w(C_J)$
      for some $w in W$ and some subset $J$ of $Pi$. Now $w'(frak(K))=frak(K)$
      if and only if $w^(-1) w' w(C_J)=C_J$, which holds if and only if
      $w' in w W_J w^(-1)$ by @p:fundamental-face-stabilizer. Thus the
      stabilizer of $frak(K)$ is $w W_J w^(-1)$, a parabolic subgroup of $W$.
      Conversely, any parabolic subgroup of $W$ has form $w W_J w^(-1)$, so is
      the stabilizer of some element of the Coxeter complex.
    ]

  ]
]
