#import "statements.typ": corollary, lemma, proof, theorem

#[
  #import "main-defs.typ": L, ix, nx, source
  #let ad = math.op("ad")

  #source(81, "68")
  = Unipotent Subgroups <ch:unipotent-subgroups>
  == The Subgroups $U,V$ <sec:subgroups-u-and-v>

  #nx("U", [$U$], group: "latin-u")[The unipotent subgroup of a Chevalley group
    $G$ generated by the positive root subgroups]#nx(
    "V",
    [$V$],
    group: "latin-v",
  )[The unipotent subgroup of a Chevalley group $G$ generated by the negative
    root subgroups]#nx("X-r", [$X_r$], group: "latin-x", after: "x-r-t")[The
    root subgroup of a Chevalley group corresponding to the root $r$]#ix(
    "root subgroups, of Chevalley groups",
  )#nx("G", [$G$], group: "latin-g")[A group, usually a Chevalley group]Let
  $G=frak(L)(K)$ be the Chevalley group of type #L over $K$. $G$ is generated by
  elements $x_r (t)$ for all $r in Phi$, $t in K$. Now we have
  $
    x_r (t_1) dot x_r (t_2) & =exp(t_1 ad e_r) dot exp(t_2 ad e_r) \
                            & =exp((t_1+t_2)ad e_r) \
                            & =x_r (t_1+t_2).
  $ <eq:subgroups-u-and-v-root-group-addition>
  Let $X_r$ be the group generated by the elements $x_r (t)$ for all $t in K$.
  $X_r$ is a subgroup of $G$ isomorphic to the additive group of $K$. For the
  map $t arrow.r x_r (t)$ is an epimorphism from $K$ to $X_r$; but if $x_r (t)$
  is the identity, $t$ must be $0$, as can be seen from the operation of
  $x_r (t)$ on the basis elements of $frak(L)_K$. The subgroups $X_r$ are called
  the _root subgroups_ of $G$.

  Let $U$ be the subgroup of $G$ generated by the elements $x_r (t)$ for
  $r in Phi^+$, $t in K$; and $V$ be generated by the $x_r (t)$ for
  $r in Phi^-$, $t in K$. Then $U$ and $V$ clearly generate $G$, and $U$ is
  generated by the root subgroups $X_r$ corresponding to the positive roots,
  while $V$ is generated by the negative root subgroups. We shall elucidate some
  of the properties of $U$, and analogous properties will clearly hold for $V$
  also.

  We show first that the elements of $U$ and $V$ operate #ix(
    "unipotent linear transformation",
  )on $frak(L)_K$ as unipotent linear transformations. A linear transformation
  $u$ of a vector space into itself is said to be unipotent if $u-1$ is
  nilpotent. Let
  $
    frak(L)_K=frak(H) ⊕ sum_(r in Phi) frak(L)_r
  $ <eq:subgroups-u-and-v-root-decomposition>
  be the decomposition of $frak(L)_K$ corresponding to the Cartan decomposition
  of #L. We define $frak(L)_0=frak(H)$ and
  $ frak(L)_i=sum_(h(r)=i) frak(L)_r $ <eq:subgroups-u-and-v-height-space>
  #block(sticky: true)[for each $i!=0$. Then]
  $ frak(L)_K=⨁_i frak(L)_i. $ <eq:subgroups-u-and-v-height-decomposition>

  #source(82, "69")
  #block(sticky: true)[
    Now if $r in Phi^+$ and $x in frak(L)_i$ it is evident that
  ]
  $
    x_r (t) dot x-x in sum_(j>i) frak(L)_j.
  $ <eq:subgroups-u-and-v-root-raises-height>
  Since each element of $U$ is a product of elements $x_r (t)$ for positive
  roots $r$, we have for each $u in U$, $x in frak(L)_i$:
  $
    u dot x-x in sum_(j>i) frak(L)_j.
  $ <eq:subgroups-u-and-v-unipotent-raises-height>
  Thus $u-1$ is a nilpotent linear transformation of $frak(L)_K$, whence $u$ is
  unipotent. Similarly each element of $V$ is a unipotent transformation of
  $frak(L)_K$.

  The following lemma will be very useful in the subsequent development:

  #lemma()[
    #block(sticky: true)[
      Let #L be a simple Lie algebra over $CC$. Let $y$ be an element of #L such
      that $ad y$ is nilpotent and let $theta$ be an automorphism of #L. Then
    ]
    $ theta dot exp(ad y)theta^(-1)=exp(ad theta y). $
    <eq:exponential-equivariance-exponential-equivariance>
  ] <l:exponential-equivariance>

  #proof[
    #block(sticky: true)[ Let $x in frak(L)$. Then we have]
    $
      theta dot exp(ad y)theta^(-1)(x)
      &=theta lr(
        (sum_(i=0)^infinity frac(
            1,
            i!
          )[y,dots.c[y,theta^(-1)(x)]])
      ) \
      &=sum_(i=0)^infinity frac(1, i!)[theta y,dots.c[theta y,x]] \
      &=exp(ad theta(y)) dot x.
    $ <eq:exponential-equivariance-iterated-brackets>
    #block(sticky: true)[It follows that]
    $ theta dot exp(ad y)theta^(-1)=exp(ad theta y). $
    <eq:exponential-equivariance-conclusion>
  ]

  We now require a more technical lemma about certain nilpotent linear
  transformations of a vector space, which is a special case of the
  Campbell–Hausdorff formula.

  #lemma()[
    #block()[
      #block(sticky: true)[
        Let $V$ be a vector space over a field of characteristic $0$ and
        $xi,eta$ be linear transformations of $V$ into itself such that $xi,eta$
        and
      ]
      $ [xi,eta]=xi eta-eta xi $ <eq:nilpotent-campbell-hausdorff-commutator>
      #block(sticky: true)[
        are nilpotent and $[xi,eta]$ commutes with $xi$ and $eta$. Then $xi+eta$
        is also nilpotent, and
      ]
      $ exp(xi+eta)=exp xi dot exp eta dot exp(-frac(1, 2)[xi,eta]). $
      <eq:nilpotent-campbell-hausdorff-campbell-hausdorff>

    ]

    #source(83, "70")
  ] <l:nilpotent-campbell-hausdorff>

  #proof[
    #block(sticky: true)[ We shall show that]
    $
      frac((xi+eta)^n, n!)=sum_(i,j,k \ i+j+2k=n)
      frac(xi^i, i!) dot frac(eta^j, j!)
      dot frac([xi,eta]^k, 2^k dot k!) dot (-1)^k.
    $ <eq:nilpotent-campbell-hausdorff-power-expansion>
    #block(sticky: true)[This is true for $n=1$ and $2$, since]
    $
      frac(1, 2)(xi+eta)^2=frac(1, 2)xi^2+frac(1, 2)eta^2+xi
      eta-frac(1, 2)[xi,eta].
    $
    <eq:nilpotent-campbell-hausdorff-quadratic-case>
    #block(sticky: true)[To prove it in general we require the formula]
    $
      eta xi^i=xi^i eta-i xi^(i-1)[xi,eta].
    $ <eq:nilpotent-campbell-hausdorff-reordering>
    This is true for $i=1$ and its proof by induction is evident.

    We assume the required result for $(xi+eta)^(n-1)/(n-1)!$. Then
    $
      frac((xi+eta)^n, n!) & =frac(xi+eta, n) dot sum_(i,j,k \ i+j+2k=n-1)
                             frac(xi^i, i!) dot frac(eta^j, j!)
                             dot frac([xi,eta]^k, 2^k dot k!) dot (-1)^k \
                           & =frac(1, n)sum_(i,j,k \ i+j+2k=n-1)
                             frac(xi^(i+1), i!) dot frac(eta^j, j!)
                             dot frac([xi,eta]^k, 2^k dot k!)
                             dot (-1)^k \
                           & quad+frac(1, n)sum_(i,j,k \ i+j+2k=n-1)
                             frac(xi^i, i!) dot frac(eta^(j+1), j!)
                             dot frac([xi,eta]^k, 2^k dot k!)
                             dot (-1)^k \
                           & quad+frac(1, n)sum_(i,j,k \ i+j+2k=n-1 \ i>=1)
                             frac(xi^(i-1), (i-1)!) dot frac(eta^j, j!)
                             dot frac([xi,eta]^(k+1), 2^k dot k!)
                             dot (-1)^(k+1)
    $ <eq:nilpotent-campbell-hausdorff-induction-expansion>
    // E024: the last sum explicitly excludes i=0; otherwise (i-1)! is
    // undefined.
    $
      & =sum_(i,j,k \ i+j+2k=n) frac(xi^i, i!) dot frac(eta^j, j!)
        dot frac([xi,eta]^k, 2^k dot k!) dot (-1)^k
        dot lr((frac(i, n)+frac(j, n)+frac(2k, n))) \
      & =sum_(i,j,k \ i+j+2k=n) frac(xi^i, i!) dot frac(eta^j, j!)
        dot frac([xi,eta]^k, 2^k dot k!) dot (-1)^k.
    $ <eq:nilpotent-campbell-hausdorff-induction-collected>
    #block(sticky: true)[Since $xi,eta$ and $[xi,eta]$ are all nilpotent,]
    $ frac((xi+eta)^n, n!)=0 $ <eq:nilpotent-campbell-hausdorff-nilpotent-sum>
    #block(sticky: true)[for sufficiently large values of $n$. Also]
    $ exp(xi+eta)=exp xi dot exp eta dot exp(-frac(1, 2)[xi,eta]), $
    <eq:nilpotent-campbell-hausdorff-conclusion>
    as required.
  ]

]

#[
  #import "main-defs.typ": L, ix, nx, source
  #import "diagrams/dynkin.typ": g2-root-string
  #let ad = math.op("ad")

  #source(84, "71")
  == Chevalley’s Commutator Formula <sec:chevalley-commutator-formula>

  In the present section we shall derive a formula, due to Chevalley, which
  expresses the commutator of two generators of $G$ as a product of generators.
  We work first over the complex field $CC$ and transfer at a later stage to an
  arbitrary field $K$.

  Let #L be a simple Lie algebra over $CC$; $r,s$ be linearly independent roots
  of #L, and $t,u$ be elements of $CC$. Consider the expression
  $
    x_r (t)x_s (u)x_r (t)^(-1).
  $ <eq:chevalley-commutator-formula-conjugation>
  #block(sticky: true)[By @l:exponential-equivariance we have]
  $
    x_r (t)x_s (u)x_r (t)^(-1)
    &=x_r (t)exp(ad u e_s)x_r (t)^(-1) \
    &=exp ad(x_r (t) dot u e_s) \
    &=exp ad lr((sum_(i=0)^q M_(r,s,i)t^i u e_(i r+s))) \
    &=exp lr((sum_(i=0)^q M_(r,s,i)t^i u ad e_(i r+s))).
  $ <eq:chevalley-commutator-formula-conjugation-expansion>
  #block(sticky: true)[
    Now if $r_1,r_2$ are linearly independent roots such that $r_1+r_2$ is not a
    root, $ad e_(r_1)$ and $ad e_(r_2)$ commute. For
  ]
  $
    ad e_(r_1) dot ad e_(r_2)-ad e_(r_2) dot ad e_(r_1)
    =ad[e_(r_1)e_(r_2)]=0.
  $ <eq:chevalley-commutator-formula-commuting-adjoints>
  Thus if $r+s$ is not a root $ad(t e_r)$ commutes with $ad(u e_s)$ and hence
  $x_r (t)$ commutes with $x_s (u)$. On the other hand, if $r+s$ is a root, the
  integral combinations of $r,s$ which are in $Phi$ form a root system of type
  $A_2$, $B_2$ or $G_2$, by @l:rank-two-root-subsystems. We restrict attention
  to the roots of the form $i r+j s$ with $i,j>0$, and distinguish between a
  number of special cases.

  #metadata((kind: "anchor")) <eq:commutator-case-i>
  (i) Suppose $r+2s$, $3r+2s$ are not roots. Then if $i r+j s in Phi$ and $i>0$,
  $j>0$, we must have $j=1$. This means that all the transformations
  $ad e_(i r+s)$ commute. Thus
  $
    x_r (t)x_s (u)x_r (t)^(-1) & =product_(i=0)^q
                                 exp(M_(r,s,i)t^i u ad e_(i r+s)) \
                               & =product_(i=0)^q x_(i r+s)(M_(r,s,i)t^i u).
  $ <eq:commutator-case-i-product>

  #metadata((kind: "anchor")) <eq:commutator-case-ii>
  (ii) Suppose $r+2s$ is a root and the integral combinations of $r,s$ in
  #source(85, "72")
  $Phi$ form a root system of type $B_2$. Then
  $
    x_r (t)x_s (u)x_r (t)^(-1)=exp(u ad e_s+N_(r,s)t u ad e_(r+s)).
  $ <eq:chevalley-commutator-formula-b2-exponential>
  #block(sticky: true)[
    Let $xi=u ad e_s$ and $eta=N_(r,s)t u ad e_(r+s)$. Then
  ]
  $
    [xi,eta]=N_(r,s)N_(s,r+s)t u^2 ad e_(r+2s).
  $ <eq:chevalley-commutator-formula-b2-bracket>
  Thus $[xi,eta]$ is nilpotent and commutes with $xi$ and $eta$ (because $r+3s$,
  $2r+3s$ are not in $Phi$). Applying @l:nilpotent-campbell-hausdorff we obtain
  $
    & x_r (t)x_s (u)x_r (t)^(-1) \
    & =exp(u ad e_s) dot exp(N_(r,s)t u ad e_(r+s)) \
    & quad times exp(-1/2 N_(r,s)N_(s,r+s)t u^2 ad e_(r+2s)) \
    & =x_s (u)x_(r+s)(N_(r,s)t u)x_(r+2s)(M_(s,r,2)t u^2).
  $ <eq:chevalley-commutator-formula-b2-product>

  #metadata((kind: "anchor")) <eq:commutator-case-iii>
  #block(sticky: true)[
    (iii) Suppose the integral combinations of $r,s$ in $Phi$ form a root system
    of type $G_2$ in which $3r+2s$ is a root. Then the integral combinations of
    form $i r+j s in Phi$ with $i>0$, $j>0$ are
  ]
  $
    r+s, quad 2r+s, quad 3r+s, quad 3r+2s.
  $ <eq:chevalley-commutator-formula-g2-short-first-roots>
  #block(sticky: true)[Then]
  $
    x_r (t)x_s (u)x_r (t)^(-1)
    =exp lr((sum_(i=0)^3 M_(r,s,i)t^i u ad e_(i r+s))).
  $ <eq:chevalley-commutator-formula-g2-short-first-exponential>
  #block(sticky: true)[Let]
  $
     xi & =sum_(i=0)^2 M_(r,s,i)t^i u ad e_(i r+s), \
    eta & =M_(r,s,3)t^3 u ad e_(3r+s).
  $ <eq:chevalley-commutator-formula-g2-first-splitting>
  #block(sticky: true)[Then]
  $ [xi,eta]=N_(s,3r+s)M_(r,s,3)t^3 u^2 ad e_(3r+2s). $
  <eq:chevalley-commutator-formula-g2-first-bracket>
  Thus $[xi,eta]$ is nilpotent and commutes with $xi,eta$. By
  @l:nilpotent-campbell-hausdorff we have
  $
    & x_r (t)x_s (u)x_r (t)^(-1) \
    & =exp lr((sum_(i=0)^2 M_(r,s,i)t^i u ad e_(i r+s))) \
    & quad dot exp(M_(r,s,3)t^3 u ad e_(3r+s)) \
    & quad times exp(-1/2 N_(s,3r+s)M_(r,s,3)t^3 u^2 ad e_(3r+2s)).
  $ <eq:chevalley-commutator-formula-g2-first-product>
  #block(sticky: true)[
    We now make a second application of @l:nilpotent-campbell-hausdorff. Put
  ]
  $
    xi=sum_(i=0)^1 M_(r,s,i)t^i u ad e_(i r+s),
    quad eta=M_(r,s,2)t^2 u ad e_(2r+s).
  $ <eq:chevalley-commutator-formula-g2-second-splitting>
  #block(sticky: true)[Then]
  $ [xi,eta]=N_(r+s,2r+s)M_(r,s,1)M_(r,s,2)t^3 u^2 ad e_(3r+2s). $
  <eq:chevalley-commutator-formula-g2-second-bracket>

  #source(86, "73")
  #block(sticky: true)[
    $[xi,eta]$ is again nilpotent and commutes with $xi,eta$. Thus
  ]
  // E025: restore the two BCH factors from the preceding definitions of
  // xi,eta.
  $
    & x_r (t)x_s (u)x_r (t)^(-1) \
    & =exp(u ad e_s+M_(r,s,1)t u ad e_(r+s)) \
    & quad dot exp(M_(r,s,2)t^2 u ad e_(2r+s)) \
    & quad times exp(
        -1/2 N_(r+s,2r+s)M_(r,s,1)M_(r,s,2)
        t^3 u^2 ad e_(3r+2s)
      ) \
    & quad times exp(M_(r,s,3)t^3 u ad e_(3r+s)) \
    & quad times exp(-1/2 N_(s,3r+s)M_(r,s,3)t^3 u^2 ad e_(3r+2s)) \
    & =x_s (u)x_(r+s)(M_(r,s,1)t u)x_(2r+s)(M_(r,s,2)t^2 u)
      x_(3r+s)(M_(r,s,3)t^3 u) \
    & quad times x_(3r+2s)(
        (-1/2 N_(r+s,2r+s)M_(r,s,1)M_(r,s,2)
          -1/2 N_(s,3r+s)M_(r,s,3))t^3 u^2).
  $ <eq:chevalley-commutator-formula-g2-second-product>
  #block(sticky: true)[Observe that the coefficient of $x_(3r+2s)$ is]
  $
    & (-1/2 N_(r+s,2r+s)M_(r,s,1)M_(r,s,2)
        -1/2 N_(s,3r+s)M_(r,s,3))t^3 u^2 \
    & =(-1/4 N_(r+s,2r+s)N_(r,s)N_(r,s)N_(r,r+s)
        -1/2 N_(s,3r+s)M_(r,s,3))t^3 u^2 \
    & =(1/2 M_(r+s,r,2)-1/2 N_(s,3r+s)M_(r,s,3))t^3 u^2,
  $ <eq:chevalley-commutator-formula-g2-highest-coefficient>
  since $N_(r,s)=plus.minus 1$.

  This coefficient can be simplified by the following lemma:

  #lemma()[
    $N_(s,3r+s)M_(r,s,3)=1/3 M_(r+s,r,2)$.
  ] <l:g-two-commutator-coefficient>

  #proof[
    #block(sticky: true)[ We use the relation]
    $
      s+(3r+s)+(-(r+s))+(-(2r+s))=0.
    $ <eq:g-two-commutator-coefficient-root-relation>
    #block(sticky: true)[
      By formula @th:structure-constant-relations
      @eq:structure-constant-relations-iv[(iv)] relating the structure constants
      we have
    ]
    $
      frac(N_(s,3r+s)N_(-(r+s),-(2r+s)), 3)
      +N_(-(r+s),s)N_(3r+s,-(2r+s))=0.
    $ <eq:g-two-commutator-coefficient-jacobi>
    #block(sticky: true)[
      Using formulae @th:structure-constant-relations
      @eq:structure-constant-relations-ii[(ii)],
      @eq:structure-constant-relations-iii[(iii)] we obtain
    ]
    $
      frac(-N_(s,3r+s)N_(r+s,2r+s), 3)
      +frac(N_(s,r)N_(-(2r+s),-r), 3)=0,
    $ <eq:g-two-commutator-coefficient-jacobi-rewritten>
    #block(sticky: true)[whence]
    $
      N_(s,3r+s)N_(r+s,2r+s)=N_(s,r)N_(r,2r+s).
    $ <eq:g-two-commutator-coefficient-n-relation>
    #block(sticky: true)[It follows that]
    $
      N_(s,3r+s)M_(r,s,3) & =1/6 N_(s,3r+s)N_(r,s)N_(r,r+s)N_(r,2r+s) \
                          & =-1/6 N_(r,r+s)N_(r+s,2r+s)
                            quad ("since" N_(s,3r+s)^2=1) \
                          & =1/6 N_(r+s,r)N_(r+s,2r+s) \
                          & =1/3 M_(r+s,r,2).
    $ <eq:g-two-commutator-coefficient-conclusion>
  ]

  #source(87, "74")
  Applying @l:g-two-commutator-coefficient, the coefficient of $x_(3r+2s)$ in
  the expression for
  $
    x_r (t)x_s (u)x_r (t)^(-1)
  $ <eq:chevalley-commutator-formula-g2-conjugation-repeated>
  #block(sticky: true)[is $1/3 M_(r+s,r,2)t^3 u^2$. Thus]
  $
    x_r (t)x_s (u)x_r (t)^(-1)
    &=x_s (u)x_(r+s)(M_(r,s,1)t u)x_(2r+s)(M_(r,s,2)t^2 u) \
    &quad times x_(3r+s)(M_(r,s,3)t^3 u)
    x_(3r+2s)(1/3 M_(r+s,r,2)t^3 u^2).
  $ <eq:chevalley-commutator-formula-g2-short-first-product>

  #metadata((kind: "anchor")) <eq:commutator-case-iv>
  (iv) Suppose the integral combinations of $r,s$ in $Phi$ form a root system of
  type $G_2$ in which $2r+3s$ is a root. Then the integral combinations of the
  form $i r+j s in Phi$, with $i>0$, $j>0$ are
  $
    r+s, quad r+2s, quad r+3s, quad 2r+3s.
  $ <eq:chevalley-commutator-formula-g2-long-first-roots>
  #block(sticky: true)[
    The formula of @l:nilpotent-campbell-hausdorff can no longer be used to
    calculate
  ]
  $
    x_r (t)x_s (u)x_r (t)^(-1).
  $ <eq:chevalley-commutator-formula-g2-long-first-conjugation>
  #block(sticky: true)[
    We use instead an indirect method based on @eq:commutator-case-iii[(iii)].
    We have shown in @eq:commutator-case-iii[(iii)] (interchanging the rôles of
    $r,s$) that
  ]
  $
    & x_s (u)x_r (t)x_s (u)^(-1) \
    & =x_r (t)x_(s+r)(M_(s,r,1)u t)x_(2s+r)(M_(s,r,2)u^2 t) \
    & quad times x_(3s+r)(M_(s,r,3)u^3 t)
      dot x_(3s+2r)(1/3 M_(s+r,s,2)u^3 t^2) \
    & =x_(s+r)(M_(s,r,1)u t)x_(2s+r)(M_(s,r,2)u^2 t) dot x_r (t) \
    & quad times x_(3s+r)(M_(s,r,3)u^3 t) dot x_r (t)^(-1) \
    & quad dot x_(3s+2r)(1/3 M_(s+r,s,2)u^3 t^2)x_r (t) \
    & =x_(s+r)(M_(s,r,1)u t)x_(2s+r)(M_(s,r,2)u^2 t)
      x_(3s+r)(M_(s,r,3)u^3 t) \
    & quad times x_(3s+2r)((1/3 M_(s+r,s,2)+N_(r,3s+r)M_(s,r,3))
        u^3 t^2) dot x_r (t).
  $ <eq:chevalley-commutator-formula-g2-interchanged-product>
  #block(sticky: true)[Now by @l:g-two-commutator-coefficient,]
  $
    N_(r,3s+r)M_(s,r,3)=1/3 M_(s+r,s,2).
  $ <eq:chevalley-commutator-formula-g2-interchanged-constant>
  #block(sticky: true)[Thus]
  $
    & x_s (u)x_r (t)x_s (u)^(-1) \
    & =x_(s+r)(M_(s,r,1)u t)x_(2s+r)(M_(s,r,2)u^2 t)
      x_(3s+r)(M_(s,r,3)u^3 t) \
    & quad times x_(3s+2r)(2/3 M_(s+r,s,2)u^3 t^2) dot x_r (t).
  $ <eq:chevalley-commutator-formula-g2-interchanged-collected>
  #block(sticky: true)[Replacing $u$ by $-u$ in this formula gives]
  $
    & x_r (t)x_s (u)x_r (t)^(-1) \
    & =x_s (u)x_(s+r)(-M_(s,r,1)u t)x_(2s+r)(M_(s,r,2)u^2 t) \
    & quad times x_(3s+r)(-M_(s,r,3)u^3 t)
      dot x_(3s+2r)(-2/3 M_(s+r,s,2)u^3 t^2).
  $ <eq:chevalley-commutator-formula-g2-long-first-product>

  #metadata((kind: "anchor")) <eq:commutator-case-v>
  (v) Suppose the integral combinations of $r,s$ in $Phi$ form a root system of
  type $G_2$ in which $r+2s in Phi$, $3r+2s in.not Phi$, $3s+2r in.not Phi$.
  Then the roots of
  #source(88, "75")
  form $i r+j s in Phi$ with $i>0$, $j>0$ are $r+s$, $2r+s$, $2s+r$. The root
  system in this case is shown in @fig:2[Figure 2].

  #figure(
    [#block[#g2-root-string() #align(center)[Figure 2]] <fig:2>],
    caption: none,
    placement: top,
  )
  #block(sticky: true)[Then we have]

  $
    & x_r (t)x_s (u)x_r (t)^(-1) \
    & =x_r (t)exp(u ad e_s)x_r (t)^(-1) \
    & =exp ad lr((sum_(i=0)^q M_(r,s,i)t^i u e_(i r+s))) \
    & =exp ad(u e_s+M_(r,s,1)t u e_(r+s)+M_(r,s,2)t^2 u e_(2r+s)) \
    & =exp ad(u e_s+M_(r,s,1)t u e_(r+s))
      exp ad(M_(r,s,2)t^2 u e_(2r+s)) \
    & =exp ad(u e_s)exp ad(M_(r,s,1)t u e_(r+s)) \
    & quad times exp ad(-1/2 M_(r,s,1)N_(s,r+s)t u^2 e_(r+2s))
      exp ad(M_(r,s,2)t^2 u e_(2r+s)) \
    & =x_s (u)x_(r+s)(M_(r,s,1)t u)x_(2r+s)(M_(r,s,2)t^2 u)
      x_(r+2s)(M_(s,r,2)t u^2).
  $ <eq:chevalley-commutator-formula-g2-two-short-product>
  Now the cases @eq:commutator-case-i[(i)], @eq:commutator-case-ii[(ii)],
  @eq:commutator-case-iii[(iii)], @eq:commutator-case-iv[(iv)],
  @eq:commutator-case-v[(v)] considered above exhaust all possibilities. All the
  cases except $G_2$ are dealt with in @eq:commutator-case-i[(i)] or
  @eq:commutator-case-ii[(ii)], and the three different ways in which $r,s$ can
  be placed inside $G_2$ not satisfying @eq:commutator-case-i[(i)] are dealt
  with in @eq:commutator-case-iii[(iii)], @eq:commutator-case-iv[(iv)],
  @eq:commutator-case-v[(v)].

  We may summarize the results of
  @eq:commutator-case-i[(i)]–@eq:commutator-case-v[(v)] in a single formula as
  follows:
  $
    x_r (t)x_s (u)x_r (t)^(-1)
    =x_s (u) dot product_(i,j>0) x_(i r+j s)(C_(i j r s)t^i u^j),
  $ <eq:chevalley-commutator-formula-conjugation-formula>

  #source(89, "76")
  #block(sticky: true)[where]
  $
    C_(i 1 r s) & =M_(r s i), \
    C_(1 j r s) & =(-1)^j M_(s r j), \
    C_(3 2 r s) & =1/3 M_(r+s,r,2), \
    C_(2 3 r s) & =-2/3 M_(s+r,s,2).
  $ <eq:chevalley-commutator-formula-c-constants>
  The product is taken over all pairs $i>0$, $j>0$ such that $i r+j s in Phi$,
  the order of the terms in the product being such that $i+j$ is increasing.
  #footnote[
    This condition does not determine the order uniquely in the situation of
    case @eq:commutator-case-v[(v)]. However, the two terms with $i+j=3$
    commute, so both orders give the same result.
  ]

  The numbers $C_(i j r s)$ defined here are all rational integers. This is
  clear for $C_(i 1 r s)$ and $C_(1 j r s)$, while for $C_(3 2 r s)$ and
  $C_(2 3 r s)$ the absolute value of $M_(r+s,r,2)$, $M_(s+r,s,2)$ can be
  obtained by examining the root system of $G_2$. These both have value
  $plus.minus 3$. Thus $C_(3 2 r s)=plus.minus 1$ and
  $C_(2 3 r s)=plus.minus 2$. Therefore in all cases we have
  $C_(i j r s)=plus.minus 1$, $plus.minus 2$ or $plus.minus 3$.

  Now it follows from results established in @ch:chevalley-groups[chapter] that
  the validity of the equation
  $
    x_r (t)x_s (u)x_r (t)^(-1)
    =x_s (u) dot product_(i,j>0) x_(i r+j s)(C_(i j r s)t^i u^j)
  $ <eq:chevalley-commutator-formula-integral-polynomial-identity>
  is equivalent to the vanishing of certain polynomials $f_k (t,u)=0$, where
  $f_k (x,y) in ZZ[x,y]$. Let $K$ be an arbitrary field and $t,u$ be elements of
  $K$. Then the validity of the equation
  $
    x_r (t)x_s (u)x_r (t)^(-1)
    =x_s (u)product_(i,j>0) x_(i r+j s)(C_(i j r s)t^i u^j)
  $ <eq:chevalley-commutator-formula-field-polynomial-identity>
  in $G=frak(L)(K)$ is equivalent to the vanishing of the polynomials
  $tilde(f)_(k)(t,u)=0$, where $tilde(f)_(k)(x,y) in K[x,y]$ is the polynomial
  obtained from $f_k (x,y)$ by replacing each integral coefficient by its image
  in the prime subfield of $K$ under the natural homomorphism. However, we have
  shown that $f_k (t,u)=0$ for all $t,u in CC$. Thus each $f_k$ is identically
  zero. It follows that each $tilde(f)_k$ is identically zero. Thus
  $tilde(f)_(k)(t,u)=0$ for all $t,u in K$. We have therefore established the
  #ix("commutator formula")following theorem, known as Chevalley’s commutator
  formula.

  #ix(
    "Chevalley’s theorems, on existence of integral basis",
    sub: "on commutator formula",
  )#nx("C-i-j-r-s", [$C_(i j r s)$], group: "latin-c", after: "C-J")[The
    constants occurring in Chevalley’s commutator formula]#theorem()[
    #block(sticky: true)[
      Let $G=frak(L)(K)$ be a Chevalley group over an arbitrary field, $r,s$ be
      linearly independent roots of #L and $t,u$ be elements of $K$. Define the
      commutator
    ]
    $ [x_s (u),x_r (t)]=x_s (u)^(-1)x_r (t)^(-1)x_s (u)x_r (t). $
    <eq:chevalley-commutator-formula-commutator-definition>
    #block(sticky: true)[Then we have]
    $
      [x_s (u),x_r (t)]=product_(i,j>0) x_(i r+j s)(C_(i j r s)(-t)^i u^j),
    $ <eq:chevalley-commutator-formula-chevalley-commutator>
    #source(90, "77")
    #block(sticky: true)[
      where the product is taken over all pairs of positive integers $i,j$ for
      which $i r+j s$ is a root, in order of increasing $i+j$. The constants
      $C_(i j r s)$ are given by
    ]
    $
      C_(i 1 r s) & =M_(r s i), \
      C_(1 j r s) & =(-1)^j M_(s r j), \
      C_(3 2 r s) & =1/3 M_(r+s,r,2), \
      C_(2 3 r s) & =-2/3 M_(s+r,s,2).
    $ <eq:chevalley-commutator-formula-constants>
    Each $C_(i j r s)$ is one of $plus.minus 1$, $plus.minus 2$, $plus.minus 3$.
  ] <th:chevalley-commutator-formula>

  #corollary()[
    #block(sticky: true)[
      If $r,s in Phi^+$ are linearly independent then
    ]
    $
      [x_s (u),x_r (t)]=product_(i,j>0) x_(i r+j s)(C_(i j r s)(-t)^i u^j),
    $ <eq:positive-root-commutator-positive-commutator>
    where the product is taken over all positive roots of the form $i r+j s$,
    $i>0$, $j>0$, in increasing order.
  ] <cor:positive-root-commutator>

]

#[
  #import "main-defs.typ": L, V, ix, nx, source

  == The Structure of $U$ and $V$ <sec:structure-of-u-and-v>

  We shall now use Chevalley’s commutator formula to investigate the structure
  of $U$. We first require two lemmas.

  #nx("U-m", [$U_m$], group: "latin-u")[The subgroup of $U$ generated by the
    root subgroups corresponding to roots of height at least $m$]#lemma()[
    The ordering of the roots can be chosen compatible with the height function,
    i.e. so that $r prec s$ implies $h(r)<=h(s)$.
  ] <l:height-compatible-root-order>

  #proof[
    #block()[
      Let #V be the real vector space spanned by $Phi$ and let
      $h:frak(V) arrow.r RR$ be the linear map which coincides with the height
      function on $Phi$. Let $frak(V)_0$ be the null-space of $h$. Then
      $dim frak(V)_0=l-1$. Let $v_1$ be an element of #V with $h(v_1)=1$ and
      $v_2,v_3,dots.c,v_l$ be a basis of $frak(V)_0$. Then
    ]
    $
      h lr((sum_(i=1)^l lambda_i v_i))=lambda_1.
    $ <eq:height-compatible-root-order-height-coordinate>
    If we define $frak(V)^+$ to be the set of non-zero vectors whose first
    non-zero coefficient $lambda_i$ is positive we obtain an ordering compatible
    with the height function.
  ]

  #lemma()[
    Let $r in Phi$. Then the element $h_r in frak(L)_K$ is non-zero.
  ] <l:nonzero-coroot-after-base-change>

  #proof[
    This is true by definition if $r in Pi$. The co-roots $h_r in frak(L)$ form
    #source(91, "78")
    the dual root system $Phi^*$ by @p:dual-root-system, and $Pi^*$ is a
    fundamental system in $Phi^*$. Thus
    $
      h_r=n_1 h_(p_1)+dots.c+n_l h_(p_l),
    $ <eq:nonzero-coroot-after-base-change-integral-coroot>
    where $Pi={p_1,p_2,dots.c,p_l}$ and $n_i in ZZ$.

    Now it is only possible for $h_r=0$ in $frak(L)_K$ if $K$ has characteristic
    $p$ and $p$ divides each $n_i$, $i=1,dots.c,l$. We suppose that this is so.
    Now $r$ can be expressed in the form $w(p_i)$ for some $w in W$ and some
    $i$. Then $w(h_(p_i))=h_r$. The element $w$ is represented with respect to
    the basis $h_(p_1),dots.c,h_(p_l)$ by a matrix with coefficients in $ZZ$,
    and one of the columns of this matrix is $(n_1,n_2,dots.c,n_l)$. Thus
    $det w$ is divisible by $p$. Since $det w=plus.minus 1$ we have a
    contradiction.
  ]

  #ix(
    "canonical form, for elements of a Chevalley group",
    sub: "for elements of a unipotent subgroup",
  )#ix("central series of unipotent group")#theorem()[
    #block(sticky: true)[
      Let $G=frak(L)(K)$ #ix("unipotent subgroup, of a Chevalley group")be a
      Chevalley group, $U$ be the subgroup of $G$ generated by the root
      subgroups $X_r$ with $r in Phi^+$, and $U_m$ be the subgroup generated by
      the $X_r$ with $r in Phi^+$ and $h(r)>=m$. Then:
    ]
    #block(sticky: true)[(i) $U$ is nilpotent and]
    $ U=U_1 supset U_2 supset dots.c supset U_h supset 1 $
    <eq:unipotent-root-factorization-central-series>
    is a central series for $U$, where $h$ is the greatest height of a root of
    #L.

    #block(sticky: true)[(ii) Each element of $U$ is uniquely expressible in the
      form]
    $
      product_(r_i in Phi^+) x_(r_i)(t_i),
    $ <eq:unipotent-root-factorization-ordered-product>
    where the product is taken over all positive roots in increasing order.
  ] <th:unipotent-root-factorization>

  #proof[
    #block(sticky: true)[
      Observe first that $U_m$ is normal in $U$ for each $m>=1$. For if
      $s in Phi^+$ and $h(s)>=m$ we have
    ]
    $
      x_r (t)x_s (u)x_r (t)^(-1) in U_m
    $ <eq:unipotent-root-factorization-generator-normalizes>
    for all $r in Phi^+$, by the commutator formula. Thus
    $x_r (t)U_m x_r (t)^(-1) subset.eq U_m$. Replacing $t$ by $-t$ we see that
    $x_r (t)U_m x_r (t)^(-1)=U_m$. Since the $x_r (t)$ for $r in Phi^+$,
    $t in K$ generate $U$, it follows that $U_m$ is normal in $U$.

    Let $[U_m,U_n]$ be the subgroup generated by all commutators $[a,b]$ for
    $a in U_m$, $b in U_n$. Let $r,s in Phi^+$ satisfy $h(r)>=n$, $h(s)>=m$.
    Then
    $ h(i r+j s)>=m+n $ <eq:unipotent-root-factorization-commutator-height>
    #block(sticky: true)[for all $i,j>0$. Thus]
    $
      [x_s (u),x_r (t)] in U_(m+n),
    $ <eq:unipotent-root-factorization-generator-commutator>
    using the commutator formula. This means that the images of $x_r (t)$,
    $x_s (u)$ under the natural homomorphism commute in the factor group
    $U\/U_(m+n)$.

    #source(92, "79")
    Now elements of the form $x_s (u)$ generate $U_m$ and elements of form
    $x_r (t)$ generate $U_n$. Thus each element of $U_m$ commutes with each
    element of $U_n$ in $U\/U_(m+n)$. Hence $[a,b] in U_(m+n)$ for all
    $a in U_m$, $b in U_n$. Thus
    $
      [U_m,U_n] subset.eq U_(m+n).
    $ <eq:unipotent-root-factorization-subgroup-commutator>
    In particular $[U,U_n] subset.eq U_(n+1)$ for each $n$. Thus each element of
    $U_n\/U_(n+1)$ commutes with each element of $U\/U_(n+1)$, and so
    $U_n\/U_(n+1)$ is in the centre of $U\/U_(n+1)$. Therefore we have a central
    series for $U$.

    Now each element of $U$ is a product of elements $x_r (t)$ with
    $r in Phi^+$. If in such a product we have a pair of consecutive terms
    $x_s (u)x_r (t)$ with $r prec s$ we use the formula
    $
      x_s (u)x_r (t)=x_r (t)x_s (u)
      product_(i,j>0) x_(i r+j s)(C_(i j r s)(-t)^i u^j).
    $ <eq:unipotent-root-factorization-collection>
    The terms $x_r (t)x_s (u)$ now occur in their natural order and all new
    terms introduced satisfy $h(i r+j s)>=h(r)+h(s)$. Thus the process of
    rearranging the terms in their natural order by means of the commutator
    formula terminates after a finite number of steps, and each element of $U$
    is expressible in the form
    $
      x_(r_1)(t_1)x_(r_2)(t_2)dots.c x_(r_N)(t_N),
    $ <eq:unipotent-root-factorization-collected-product>
    where $0 prec r_1 prec r_2 prec dots.c prec r_N$ are the positive roots of
    #L.

    #block(sticky: true)[
      We now prove uniqueness. We shall prove by descending induction on $m$
      that
    ]
    $ product_(h(s)>=m) x_s (t_s)=product_(h(s)>=m) x_s (t'_s) $
    <eq:unipotent-root-factorization-uniqueness-induction>
    implies $t_s=t'_s$, where the products are taken over all positive roots of
    height at least $m$ in increasing order. The statement is trivially true for
    $m=h+1$, since $U_(h+1)=1$. We assume it true for $m+1$. Let
    $ u=product_(h(s)>=m) x_s (t_s)=product_(h(s)>=m) x_s (t'_s) $
    <eq:unipotent-root-factorization-common-element>
    and let $r$ be a positive root of height $m$. Consider the element
    $u dot e_(-r)$ of $frak(L)_K$. If $h(s)>m$ and $-r+s in Phi$, then
    $-r+s in Phi^+$, since the ordering of the roots is compatible with the
    height. If $h(s)=m$ then $-r+s$ cannot be a root, since its height would be
    $0$. Thus
    $
      u dot e_(-r)=e_(-r)+t_r h_r+x,
    $ <eq:unipotent-root-factorization-first-coroot-component>
    #block(sticky: true)[where]
    $
      x in sum_(r in Phi^+) frak(L)_r;
    $ <eq:unipotent-root-factorization-first-positive-remainder>

    #source(93, "80")
    #block(sticky: true)[and similarly]
    $
      u dot e_(-r)=e_(-r)+t'_r h_r+y,
    $ <eq:unipotent-root-factorization-second-coroot-component>
    #block(sticky: true)[where]
    $
      y in sum_(r in Phi^+) frak(L)_r.
    $ <eq:unipotent-root-factorization-second-positive-remainder>
    #block(sticky: true)[But $frak(L)_K$ has the direct decomposition]
    $
      frak(L)_K=frak(H) ⊕ sum_(r in Phi^+) frak(L)_r
      ⊕ sum_(r in Phi^-) frak(L)_r
    $ <eq:unipotent-root-factorization-triangular-decomposition>
    and $h_r!=0$ by @l:nonzero-coroot-after-base-change. Thus $t_r=t'_r$ and
    $x=y$. Hence
    $
      u & =product_(h(s)=m) x_s (t_s) dot product_(h(s)>=m+1) x_s (t_s) \
        & =product_(h(s)=m) x_s (t_s) dot product_(h(s)>=m+1) x_s (t'_s).
    $ <eq:unipotent-root-factorization-height-m-factor>
    #block(sticky: true)[It follows that]
    // @typstyle off
    $
  lr((product_(h(s)=m) x_s (t_s)))^(-1) dot u
    & =product_(h(s)>=m+1) x_s (t_s) \
    & =product_(h(s)>=m+1) x_s (t'_s),
$ <eq:unipotent-root-factorization-uniqueness-conclusion>
    whence $t_s=t'_s$ by induction, and the proof is complete.
  ]

  It is clear that similar results hold for $V$ in terms of negative roots.
]
