#let chapter = [
  #[
    #import "main-defs.typ": L, chapter-ref, qed, section-ref, source
    #source(94, "81")
    = The Subgroups $lr(⟨X_r, X_(-r)⟩)$ <ch:root-sl2-subgroups>
    In the preceding chapter we considered relations involving generators
    $x_r (t),x_s (u)$ of a Chevalley group corresponding to linearly independent
    roots $r,s$, and showed in particular that two such elements generate a
    nilpotent subgroup. We shall now investigate relations involving generators
    of the form $x_r (t),x_(-r)(u)$. We do this by determining the structure of
    the subgroup $lr(⟨X_r,X_(-r)⟩)$ generated by two root subgroups
    corresponding to opposite roots. This subgroup turns out to be closely
    related to the group $italic("SL")_2(K)$; in fact there is a homomorphism
    from $italic("SL")_2(K)$ onto $lr(⟨X_r,X_(-r)⟩)$. We prove the existence of
    this homomorphism first for the complex field. Regarding #L as a module for
    the group $lr(⟨X_r,X_(-r)⟩)$, we show that the operation of
    $lr(⟨X_r,X_(-r)⟩)$ on certain submodules of #L is the same as the operation
    of $italic("SL")_2(CC)$ on the space of homogeneous polynomials in two
    variables of a suitable degree.#footnote[This method of establishing the
      existence of the homomorphism was described to the author by C. W.
      Curtis.]

    == The Group $italic("SL")_2(K)$ <sec:group-sl2>
    #metadata((kind: "anchor")) <l:6-1-1>
    #smallcaps[Lemma 6.1.1.] _Let $K$ be an arbitrary field. Then the group
    $italic("SL")_2(K)$ is generated by the elements_
    $ mat(1, t; 0, 1), quad mat(1, 0; t, 1) $ <eq:6-1-1>
    _as $t$ runs through $K$._

    #smallcaps[Proof.] Let
    $ mat(alpha, beta; gamma, delta) $ <eq:6-1-2>
    be an element of $italic("SL")_2(K)$. If $gamma!=0$ we have
    $
      mat(alpha, beta; gamma, delta) = mat(1, (alpha-1)gamma^(-1); 0, 1) mat(
        1, 0;
        gamma, 1
      ) mat(1, (delta-1)gamma^(-1); 0, 1).
    $ <eq:6-1-1-factorization>

    #source(95, "82")
    #block(sticky: true)[If $beta!=0$ we have]
    $
      mat(alpha, beta; gamma, delta)
      =mat(1, 0; (delta-1)beta^(-1), 1)
      mat(1, beta; 0, 1)mat(1, 0; (alpha-1)beta^(-1), 1).
    $ <eq:6-1-1-beta-factorization>
    #block(sticky: true)[If $beta=gamma=0$ we have]
    // E026: bottom-right entry of the last factor is misprinted as 0.
    $
      mat(alpha, 0; 0, alpha^(-1))
      =mat(1, 0; alpha^(-1)-1, 1)mat(1, 1; 0, 1)
      mat(1, 0; alpha-1, 1)mat(1, -alpha^(-1); 0, 1).
    $ <eq:6-1-1-diagonal-factorization>
    It is clear from these relations that $S L_2(K)$ is generated in the manner
    described.#linebreak()#qed

    #block(sticky: true)[
      Let $R=CC[x,y]$ be the polynomial ring in two variables over $CC$ and
      $R_q$ be the subspace of polynomials which are homogeneous of degree $q$.
      $R_q$ has a basis
    ]
    $ x^q,x^(q-1)y,x^(q-2)y^2,dots,y^q $ <eq:6-1-polynomial-basis>
    #block(sticky: true)[and dimension $q+1$. An element]
    $ mat(alpha, beta; gamma, delta) $ <eq:6-1-polynomial-matrix>
    // E027: the original says SL_2(K), although R is C[x,y].
    #block(sticky: true)[
      of $S L_2(CC)$ operates on $R$ by the transformation
    ]
    $
      x & arrow.r alpha x+gamma y, \
      y & arrow.r beta x+delta y,
    $ <eq:6-1-polynomial-action>
    and $R_q$ is a representation space for $S L_2(CC)$ for each $q$ under this
    operation.

    #metadata((kind: "anchor")) <l:6-1-2>
    #block(sticky: true)[
      #smallcaps[Lemma 6.1.2.] _Let $v_i=x^i y^(q-i)$, $i=0,1,dots,q$. Then the
      images of $v_i$ under transformation by_
    ]
    $ mat(1, t; 0, 1) quad "and" quad mat(1, 0; t, 1) $
    <eq:6-1-2-generators>
    #block(sticky: true)[_are given by:_]
    $
      mat(1, t; 0, 1) dot v_i & =sum_(j=0)^(q-i) binom(q-i, j)t^j v_(i+j), \
      mat(1, 0; t, 1) dot v_i & =sum_(j=0)^i binom(i, j)t^j v_(i-j).
    $ <eq:6-1-2-actions>

    #source(96, "83")
    #block()[
      #block(sticky: true)[#smallcaps[Proof.] Since]
      $ mat(1, t; 0, 1) $ <eq:6-1-2-upper>
      #block(sticky: true)[
        transforms $x$ into itself and $y$ into $t x+y$, and
      ]
      $ mat(1, 0; t, 1) $ <eq:6-1-2-lower>
      transforms $y$ into itself and $x$ into $x+t y$, the result is clear. #qed

    ]
  ]

  #[
    #import "main-defs.typ": L, book-ref, chapter-ref, qed, source

    == The Homomorphism from $S L_2(CC)$ <sec:homomorphism-from-complex-sl2>

    #block(sticky: true)[
      We now consider the operation of the subgroup $lr(⟨X_r,X_(-r)⟩)$ of
      $G=frak(L)(CC)$ on the Lie algebra #L. Each $r$-chain of roots gives rise
      to a submodule of #L under $lr(⟨X_r,X_(-r)⟩)$ as follows. Let $s$ be a
      root linearly independent of $r$ which begins an $r$-chain. Let
    ]
    $ s,r+s,2r+s,dots,q r+s $ <eq:6-2-root-chain>
    #block(sticky: true)[
      be the $r$-chain of roots through $s$. Let $frak(M)_s$ be the subspace of
      #L defined by
    ]
    $
      frak(M)_s=frak(L)_s ⊕ frak(L)_(r+s) ⊕ dots
      ⊕ frak(L)_(q r+s).
    $ <eq:6-2-chain-submodule>
    Then $frak(M)_s$ is invariant under $lr(⟨X_r,X_(-r)⟩)$ by the results of
    #chapter-ref("chevalley-groups"). Let $frak(H)_r$ be the $1$-dimensional
    subspace of $frak(H)$ spanned by the co-root $h_r$ and $frak(H)_r^perp$ be
    the subspace of $frak(H)$ of elements $h$ with $(h,h_r)=0$. Then the
    subspaces $frak(L)_r ⊕ frak(H)_r ⊕ frak(L)_(-r)$ and $frak(H)_r^perp$ are
    invariant under the action of $lr(⟨X_r,X_(-r)⟩)$, and #L is the direct sum
    of these subspaces together with the spaces $frak(M)_s$ for the various
    $r$-chains of roots.

    #metadata((kind: "anchor")) <l:6-2-1>
    #block(sticky: true)[
      #smallcaps[Lemma 6.2.1.] _Let $r,s$ be linearly independent roots such
      that the $r$-chain through $s$ is_
    ]
    $ s,r+s,dots,q r+s. $ <eq:6-2-1-chain>
    #block(sticky: true)[
      _Let $frak(M)_s=frak(L)_s ⊕ dots ⊕ frak(L)_(q r+s)$ and write
      $f_i=e_(i r+s)$. Then $f_0,f_1,dots,f_q$ is a basis for $frak(M)_s$ and we
      have_
    ]
    $
        x_r (t) dot f_i & =sum_(j=0)^(q-i) ε_i ε_(i+1) dots ε_(i+j-1)
                          binom(i+j, j)t^j f_(i+j), \
      x_(-r)(t) dot f_i & =sum_(j=0)^i ε_(i-1) ε_(i-2) dots ε_(i-j)
                          binom(q-i+j, j)t^j f_(i-j),
    $ <eq:6-2-1-actions>
    #source(97, "84")
    #block(sticky: true)[
      _where the numbers $ε_0,ε_1,dots$ are all $plus.minus 1$ and are defined
      by_
    ]
    $ N_(r,i r+s)=ε_i (i+1). $ <eq:6-2-1-signs>
    (Note that $N_(r,i r+s)=plus.minus(i+1)$ by #book-ref(
      "th",
      "4-2-1",
      [4.2.1],
    ).)

    #block(sticky: true)[
      #smallcaps[Proof.] We know from #chapter-ref("chevalley-groups") that
    ]
    $
      x_r (t) dot e_(i r+s) & =sum_(j=0)^(q-i) M_(r,i r+s,j)t^j e_((i+j)r+s) \
                            & =sum_(j=0)^(q-i) ε_i ε_(i+1) dots ε_(i+j-1)
                              binom(i+j, j)t^j e_((i+j)r+s).
    $ <eq:6-2-1-positive-action>
    #block(sticky: true)[Similarly we have]
    $
      x_(-r)(t) dot e_(i r+s)=sum_(j=0)^i M_(-r,i r+s,j)t^j e_((i-j)r+s).
    $ <eq:6-2-1-negative-action>
    #block(sticky: true)[
      However, using relations #book-ref("th", "4-1-2", [4.1.2]) #book-ref(
        "eq",
        "4-1-2-i",
        [(i)],
      ), #book-ref("eq", "4-1-2-ii", [(ii)]), #book-ref(
        "eq",
        "4-1-2-iii",
        [(iii)],
      ) between the structure constants and also #book-ref(
        "l",
        "4-1-1",
        [4.1.1],
      ) we have
    ]
    $
      M_(-r,i r+s,j) & =frac(1, j!)N_(-r,i r+s)N_(-r,(i-1)r+s)dots \
                     & =frac(1, j!)N_(r,(i-1)r+s) dot frac(q-i+1, i)
                       dot N_(r,(i-2)r+s) dot frac(q-i+2, i-1)dots \
                     & =frac(1, j!)ε_(i-1)(q-i+1) dot ε_(i-2)(q-i+2)dots \
                     & =ε_(i-1)ε_(i-2)dots ε_(i-j)binom(q-i+j, j).
    $ <eq:6-2-1-negative-coefficient>
    #block(sticky: true)[Thus]
    $
      x_(-r)(t) dot e_(i r+s)
      =sum_(j=0)^i ε_(i-1)ε_(i-2)dots ε_(i-j)
      binom(q-i+j, j)t^j e_((i-j)r+s).
    $ <eq:6-2-1-negative-result>
    #qed

    #block(sticky: true)[
      We now show it is possible to choose a basis for $R_q$ so that
    ]
    $ mat(1, t; 0, 1), quad mat(1, 0; t, 1) $ <eq:6-2-basis-generators>
    operate on this basis in essentially the same way that $x_r (t),x_(-r)(t)$
    operate on the basis $f_0,f_1,dots,f_q$ of $frak(M)_s$.

    #source(98, "85")
    #metadata((kind: "anchor")) <l:6-2-2>
    #block(sticky: true)[
      #smallcaps[Lemma 6.2.2.] _Let $v_i=x^i y^(q-i) in R_q$ and
      $ε_0,ε_1,dots,ε_(q-1)$ be integers equal to $plus.minus 1$. Define_
    ]
    $
      u_i=ε_0 ε_1 dots ε_(i-1)binom(q, i)v_i,
      quad i=0,1,dots,q.
    $ <eq:6-2-2-basis>
    #block(sticky: true)[_Then_]
    $
      mat(1, t; 0, 1) dot u_i & =sum_(j=0)^(q-i) ε_i ε_(i+1)dots ε_(i+j-1)
                                binom(i+j, j)t^j u_(i+j), \
      mat(1, 0; t, 1) dot u_i & =sum_(j=0)^i ε_(i-1)ε_(i-2)dots ε_(i-j)
                                binom(q-i+j, j)t^j u_(i-j).
    $ <eq:6-2-2-actions>

    #block(sticky: true)[
      #smallcaps[Proof.] By #book-ref("l", "6-1-2", [6.1.2]) we have
    ]
    $
      mat(1, t; 0, 1) dot u_i & =sum_(j=0)^(q-i)
                                frac(
                                  binom(q-i, j)binom(q, i)ε_0 ε_1 dots ε_(i-1),
                                  binom(q, i+j)ε_0 ε_1 dots ε_(i+j-1)
                                )t^j u_(i+j) \
                              & =sum_(j=0)^(q-i)ε_i ε_(i+1)dots ε_(i+j-1)
                                binom(i+j, j)t^j u_(i+j).
    $ <eq:6-2-2-positive-calculation>
    $
      mat(1, 0; t, 1) dot u_i & =sum_(j=0)^i
                                frac(
                                  binom(i, j)binom(q, i)ε_0 ε_1 dots ε_(i-1),
                                  binom(q, i-j)ε_0 ε_1 dots ε_(i-j-1)
                                )t^j u_(i-j) \
                              & =sum_(j=0)^i binom(q-i+j, j)
                                ε_(i-1)ε_(i-2)dots ε_(i-j)t^j u_(i-j).
    $ <eq:6-2-2-negative-calculation>
    #qed

    #block(sticky: true)[
      We next compare the action of $lr(⟨X_r,X_(-r)⟩)$ on
      $frak(L)_r ⊕ frak(H)_r ⊕ frak(L)_(-r)$ with the action of $S L_2(CC)$ on
      $R_2$. We recall the relations:
    ]
    $
           x_r (t) dot e_r & =e_r, \
           x_r (t) dot h_r & =h_r-2t e_r, \
        x_r (t) dot e_(-r) & =e_(-r)+t h_r-t^2 e_r; \
         x_(-r)(t) dot e_r & =e_r-t h_r-t^2 e_(-r), \
         x_(-r)(t) dot h_r & =h_r+2t e_(-r), \
      x_(-r)(t) dot e_(-r) & =e_(-r).
    $ <eq:6-2-adjoint-actions>

    #source(99, "86")
    #metadata((kind: "anchor")) <l:6-2-3>
    #block(sticky: true)[
      #smallcaps[Lemma 6.2.3.] _Consider the basis $-x^2,2x y,y^2$ of $R_2$._
    ]
    $ mat(1, t; 0, 1) quad "and" quad mat(1, 0; t, 1) $
    <eq:6-2-3-generators>
    #block(sticky: true)[_operate on this basis as follows:_]
    $
      mat(1, t; 0, 1): quad & -x^2 arrow.r -x^2, \
                            & 2x y arrow.r 2x y-2t dot (-x^2), \
                            & y^2 arrow.r y^2+t dot (2x y)-t^2 dot (-x^2);
    $ <eq:6-2-3-upper-action>
    $
      mat(1, 0; t, 1): quad & -x^2 arrow.r -x^2-t dot (2x y)-t^2 dot y^2, \
                            & 2x y arrow.r 2x y+2t y^2, \
                            & y^2 arrow.r y^2.
    $ <eq:6-2-3-lower-action>

    #block(sticky: true)[#smallcaps[Proof.] This is clear. Thus]
    $ mat(1, t; 0, 1), quad mat(1, 0; t, 1) $ <eq:6-2-3-comparison>
    operate on the basis $-x^2,2x y,y^2$ of $R_2$ in the same way that
    $x_r (t),x_(-r)(t)$ operate on the basis $e_r,h_r,e_(-r)$ of
    $frak(L)_r ⊕ frak(H)_r ⊕ frak(L)_(-r)$. #qed

    We shall also require the following lemma.

    #block(breakable: false)[
      #metadata((kind: "anchor")) <l:6-2-4>
      #block(sticky: true)[#smallcaps[Lemma 6.2.4.] _Let_]
      $ mat(alpha, beta; gamma, delta) in S L_2(CC). $ <eq:6-2-4-matrix>
      #block(sticky: true)[_Then_]
      $
        mat(alpha, beta; gamma, delta) dot 2x y
        =2x y+2(-alpha beta dot (-x^2)+beta gamma dot (2x y)+gamma
          delta dot (y^2)).
      $ <eq:6-2-4-action>


    ]

    #smallcaps[Proof.] This is evident since $alpha delta-beta gamma=1$. #qed

    We can now prove the existence of the required homomorphism from
    $S L_2(CC)$.

    #source(100, "87")
    #metadata((kind: "anchor")) <p:6-2-5>
    #block(sticky: true)[
      #smallcaps[Proposition 6.2.5.] _There is a homomorphism from $S L_2(CC)$
      onto the subgroup $lr(⟨X_r,X_(-r)⟩)$ of $G=frak(L)(CC)$ under which_
    ]
    $
      mat(1, t; 0, 1) & arrow.r x_r (t), \
      mat(1, 0; t, 1) & arrow.r x_(-r)(t).
    $ <eq:6-2-5-generator-images>

    #block(sticky: true)[
      #smallcaps[Proof.] Write $frak(M)_r=frak(L)_r ⊕ frak(H)_r ⊕ frak(L)_(-r)$.
      Then we have a decomposition of #L
    ]
    $
      frak(L)=frak(H)_r^perp ⊕ frak(M)_r
      ⊕ sum_(s in Gamma)frak(M)_s
    $ <eq:6-2-5-decomposition>
    into a direct sum of submodules with respect to $lr(⟨X_r,X_(-r)⟩)$, where
    $Gamma$ is the set of roots which are independent of $r$ and begin an
    $r$-chain. Now $lr(⟨X_r,X_(-r)⟩)$ operates as the identity on
    $frak(H)_r^perp$. Lemmas #book-ref("l", "6-2-1", [6.2.1]), #book-ref(
      "l",
      "6-2-2",
      [6.2.2],
    ), and #book-ref("l", "6-2-3", [6.2.3]) show that there exists a module
    $frak(M)$ for $S L_2(CC)$, which is a direct sum of spaces of homogeneous
    polynomials with a trivial module, such that
    $ mat(1, t; 0, 1), quad mat(1, 0; t, 1) $ <eq:6-2-5-module-actions>
    #block(sticky: true)[
      operate on $frak(M)$ in the same way as $x_r (t),x_(-r)(t)$ operate on #L.
      Since the elements
    ]
    $ mat(1, t; 0, 1), quad mat(1, 0; t, 1) $ <eq:6-2-5-generators>
    #block(sticky: true)[
      for $t in CC$ generate $S L_2(CC)$, there is a homomorphism from
      $S L_2(CC)$ onto $lr(⟨X_r,X_(-r)⟩)$ under which
    ]
    $
      mat(1, t; 0, 1) arrow.r x_r (t) quad "and" quad
      mat(1, 0; t, 1) arrow.r x_(-r)(t).
    $ <eq:6-2-5-homomorphism>
    #qed
  ]

  #[
    #import "main-defs.typ": L, book-ref, qed, section-ref, source

    == The Homomorphism from $S L_2(K)$ <sec:homomorphism-from-sl2>

    We now transfer from the complex field to an arbitrary field $K$ and
    establish the following result.

    #source(101, "88")
    #metadata((kind: "anchor")) <th:6-3-1>
    #block(sticky: true)[
      #smallcaps[Theorem 6.3.1.] _Let $K$ be any field. Then there is a
      homomorphism from $S L_2(K)$ onto the subgroup $lr(⟨X_r,X_(-r)⟩)$ of
      $G=frak(L)(K)$ under which_
    ]
    $
      mat(1, t; 0, 1) & arrow.r x_r (t), \
      mat(1, 0; t, 1) & arrow.r x_(-r)(t).
    $ <eq:6-3-1-generator-images>

    #block(sticky: true)[
      #smallcaps[Proof.] We already have the existence of such a homomorphism
      when $K=CC$. Consider the module $frak(M)$ for $S L_2(CC)$ constructed in
      #section-ref("homomorphism-from-complex-sl2"). $frak(M)$ is a direct sum
      of modules $R_q$ with a trivial module, and we obtain a basis for
      $frak(M)$ by combining the natural bases of the components $R_q$ with a
      basis of the trivial module. With respect to this basis of $frak(M)$ an
      element
    ]
    $ mat(alpha, beta; gamma, delta) $ <eq:6-3-1-complex-matrix>
    #block(sticky: true)[
      of $S L_2(CC)$ is represented by a matrix whose entries are polynomials in
      $alpha,beta,gamma,delta$ with coefficients in $ZZ$. This is clear because
      each component $R_q$ gives such a polynomial representation. This basis
      for $frak(M)$ corresponds to a basis for #L as in #section-ref(
        "homomorphism-from-complex-sl2",
      ). This basis for #L is adapted to the decomposition
    ]
    $
      frak(L)=frak(H)_r^perp ⊕ frak(M)_r ⊕ sum_(s in Gamma)frak(M)_s
    $ <eq:6-3-1-decomposition>
    #block(sticky: true)[
      of #book-ref("p", "6-2-5", [6.2.5]), but is not necessarily a Chevalley
      basis of #L. However, it differs from a Chevalley basis only on $frak(H)$.
      It will be necessary to show that when we change to a basis of $frak(M)$
      corresponding to a Chevalley basis of #L, the element
    ]
    $ mat(alpha, beta; gamma, delta) $ <eq:6-3-1-chevalley-matrix>
    of $S L_2(CC)$ will still be represented by a matrix
    $F(alpha,beta,gamma,delta)$ whose entries are polynomials in
    $alpha,beta,gamma,delta$ with coefficients in $ZZ$.

    With this in mind we first transform the basis elements of #L which lie in
    $frak(H)$ by an element of the Weyl group which transforms $h_r$ into a
    fundamental co-root. Since the elements of the Weyl group operate on
    $frak(H)$ by integral unimodular transformations, this will not affect the
    property #source(102, "89")with which we are concerned. Thus we may assume
    that $h_r$ is a fundamental co-root.

    #block(sticky: true)[
      Now the remaining elements of the Chevalley basis which lie in $frak(H)$
      are the other fundamental co-roots. Let $h_s$, $s in Pi$, be one of these.
      Then we have
    ]
    $ h_s=lambda dot h_r+y, $ <eq:6-3-1-coroot-decomposition>
    #block(sticky: true)[where $y in frak(H)_r^perp$ and]
    $ lambda=frac((h_r,h_s), (h_r,h_r))=frac((s,r), (s,s)). $
    <eq:6-3-1-coroot-coefficient>
    #block(sticky: true)[
      In particular, $2lambda$ is an integer. We note that if
      $theta in lr(⟨X_r,X_(-r)⟩)$ then we have
    ]
    $ theta(h_s)=lambda theta(h_r)+y=h_s+lambda(theta(h_r)-h_r). $
    <eq:6-3-1-coroot-action>

    #block(sticky: true)[
      Now consider the action of $S L_2(CC)$ on $frak(M)$. Let $m_r,m_s$ be
      basis elements of $frak(M)$ corresponding to $h_r,h_s in frak(L)$. Let
    ]
    $ T=mat(alpha, beta; gamma, delta) in S L_2(CC). $ <eq:6-3-1-t>
    #block(sticky: true)[Then we have]
    $ T(m_s)=m_s+lambda dot (T(m_r)-m_r). $ <eq:6-3-1-basis-action>
    By #book-ref("l", "6-2-4", [6.2.4]), $T(m_r)-m_r$ is a linear combination of
    basis elements of $frak(M)$ with coefficients which are polynomials in
    $alpha,beta,gamma,delta$ with _even_ integer coefficients. Since $2lambda$
    is an integer the entries in the matrix $F(alpha,beta,gamma,delta)$ are
    polynomials in $alpha,beta,gamma,delta$ with coefficients in $ZZ$.

    #block(sticky: true)[
      We also observe from #book-ref("l", "6-2-4", [6.2.4]) that the polynomials
      in $alpha,beta,gamma,delta$ occurring as coefficients in $T(m_r)-m_r$ are
      all homogeneous of degree $2$. Since $alpha delta-beta gamma=1$ we may
      write
    ]
    $ T(m_s)=(alpha delta-beta gamma)m_s+lambda dot (T(m_r)-m_r). $
    <eq:6-3-1-homogeneous-action>
    Thus $T(m_s)$ is a linear combination of basis elements of $frak(M)$ with
    coefficients which may be taken as homogeneous polynomials in
    $alpha,beta,gamma,delta$ of degree $2$.

    #block(sticky: true)[We now transfer to the field $K$ and define a map]
    $ mat(alpha, beta; gamma, delta) arrow.r F(alpha,beta,gamma,delta), $
    <eq:6-3-1-polynomial-map>
    #block(sticky: true)[
      where $alpha,beta,gamma,delta in K$. This maps $S L_2(K)$ into a group of
      matrices over $K$ obtained by replacing the variables in the polynomial
      entries of $F(alpha,beta,gamma,delta)$ #source(103, "90")by elements of
      $K$. The condition for this map to be a homomorphism is the vanishing of
      the matrix
    ]
    $
      & F(alpha alpha'+beta gamma',alpha beta'+beta delta',
          gamma alpha'+delta gamma',gamma beta'+delta delta') \
      & quad -F(alpha,beta,gamma,delta)F(alpha',beta',gamma',delta')
    $ <eq:6-3-1-homomorphism-condition>
    for all $alpha,beta,gamma,delta,alpha',beta',gamma',delta' in K$ satisfying
    $alpha delta-beta gamma=1$, $alpha' delta'-beta' gamma'=1$. This matrix
    certainly vanishes for all
    $alpha,beta,gamma,delta,alpha',beta',gamma',delta' in CC$ satisfying
    $alpha delta-beta gamma=1$, $alpha' delta'-beta' gamma'=1$, and we shall
    prove that the same is true for $K$.

    We take a Chevalley basis of #L and decompose it into disjoint subsets
    consisting of:

    (i) the root vectors corresponding to the roots in a given $r$-chain.

    #block(sticky: true)[
      (ii) the remaining set $e_r,e_(-r),h_s$ for $s in Pi$. The basis obtained
      for $frak(M)$ corresponding to this Chevalley basis of #L decomposes in an
      analogous way, and the submodules spanned by the basis vectors in each
      individual subset are invariant under $S L_2(CC)$. The matrix representing
    ]
    $ mat(alpha, beta; gamma, delta) $ <eq:6-3-1-chain-matrix>
    #block(sticky: true)[
      on a submodule corresponding to an $r$-chain of roots of length $q+1$ has
      as its coefficients homogeneous polynomials in $alpha,beta,gamma,delta$ of
      degree $q$, and the matrix representing
    ]
    $ mat(alpha, beta; gamma, delta) $ <eq:6-3-1-cartan-matrix>
    #block(sticky: true)[
      on the submodule corresponding to ${e_r,e_(-r),h_s; s in Pi}$ has
      coefficients which are homogeneous polynomials in $alpha,beta,gamma,delta$
      of degree $2$, as has been pointed out above. Thus the matrix
      $F(alpha,beta,gamma,delta)$ representing
    ]
    $ mat(alpha, beta; gamma, delta) $ <eq:6-3-1-block-matrix>
    #block(sticky: true)[
      on $frak(M)$ is a diagonal sum of matrices $F_i (alpha,beta,gamma,delta)$
      in which the coefficients are homogeneous polynomials in
      $alpha,beta,gamma,delta$ of constant degree. Also the matrix
    ]
    $
      & G(alpha,beta,gamma,delta,alpha',beta',gamma',delta') \
      & quad =F(alpha alpha'+beta gamma',alpha beta'+beta delta',
          gamma alpha'+delta gamma',gamma beta'+delta delta') \
      & quad quad -F(alpha,beta,gamma,delta)F(alpha',beta',gamma',delta')
    $ <eq:6-3-1-g>
    is a diagonal sum of matrices
    $G_i (alpha,beta,gamma,delta,alpha',beta',gamma',delta')$ in which the
    coefficients are homogeneous polynomials of constant degree in each of
    $alpha,beta,gamma,delta$ and $alpha',beta',gamma',delta'$ separately.

    #source(104, "91")
    #block(sticky: true)[Since $frak(M)$ is a module for $S L_2(CC)$, we have]
    $ G_i (alpha,beta,gamma,delta,alpha',beta',gamma',delta')=0 $
    <eq:6-3-1-g-vanishing>
    #block(sticky: true)[
      whenever $alpha delta-beta gamma=1$, $alpha' delta'-beta' gamma'=1$. Since
      $G_i$ is homogeneous in $alpha,beta,gamma,delta$ and also in
      $alpha',beta',gamma',delta'$, we have $G_i=0$ whenever
      $alpha delta-beta gamma=xi$, $alpha' delta'-beta' gamma'=xi'$, for all
      $xi,xi'!=0$. Let $P(alpha,beta,gamma,delta,alpha',beta',gamma',delta')$ be
      a matrix coefficient of $G_i$. Then the polynomial
    ]
    $
      & P(alpha,beta,gamma,delta,alpha',beta',gamma',delta') \
      & quad dot (alpha delta-beta gamma)(alpha' delta'-beta' gamma')
    $ <eq:6-3-1-p-vanishing>
    #block(sticky: true)[
      vanishes for all
      $alpha,beta,gamma,delta,alpha',beta',gamma',delta' in CC$, so is
      identically zero. Since $alpha delta-beta gamma$ and
      $alpha' delta'-beta' gamma'$ are not identically zero, $P$ is identically
      zero. Thus the matrix $G$ is identically zero and we have
    ]
    $
      & F(alpha,beta,gamma,delta)F(alpha',beta',gamma',delta') \
      & quad equiv F(alpha alpha'+beta gamma',alpha beta'+beta delta',
          gamma alpha'+delta gamma',gamma beta'+delta delta')
    $ <eq:6-3-1-polynomial-identity>
    #block(sticky: true)[
      in the sense that equating matrix coefficients gives a polynomial
      identity. This remains true when we transfer to the field $K$. Thus the
      map
    ]
    $ mat(alpha, beta; gamma, delta) arrow.r F(alpha,beta,gamma,delta) $
    <eq:6-3-1-field-homomorphism>
    with $alpha,beta,gamma,delta in K$ is a homomorphism.

    #block(sticky: true)[Let]
    $
        A_r (zeta) & =F(1,zeta,0,1), \
      A_(-r)(zeta) & =F(1,0,zeta,1), quad zeta in CC.
    $ <eq:6-3-1-complex-generators>
    #block(sticky: true)[
      Then $A_r (zeta),A_(-r)(zeta)$ are the matrices representing
      $x_r (zeta),x_(-r)(zeta)$ with respect to the Chevalley basis of #L. For
      each $t in K$ let $A_r (t),A_(-r)(t)$ be the matrices obtained by
      replacing the complex variable $zeta$ in $A_r (zeta),A_(-r)(zeta)$ by the
      element $t$ of $K$. Then $A_r (t),A_(-r)(t)$ are the matrices representing
      the elements $x_r (t),x_(-r)(t)$ of $frak(L)(K)$, by definition of the
      latter. We have
    ]
    $
        A_r (t) & =F(1,t,0,1), \
      A_(-r)(t) & =F(1,0,t,1), quad "for" t in K.
    $ <eq:6-3-1-field-generators>
    #block(sticky: true)[Now $S L_2(K)$ is generated by the matrices]
    $ mat(1, t; 0, 1), quad mat(1, 0; t, 1) $ <eq:6-3-1-sl2-generators>
    #block(sticky: true)[
      for $t in K$ and so the group of matrices $F(alpha,beta,gamma,delta)$ with
      $alpha,beta,gamma,delta in K$ and $alpha delta-beta gamma=1$ is generated
      by $A_r (t),A_(-r)(t)$ for $t in K$. This group of matrices #source(
        105,
        "92",
      )is therefore isomorphic to the subgroup $lr(⟨X_r,X_(-r)⟩)$ of
      $frak(L)(K)$. Thus we have a homomorphism from $S L_2(K)$ onto
      $lr(⟨X_r,X_(-r)⟩)$ under which
    ]
    $
      mat(1, t; 0, 1) arrow.r x_r (t) quad "and" quad
      mat(1, 0; t, 1) arrow.r x_(-r)(t).
    $ <eq:6-3-1-conclusion>
    This completes the proof. #qed
  ]

  #[
    #import "main-defs.typ": L, book-ref, qed, section-ref, source

    == The Elements $h_r (lambda)$ and $n_r$ <sec:elements-hr-and-nr>

    #block(sticky: true)[
      We shall denote by $phi_r$ the homomorphism from $S L_2(K)$ into
      $lr(⟨X_r,X_(-r)⟩)$ whose existence has just been proved. We consider next
      the images under $phi_r$ of the diagonal matrices
    ]
    $ mat(lambda, 0; 0, lambda^(-1)) $ <eq:6-4-diagonal-matrix>
    #block(sticky: true)[in $S L_2(K)$ and the monomial matrix]
    $ mat(0, 1; -1, 0). $ <eq:6-4-monomial-matrix>
    The images of these matrices play an important rôle in the sequel.

    #block(breakable: false)[
      #metadata((kind: "anchor")) <p:6-4-1>
      #block(sticky: true)[#smallcaps[Proposition 6.4.1.] _Let_]
      $
        h_r (lambda)=phi_r mat(lambda, 0; 0, lambda^(-1)).
      $ <eq:6-4-1-definition>
      #block(sticky: true)[
        _Then $h_r (lambda)$ operates on the Chevalley basis of $frak(L)_K$ in
        the following manner:_
      ]
      // E028: the set of roots is Phi; the source prints an undefined Sigma
      // here.
      $
        h_r (lambda) dot h_s & =h_s, quad s in Pi, \
        h_r (lambda) dot e_s & =lambda^(A_(r s))e_s, quad s in Phi.
      $ <eq:6-4-1-actions>
    ]

    #block()[
      #smallcaps[Proof.] Suppose $s$ is linearly independent of $r$. Let
      $overline(s)$ be the root which begins the $r$-chain through $s$, and let
      $s=i r+overline(s)$.
    ]
    #block(sticky: true)[
      Then $h_r (lambda)$ operates on $e_s$ in the same way that
    ]
    $ mat(lambda, 0; 0, lambda^(-1)) $ <eq:6-4-1-polynomial-matrix>
    #block(sticky: true)[operates on]
    $ u_i=ε_0 ε_1 dots ε_(i-1)binom(q, i)v_i, $ <eq:6-4-1-polynomial-basis>
    #source(106, "93")
    #block(sticky: true)[where $v_i=x^i y^(q-i)$. Now]
    $
      mat(lambda, 0; 0, lambda^(-1)) dot x^i y^(q-i)
      =lambda^(2i-q)x^i y^(q-i).
    $ <eq:6-4-1-monomial-action>
    #block(sticky: true)[Thus we have]
    $ mat(lambda, 0; 0, lambda^(-1)) dot u_i=lambda^(2i-q)u_i $
    <eq:6-4-1-basis-action>
    #block(sticky: true)[and so]
    $ h_r (lambda) dot e_s=lambda^(2i-q)e_s. $ <eq:6-4-1-root-action>
    #block(sticky: true)[However, since the $r$-chain through $s$ is]
    $ -i r+s,dots,s,dots,(q-i)r+s, $ <eq:6-4-1-root-chain>
    #block(sticky: true)[
      we have $A_(r s)=i-(q-i)=2i-q$ by #section-ref(
        "roots-of-simple-lie-algebras",
      ). Hence
    ]
    $ h_r (lambda) dot e_s=lambda^(A_(r s))e_s. $ <eq:6-4-1-root-weight>
    #block(sticky: true)[
      We know also that $h_r (lambda)$ operates on $e_r,h_r,e_(-r)$ in the same
      way that
    ]
    $ mat(lambda, 0; 0, lambda^(-1)) $ <eq:6-4-1-adjoint-matrix>
    #block(sticky: true)[operates on $-x^2,2x y,y^2$. Now]
    $
      mat(lambda, 0; 0, lambda^(-1)): quad & -x^2 arrow.r lambda^2(-x^2) \
                                           & 2x y arrow.r 2x y \
                                           & y^2 arrow.r lambda^(-2)y^2.
    $ <eq:6-4-1-adjoint-action>
    Thus $h_r (lambda) dot e_r=lambda^2 e_r$,
    $h_r (lambda) dot e_(-r)=lambda^(-2)e_(-r)$. Finally, $h_r (lambda)$
    operates trivially on $h_r$ and $frak(H)_r^perp$, so operates trivially on
    the whole of $frak(H)$. #qed

    #block(breakable: false)[
      #metadata((kind: "anchor")) <p:6-4-2>
      #block(sticky: true)[#smallcaps[Proposition 6.4.2.] _Let_]
      $ n_r=phi_r mat(0, 1; -1, 0). $ <eq:6-4-2-definition>
      #block(sticky: true)[
        _Then $n_r$ operates on the Chevalley basis of $frak(L)_K$ as follows:_
      ]
      $
        n_r dot h_s & =h_(w_r (s)), \
        n_r dot e_s & =eta_(r,s)e_(w_r (s)), quad "where"
                      eta_(r,s)=plus.minus 1.
      $ <eq:6-4-2-actions>
    ]

    #source(107, "94")
    #block()[
      #smallcaps[Proof.] Suppose $s$ is linearly independent of $r$ and let
      $overline(s)=-i r+s$ be the root beginning the $r$-chain through $s$. Then
      $n_r$ operates on $e_s$ in the same way that
    ]
    $ mat(0, 1; -1, 0) $ <eq:6-4-2-polynomial-matrix>
    #block(sticky: true)[operates on]
    $ u_i=ε_0 ε_1 dots ε_(i-1)binom(q, i)v_i, $ <eq:6-4-2-polynomial-basis>
    #block(sticky: true)[where $v_i=x^i y^(q-i)$. Now we have]
    $ mat(0, 1; -1, 0): x^i y^(q-i)=(-1)^i x^(q-i)y^i. $
    <eq:6-4-2-monomial-action>
    #block(sticky: true)[Thus]
    $ mat(0, 1; -1, 0): v_i=(-1)^i v_(q-i) $ <eq:6-4-2-standard-action>
    #block(sticky: true)[and so]
    $
      mat(0, 1; -1, 0): u_i
      =(-1)^i frac(ε_0 ε_1 dots ε_(i-1), ε_0 ε_1 dots ε_(q-i-1))u_(q-i).
    $ <eq:6-4-2-basis-action>
    #block(sticky: true)[It follows that]
    $ n_r dot e_s=eta_(r,s)e_((q-i)r+overline(s))=eta_(r,s)e_(w_r (s)), $
    <eq:6-4-2-root-action>
    #block(sticky: true)[where]
    $
      eta_(r,s)=(-1)^i frac(ε_0 ε_1 dots ε_(i-1), ε_0 ε_1 dots ε_(q-i-1))
      =plus.minus 1.
    $ <eq:6-4-2-sign>
    #block(sticky: true)[
      Also $n_r$ operates on $e_r,h_r,e_(-r)$ in the same way that
    ]
    $ mat(0, 1; -1, 0) $ <eq:6-4-2-adjoint-matrix>
    operates on $-x^2,2x y,y^2$.

    #block(sticky: true)[Now]
    $
      mat(0, 1; -1, 0): quad & -x^2 arrow.r -y^2, \
                             & 2x y arrow.r -2x y, \
                             & y^2 arrow.r x^2.
    $ <eq:6-4-2-adjoint-action>
    Thus $n_r dot e_r=-e_(-r)$ and $n_r dot e_(-r)=-e_r$. On $frak(H)$ we have
    $n_r dot h_r=-h_r$ and $n_r dot h=h$ if $(h_r,h)=0$. Therefore
    $n_r dot h_s=h_(w_r (s))$ for all $s in Phi$. #qed

    #source(108, "95")
    #metadata((kind: "anchor")) <p:6-4-3>
    #block(sticky: true)[
      #smallcaps[Proposition 6.4.3.] _The numbers $eta_(r,s)$ defined in
      #book-ref(
        "p",
        "6-4-2",
        [6.4.2],
      ) satisfy the conditions:_
    ]
    $
                     eta_(r,r) & =-1, \
                    eta_(r,-r) & =-1, \
      eta_(r,s)eta_(r,w_r (s)) & =(-1)^(A_(r s)), \
           eta_(r,s)eta_(r,-s) & =1.
    $ <eq:6-4-3-sign-relations>

    #block(sticky: true)[
      #smallcaps[Proof.] It has been shown in #book-ref("p", "6-4-2", [6.4.2])
      that $eta_(r,r)=-1$ and $eta_(r,-r)=-1$. We therefore suppose that $r,s$
      are linearly independent. Let
    ]
    $ -p r+s,dots,s,dots,q r+s $ <eq:6-4-3-root-chain>
    #block(sticky: true)[be the $r$-chain of roots through $s$. Then]
    $ eta_(r,s)=(-1)^p frac(ε_0 ε_1 dots ε_(p-1), ε_0 ε_1 dots ε_(q-1)), $
    <eq:6-4-3-sign>
    #block(sticky: true)[where]
    $ N_(r,(i-p)r+s)=ε_i (i+1). $ <eq:6-4-3-chain-signs>
    #block(sticky: true)[
      The above chain is also the $r$-chain through $w_r (s)=(q-p)r+s$. Thus
    ]
    $
      eta_(r,w_r (s))=(-1)^q
      frac(ε_0 ε_1 dots ε_(q-1), ε_0 ε_1 dots ε_(p-1)).
    $ <eq:6-4-3-reflected-sign>
    #block(sticky: true)[Hence]
    $ eta_(r,s)eta_(r,w_r (s))=(-1)^(p+q)=(-1)^(p-q)=(-1)^(A_(r s)). $
    <eq:6-4-3-reflected-product>
    #block(sticky: true)[Now consider the $r$-chain through $-s$. This is]
    $ -q r-s,dots,-s,dots,p r-s. $ <eq:6-4-3-negative-chain>
    #block(sticky: true)[Therefore we have]
    $
      eta_(r,-s)=(-1)^q
      frac(
        overline(ε)_0 overline(ε)_1 dots overline(ε)_(q-1),
        overline(ε)_0 overline(ε)_1 dots overline(ε)_(p-1)
      ),
    $ <eq:6-4-3-negative-sign>
    #block(sticky: true)[where]
    $ N_(r,(i-q)r-s)=overline(ε)_(i)(i+1). $ <eq:6-4-3-negative-chain-signs>
    #block(sticky: true)[
      However, the relations between the structure constants proved in
      #book-ref(
        "th",
        "4-1-2",
        [4.1.2],
      ) show that
    ]
    $
      frac(N_(r,j r+s), ((j+1)r+s,(j+1)r+s))
      &=frac(N_(-(j+1)r-s,r), (j r+s,j r+s)) \
      &=-frac(N_(r,-(j+1)r-s), (j r+s,j r+s)).
    $ <eq:6-4-3-structure-constants>

    #source(109, "96")
    #block(sticky: true)[
      Since each $ε,overline(ε)$ is just the sign of the corresponding structure
      constant it follows that
    ]
    // E029: include the negative j values needed for the denominator below.
    $ ε_(j+p)=-overline(ε)_(q-j-1), quad j=-p,-p+1,dots,(q-1). $
    <eq:6-4-3-sign-reversal>
    #block(sticky: true)[Thus]
    $
      eta_(r,-s) & =(-1)^q frac(
                     overline(ε)_0 overline(ε)_1 dots overline(ε)_(q-1),
                     overline(ε)_0 overline(ε)_1 dots overline(ε)_(p-1)
                   ) \
                 & =(-1)^p frac(
                     ε_(p+q-1)ε_(p+q-2)dots ε_p,
                     ε_(p+q-1)ε_(p+q-2)dots ε_q
                   ).
    $ <eq:6-4-3-negative-sign-rewritten>
    #block(sticky: true)[It follows that]
    #block(breakable: false)[
      $
        eta_(r,s)eta_(r,-s)
        &=(-1)^p frac(ε_0 ε_1 dots ε_(p-1), ε_0 ε_1 dots ε_(q-1)) \
        &quad dot (-1)^p frac(ε_(p+q-1)dots ε_p, ε_(p+q-1)dots ε_q)=1.
      $ <eq:6-4-3-opposite-product>
      #qed
    ]

    #block(sticky: true)[
      We shall also need some properties of the elements
    ]
    $ n_r (t)=phi_r mat(0, t; -t^(-1), 0), $ <eq:6-4-n-t>
    which are stated in the following lemma.

    #metadata((kind: "anchor")) <l:6-4-4>
    #block(sticky: true)[#smallcaps[Lemma 6.4.4.]]
    #enum(
      numbering: "(i)",
      indent: 1.1em,
      body-indent: 0.5em,
      [
        #metadata((kind: "anchor")) <eq:6-4-4-i>
        $n_r (1)=n_r$, $quad n_r (-1)=n_r^(-1)$,
      ],
      [
        #metadata((kind: "anchor")) <eq:6-4-4-ii>
        $n_r (t)=x_r (t)x_(-r)(-t^(-1))x_r (t)$,
      ],
      [
        #metadata((kind: "anchor")) <eq:6-4-4-iii>
        $h_r (t)=n_r (t)n_r (-1)$.
      ],
    )

    #smallcaps[Proof.] These results follow from the corresponding relations in
    $S L_2(K)$ using the homomorphism $phi_r$. #qed

    We note that Proposition #book-ref("p", "6-4-2", [6.4.2]) shows that the
    element $n_r$ of $G$ operates on $frak(H)$ in the same way as the element
    $w_r$ of $W$ and that $n_r$ also permutes the root spaces $frak(L)_s$,
    $s in Phi$, in the same way as $w_r$. This relationship between $n_r$ and
    $w_r$ has many implications which will be made use of in the development to
    follow.
  ]
]

#import "chapter-preview.typ": chapter-preview
#chapter-preview(6, chapter)
