#import "statements.typ": corollary, lemma, proof, theorem

#[
  #import "main-defs.typ": L, bib-ref, ix, nx, source
  #let ad = math.op("ad")

  #source(110, "97")
  #heading(level: 1)[
    The Diagonal and Monomial #box[Subgroups]
  ] <ch:diagonal-and-monomial-subgroups>

  == Properties of the Subgroup $H$ <sec:diagonal-subgroup>

  #nx("H", [$H$], group: "latin-h")[The diagonal subgroup of a Chevalley group
    $G$]#nx(
    "q-1-dots-q-l",
    [$q_1,dots,q_l$],
    group: "latin-q",
    after: "QQ",
  )[The fundamental weights of a simple Lie algebra]#ix(
    "diagonal subgroup $H$, of a Chevalley group",
  )#block(sticky: true)[
    We have introduced the elements $h_r (lambda)$ of the Chevalley group
    $G=frak(L)(K)$ as the images of the diagonal matrices
  ]
  $ mat(lambda, 0; 0, lambda^(-1)) $ <eq:diagonal-subgroup-diagonal-matrix>
  under the homomorphism from $S L_2(K)$ into $lr(⟨X_r,X_(-r)⟩)$. We define $H$
  to be the subgroup of $G$ generated by the elements $h_r (lambda)$ for all
  $r in Phi$, $lambda!=0 in K$.

  #block(sticky: true)[
    Now $h_r (lambda)$ operates on the Chevalley basis of $frak(L)_K$ by
  ]
  $
    h_r (lambda) dot h_s=h_s, quad h_r (lambda) dot e_s=lambda^(A_(r s))e_s.
  $ <eq:diagonal-subgroup-diagonal-action>
  Hence each element of $H$ is an automorphism of $frak(L)_K$ which operates
  trivially on $frak(H)_K$ and transforms each root vector $e_s$ into a multiple
  of itself. The coefficients arising in #ix("$K$-character")#nx(
    "chi",
    [$chi$],
    group: "greek-χ",
  )[A $K$-character of $P$]#nx("chi", [$chi$], group: "greek-χ")[A $K$-character
    of $P$]this way define #nx(
    "P",
    [$P$],
    group: "latin-p",
    after: "p-1-dots-p-l",
  )[The additive group generated by $p_1,dots,p_l$]naturally a character on the
  additive group generated by the roots, as we shall now describe.

  #block(sticky: true)[
    Let $P=ZZ Phi$, the set of all linear combinations of elements of $Phi$ with
    rational integer coefficients. $P$ is the additive group generated by the
    roots of #L. It is a free abelian group of rank $l$ and has a basis
    consisting of the set of fundamental roots $Pi={p_1,p_2,dots,p_l}$. A
    homomorphism from the additive group $P$ #nx(
      "K-star",
      [$K^*$],
      group: "latin-k",
    )[The multiplicative group of non-zero elements of $K$]into the
    multiplicative group $K^*$ of non-zero elements of $K$ is called a
    $K$-character of $P$. Thus a $K$-character of $P$ is a map from $P$ into
    $K^*$ satisfying the conditions
  ]
  $
    chi(a+b) & =chi(a)chi(b), quad a,b in P, \
     chi(-a) & =chi(a)^(-1), quad a in P.
  $ <eq:diagonal-subgroup-character-laws>
  #block(sticky: true)[
    Now a $K$-character of $P$ is uniquely determined by its values on the
    fundamental roots. Thus if a map from $Phi$ into $K^*$ can be extended to a
    $K$-character of $P$, this extension is uniquely determined. We consider
    such maps of the form
  ]
  $ s arrow.r lambda^(A_(r s)), quad r in Phi, lambda in K^*. $
  <eq:diagonal-subgroup-root-character>

  #source(111, "98")
  #block(sticky: true)[
    #metadata((kind: "anchor")) <def:root-character-extension>#nx(
      "chi-r-lambda",
      [$chi_(r,lambda)$],
      group: "greek-χ",
      definition: [@def:root-character-extension],
    )[The $K$-character of $P$ taking value $lambda^(A_(r s))$ at the root
      $s$]#nx(
      "chi-r-lambda",
      [$chi_(r,lambda)$],
      group: "greek-χ",
      definition: [@def:root-character-extension],
    )[The $K$-character of $P$ taking value $lambda^(A_(r s))$ at the root
      $s$] This map from $Phi$ into $K^*$ can be extended to a $K$-character of
    $P$. For let $chi_(r,lambda)$ be the map from $P$ into $K^*$ given by
  ]
  $
    chi_(r,lambda)(a)=lambda^(2(r,a)\/(r,r)).
  $ <eq:diagonal-subgroup-character-extension>
  Then $chi_(r,lambda)$ is a $K$-character of $P$ which takes the value
  $lambda^(A_(r s))$ at the root $s$.

  #block(sticky: true)[
    Now the $K$-characters of $P$ form a multiplicative group. For if
    $chi_1,chi_2$ are $K$-characters so is $chi_1 chi_2$, where
  ]
  $
    chi_1 chi_2(a)=chi_1(a)chi_2(a), quad a in P.
  $ <eq:diagonal-subgroup-character-product>
  #block(sticky: true)[
    #metadata((kind: "anchor")) <def:character-automorphism>#nx(
      "h-chi",
      [$h(chi)$],
      group: "latin-h",
      after: "H-r",
      definition: [@def:character-automorphism],
    )[The automorphism of the Lie algebra $frak(L)_K$ determined by a
      $K$-character $chi$ of $P$] Moreover, each $K$-character $chi$ of $P$
    gives rise to an automorphism $h(chi)$ of $frak(L)_K$ defined by
  ]
  $
    h(chi) dot h_s=h_s, quad h(chi) dot e_s=chi(s)e_s.
  $ <eq:diagonal-subgroup-h-character>
  #block(sticky: true)[
    Observe that if $chi=chi_(r,lambda)$ then $h(chi)=h_r (lambda)$. The
    automorphisms of $frak(L)_K$ of the form $h(chi)$ form a subgroup $hat(H)$
    #nx("H-hat", [$hat(H)$], group: "latin-h", after: "h-chi")[The group of
      automorphisms $h(chi)$ of $frak(L)_K$]of the full automorphism group of
    $frak(L)_K$. For
  ]
  $ h(chi_1) dot h(chi_2)=h(chi_1 chi_2). $ <eq:diagonal-subgroup-h-product>
  Also the map $chi arrow.r h(chi)$ is an isomorphism from the group of
  $K$-characters of $P$ onto the group $hat(H)$.

  Now, as $H$ is the subgroup of $G$ generated by the automorphisms
  $h_r (lambda)$ for all $r in Phi$, $lambda in K^*$, $H$ is a subgroup of
  $hat(H)$. Each element of $H$ therefore has the form $h(chi)$ for some
  $K$-character $chi$. We shall now consider which $K$-characters $chi$ give
  rise to automorphisms $h(chi)$ which are in $H$.

  #block(sticky: true)[
    Let $q_1,q_2,dots,q_l$ be the basis of $frak(H)_RR$ dual to the basis
    $h_(p_1),h_(p_2),dots,h_(p_l)$ of fundamental co-roots. Thus $q_1,dots,q_l$
    are defined by
  ]
  $
    (h_(p_i),q_j)=cases(1 & quad "if" i=j, 0 & quad "if" i!=j).
  $ <eq:diagonal-subgroup-dual-basis>
  #block(sticky: true)[
    The non-singularity of the Killing form shows that $q_1,dots,q_l$ form a
    basis for $frak(H)$. #ix("fundamental weights")They are called the
    _fundamental weights_ of #L. In particular, each fundamental root $p_i$ is a
    linear combination of $q_1,dots,q_l$. Let
  ]
  $
    p_i=mu_(i 1)q_1+dots+mu_(i l)q_l.
  $ <eq:diagonal-subgroup-root-weight-expansion>
  #block(sticky: true)[Then $(h_(p_j),p_i)=mu_(i j)$. Thus we have]
  $ mu_(i j)=2 frac((p_j,p_i), (p_j,p_j))=A_(p_j p_i)=A_(j i) $
  <eq:diagonal-subgroup-cartan-coefficients>
  #block(sticky: true)[
    in the notation of @th:simple-lie-algebra-isomorphism. Thus
  ]
  $ p_i=sum_(j=1)^l A_(j i)q_j $ <eq:diagonal-subgroup-root-weight-integral>
  and $p_i$ is actually an integral combination of $q_1,dots,q_l$.

  #source(112, "99")
  #block(sticky: true)[
    Let $Q$ be the set of linear combinations of $q_1,dots,q_l$ with rational
    #nx("Q", [$Q$], group: "latin-q", after: "q-1-dots-q-l")[The additive group
      generated by $q_1,dots,q_l$]integer coefficients. $Q$ is #ix(
      "fundamental group",
    )the additive group generated by the fundamental weights and is free abelian
    of rank $l$. Since each $p_i$ is in $Q$, $P$ is a subgroup of $Q$. The index
    $|Q:P|$ of $P$ in $Q$ is finite. In fact, since
  ]
  $ p_i=sum_(j=1)^l A_(j i)q_j, $ <eq:diagonal-subgroup-index-basis>
  #block(sticky: true)[
    we have $|Q:P|=det(A_(j i))$. We shall write $|Q:P|=Delta$. The values of
    $Delta$ for the different types of algebra may be calculated from the Cartan
    matrices shown in @sec:description-of-simple-lie-algebras[section], and are
    as follows.
  ]
  #align(center, table(
    columns: 10,
    align: center,
    inset: (x: 0.35em, y: 0.3em),
    stroke: none,
    table.hline(stroke: 0.5pt),
    table.header(
      [$frak(L)$],
      [$A_l$],
      [$B_l$],
      [$C_l$],
      [$D_l$],
      [$G_2$],
      [$F_4$],
      [$E_6$],
      [$E_7$],
      [$E_8$],
    ),
    table.hline(stroke: 0.3pt),
    [$Delta$], [$l+1$], [2], [2], [4], [1], [1], [3], [2], [1],
    table.hline(stroke: 0.5pt),
  )) <eq:diagonal-subgroup-index-table>
  ($Delta$ is equal to the order of the fundamental group of the Lie group of
  the given type. #ix("$K$-character")See Adams#bib-ref("adams1969").)

  Now every $K$-character of $Q$ gives rise to a $K$-character of $P$ by
  restriction. However, not every $K$-character of $P$ need be the restriction
  of some $K$-character of $Q$.

  We can now describe which $K$-characters of $P$ give rise to elements of $H$.

  #theorem()[
    $H$ is the subgroup of $G$ consisting of all automorphisms $h(chi)$ of
    $frak(L)_K$ for which $chi$ is a $K$-character of $P$ which can be extended
    to a $K$-character of $Q$.
  ] <th:diagonal-subgroup-characters>

  #proof[
    #block(sticky: true)[
      $H$ is generated by the elements $h(chi_(r,lambda))$ for all $r in Phi$,
      $lambda in K^*$. Now $chi_(r,lambda)$ can be extended to the $K$-character
      of $Q$ given by
    ]
    $ chi_(r,lambda)(a)=lambda^(2(r,a)\/(r,r)), quad a in Q. $
    <eq:diagonal-subgroup-characters-extended-character>
    (Note that $2(r,a)\/(r,r) in ZZ$ since $2r\/(r,r)$ is a co-root and
    $a in Q$.) Thus each element of $H$ has the form $h(chi)$, where $chi$ is a
    $K$-character of $Q$.
    #block(sticky: true)[Conversely, let $chi$ be any $K$-character of $Q$. Let]
    $ chi(q_1)=lambda_1, chi(q_2)=lambda_2,dots,chi(q_l)=lambda_l. $
    <eq:diagonal-subgroup-characters-character-values>
    #block(sticky: true)[
      Now $chi_(p_i,lambda_i)$ takes value $lambda_i$ at $q_i$ and value $1$ at
      $q_j$ for all $j!=i$. For
    ]
    $
      chi_(p_i,lambda_i)(q_j)=lambda_i^(2(p_i,q_j)\/(p_i,p_i))
      =lambda_i^(delta_(j i)).
    $ <eq:diagonal-subgroup-characters-coordinate-character>
    #block(sticky: true)[Thus we have]
    $ chi=chi_(p_1,lambda_1)chi_(p_2,lambda_2) dots chi_(p_l,lambda_l) $
    <eq:diagonal-subgroup-characters-character-decomposition>

    #source(113, "100")
    #block(sticky: true)[and so]
    $
      h(chi)=h(chi_(p_1,lambda_1))h(chi_(p_2,lambda_2)) dots
      h(chi_(p_l,lambda_l)).
    $ <eq:diagonal-subgroup-characters-h-decomposition>
    Therefore $h(chi) in H$ and the theorem is proved.
  ]

  #block(sticky: true)[
    We now consider the relation between $H$ and the subgroups $U$ and $V$ of
    $G$. Note first that $H$ normalizes each root subgroup $X_r$. For
  ]
  $
    h(chi)x_r (t)h(chi)^(-1) & =h(chi)exp ad(t e_r)h(chi)^(-1) \
                             & =exp ad(h(chi) dot t e_r) \
                             & =exp ad(chi(r)t e_r)
  $ <eq:diagonal-subgroup-exponential-conjugation>
  #block(sticky: true)[by @l:exponential-equivariance. Thus]
  $
    h(chi)x_r (t)h(chi)^(-1)=x_r (chi(r)t),
  $ <eq:diagonal-subgroup-root-conjugation>
  #block(sticky: true)[whence]
  $ h(chi)X_r h(chi)^(-1)=X_r. $ <eq:diagonal-subgroup-root-normalization>
  It follows that $H$ normalizes $U$ and $V$, which are generated by root
  subgroups. In particular, $U H$ and $V H$ are both subgroups of $G$.

  _Note._ The same argument shows that the group $hat(H)$ also normalizes $U$
  and $V$. Although $hat(H)$ is a group of automorphisms of $frak(L)_K$, we have
  not shown that $hat(H)$ is contained in $G$, and in fact this is not in
  general so. However it is evident now that $hat(H)$ normalizes $G$ in the
  group of all automorphisms of $frak(L)_K$, since $G$ is generated by $U$ and
  $V$.

  #lemma()[
    $U H ∩ V=1$.
  ] <l:opposite-unipotent-intersection>

  #proof[
    #block(sticky: true)[
      Let $theta in U H ∩ V$ and consider the effect of $theta$ on the Chevalley
      basis of $frak(L)_K$. Since $theta in V$ we have
    ]
    $ theta dot h_s=h_s+x, quad "where" x in sum_(r in Phi^-) frak(L)_r. $
    <eq:opposite-unipotent-intersection-cartan-negative>
    #block(sticky: true)[Since $theta in U H$ we have]
    $
      x in frak(H) ⊕ sum_(r in Phi^+) frak(L)_r.
    $ <eq:opposite-unipotent-intersection-cartan-positive>
    #block(sticky: true)[However]
    $
      frak(L)=frak(H) ⊕ sum_(r in Phi^+) frak(L)_r
      ⊕ sum_(r in Phi^-) frak(L)_r
    $ <eq:opposite-unipotent-intersection-cartan-decomposition>
    and so $x=0$. Thus $theta dot h_s=h_s$.

    #source(114, "101")
    #block(sticky: true)[
      Now let $theta dot e_s=e_s+y$. Suppose $s in Phi^+$. Then
    ]
    $
      y in frak(H) ⊕ sum_(r prec s) frak(L)_r
    $ <eq:opposite-unipotent-intersection-root-negative>
    #block(sticky: true)[since $theta in V$. Also]
    $
      y in sum_(r succ.eq s) frak(L)_r
    $ <eq:opposite-unipotent-intersection-root-positive>
    #block(sticky: true)[since $theta in U H$. But we have]
    $
      frak(L)=frak(H) ⊕ sum_(r prec s) frak(L)_r
      ⊕ sum_(r succ.eq s) frak(L)_r,
    $ <eq:opposite-unipotent-intersection-root-decomposition>
    hence $y=0$. Thus $theta dot e_s=e_s$. A similar argument applies if
    $s in Phi^-$ and so $theta=1$.
  ]

  _Note._ A similar argument shows that $V H ∩ U=1$. In particular we have
  $H ∩ V=1$ and $H ∩ U=1$. These results clearly apply also when $H$ is replaced
  by $hat(H)$.

  #block(breakable: false)[
    #corollary()[
      $U H ∩ V H=H$.
    ] <cor:opposite-borel-intersection>

    #proof[
      $U H ∩ V H=(U H ∩ V)H=H$.
    ]

  ]
]

#[
  #import "main-defs.typ": L, ix, nx, source
  #let ad = math.op("ad")

  == Properties of the Subgroup $N$ <sec:monomial-subgroup>

  #nx(
    "N-monomial",
    [$N$],
    group: "latin-n",
    after: "N-positive-roots",
    definition: [@sec:monomial-subgroup],
  )[The monomial subgroup of a Chevalley group $G$]#ix(
    "monomial subgroup $N$, of Chevalley group",
  )Let $N$ be the subgroup of $G$ generated by $H$ and the elements $n_r$ for
  all $r in Phi$. In investigating the properties of $N$ we begin with a lemma
  describing the way in which the elements $n_r$ transform the root subgroups.

  #lemma()[
    #block(breakable: false)[
      Let $r,s in Phi$. Then
      #enum(
        numbering: "(i)",
        indent: 1.1em,
        body-indent: 0.5em,
        [
          #metadata((
            kind: "anchor",
          )) <eq:monomial-conjugation-root-subgroups-i>
          $n_r dot x_s (t) dot n_r^(-1)=x_(w_r (s))(eta_(r,s)t)$,
        ],
        [
          #metadata((
            kind: "anchor",
          )) <eq:monomial-conjugation-root-subgroups-ii>
          $n_r X_s n_r^(-1)=X_(w_r (s))$.
        ],
      )
    ]
  ] <l:monomial-conjugation-root-subgroups>

  #proof[
    #block(sticky: true)[]
    $
      n_r x_s (t)n_r^(-1) & =n_r exp ad(t e_s)n_r^(-1) \
                          & =exp ad(n_r dot t e_s) \
                          & =exp ad(eta_(r,s)t e_(w_r (s))) \
                          & =x_(w_r (s))(eta_(r,s)t),
    $ <eq:monomial-conjugation-root-subgroups-conjugation-proof>
    using @l:exponential-equivariance and @p:monomial-action-on-chevalley-basis.
  ]

  The most important property of the subgroup $N$ is the one we shall now prove.

  #source(115, "102")
  #ix("Weyl group, of a root system", sub: "of a Chevalley group")#ix(
    "monomial subgroup $N$, of Chevalley group",
    sub: "relationship to Weyl group",
  )#theorem()[
    #block(breakable: false)[
      There is a homomorphism from $N$ onto $W$ with kernel $H$ under which
      $n_r arrow.r w_r$ for all $r in Phi$. Thus $H$ is a normal subgroup of $N$
      and $N\/H$ is isomorphic to $W$. If $n in N$, $h(chi) in H$, we have
      $ n h(chi)n^(-1)=h(chi'), $ <eq:monomial-quotient-weyl-group-statement>
      where $chi'(r)=chi(w^(-1)(r))$, $w$ being the image of $n$ under the above
      homomorphism.
    ]
  ] <th:monomial-quotient-weyl-group>

  #proof[
    #block(sticky: true)[
      By @p:monomial-action-on-chevalley-basis $n_r$ operates on the Chevalley
      basis of $frak(L)_K$ by
    ]
    $ n_r dot h_s=h_(w_r (s)), quad n_r dot e_s=eta_(r,s)e_(w_r (s)). $
    <eq:monomial-quotient-weyl-group-generator-action>
    Thus $n_r$ transforms the root space $frak(L)_s$ into $frak(L)_(w_r (s))$,
    and so $n_r$ permutes the root spaces in the same way that the element $w_r$
    of $W$ permutes the roots. Furthermore, each element of $H$ transforms each
    root space into itself. Thus there is a homomorphism of $N$ onto $W$ which
    maps $n_r$ into $w_r$ and which contains $H$ in its kernel.

    #block(sticky: true)[
      We show next that $H$ is a normal subgroup of $N$. Let $n in N$ and
      $h(chi) in H$. Then we have
    ]
    $
      n h(chi)n^(-1) dot h_s & =n h(chi) dot (n^(-1)h_s)=n dot
                               (n^(-1)h_s)=h_s, \
      n h(chi)n^(-1) dot e_s & =n h(chi) dot (eta e_(w^(-1)(s))),
    $ <eq:monomial-quotient-weyl-group-conjugated-action>
    // E030: a general n in N may contain torus factors, so eta is not just
    // ±1.
    #block(sticky: true)[
      where $w$ is the image of $n$ under the above homomorphism and
      $eta in K^*$. Thus
    ]
    $
      n h(chi)n^(-1) dot e_s & =eta chi(w^(-1)(s))n dot e_(w^(-1)(s)) \
                             & =eta chi(w^(-1)(s))eta^(-1)e_s \
                             & =chi'(s)e_s,
    $ <eq:monomial-quotient-weyl-group-character-action>
    #block(sticky: true)[
      where $chi'(s)=chi(w^(-1)(s))$. Hence we have
    ]
    $
      n h(chi)n^(-1)=h(chi')
    $ <eq:monomial-quotient-weyl-group-h-normalization>
    and so $H$ is normal in $N$.

    #block(sticky: true)[
      We thus have a homomorphism from $N\/H$ onto $W$ under which $n_r H$ is
      mapped to $w_r$. We show this is an isomorphism. Let $r,s in Phi$. Then
    ]
    $
      n_r n_s n_r^(-1) & =n_r x_s (1)x_(-s)(-1)x_s (1)n_r^(-1),
                         quad "by" #[@l:rank-one-element-identities], \
                       & =x_(w_r (s))(eta_(r,s))x_(w_r (-s))(-eta_(r,-s))
                         x_(w_r (s))(eta_(r,s)), \
                       & quad "by"
                         #[@l:monomial-conjugation-root-subgroups], \
                       & =x_(w_r (s))(eta_(r,s))x_(-w_r (s))(-eta_(r,s)^(-1))
                         x_(w_r (s))(eta_(r,s)), \
                       & quad "by" #[@p:monomial-sign-relations], \
                       & =n_(w_r (s))(eta_(r,s)) \
                       & =h_(w_r (s))(eta_(r,s))n_(w_r (s)),
                         quad "by" #[@l:rank-one-element-identities].
    $ <eq:monomial-quotient-weyl-group-representative-conjugation>

    #source(116, "103")
    #block(sticky: true)[Since $h_(w_r (s))(eta_(r,s)) in H$ we have]
    $ n_r H dot n_s H dot (n_r H)^(-1)=n_(w_r (s))H. $
    <eq:monomial-quotient-weyl-group-coset-conjugation>
    // E031: restore the omitted root subscript in h_r(-1).
    #block(sticky: true)[Since $n_r^2=h_r (-1) in H$ we also have]
    $ (n_r H)^2=H. $ <eq:monomial-quotient-weyl-group-coset-involution>
    Now $W$ is defined as an abstract group by generators $w_r$, $r in Phi$,
    subject to relations $w_r^2=1$, $w_r w_s w_r^(-1)=w_(w_r (s))$
    (@th:all-reflections-presentation). Hence there is a homomorphism from $W$
    onto $N\/H$ under which $w_r$ is mapped to $n_r H$. Since this is the
    inverse map of the one obtained above, it is an isomorphism. Thus $N\/H$ is
    isomorphic to $W$.
  ]

  #corollary()[
    $N ∩ hat(H)=H$.
  ] <cor:monomial-diagonal-intersection>

  #proof[
    Let $n in N ∩ hat(H)$. Since $n in hat(H)$ we have
    $n dot frak(L)_s=frak(L)_s$ for each $s in Phi$. Thus $n$ is in the kernel
    of the homomorphism mapping $N$ to $W$, and so $n in H$.
  ]

  #corollary()[
    (i) $U ∩ N=1$, (ii) $U H ∩ N=H$.
  ] <cor:monomial-borel-intersections>

  #proof[
    #block(sticky: true)[ Let $theta in U ∩ N$. Then we have]
    $
      theta dot e_s=lambda e_(w(s)),
    $ <eq:monomial-borel-intersections-monomial-action>
    #block(sticky: true)[
      where $lambda in K^*$ and $w in W$ is the image of $theta$ under the
      homomorphism from $N$ to $W$. However
    ]
    $
      theta dot e_s=e_s+x,
    $ <eq:monomial-borel-intersections-unipotent-action>
    #block(sticky: true)[where]
    $
      x in frak(H) ⊕ sum_(r succ s) frak(L)_r,
    $ <eq:monomial-borel-intersections-positive-remainder>
    since $theta in U$. It follows that $x=0$, $lambda=1$ and $w(s)=s$. This is
    valid for all $s in Phi$, and so $w=1$. This means that $theta in H$. But
    $U ∩ H=1$ and therefore $theta=1$. Hence $U ∩ N=1$.
    #block(sticky: true)[Finally we have]
    $ U H ∩ N=(U ∩ N)H=H. $ <eq:monomial-borel-intersections-intersection>
  ]

  _Note._ A similar argument shows that $U hat(H) ∩ N=H$.
]
