#let chapter = [
  #[
    #import "main-defs.typ": book-ref, mathclap, qed, source

    #show heading.where(level: 1): set text(hyphenate: false)
    #show heading.where(level: 1): set par(justify: false)

    // Short names keep long conjugation calculations readable in the source.
    #let xbar = $overline(x)$
    #let nbar = $overline(n)$
    #let hbar = $overline(h)$
    #let Gbar = $overline(G)$
    #let Hbar = $overline(H)$
    #let Ubar = $overline(U)$
    #let Nbar = $overline(N)$
    #let Bbar = $overline(B)$
    #let Xbar = $overline(X)$
    #let Zbar = $overline(Z)$
    #let ubar = $overline(u)$
    #let bbar = $overline(b)$
    #let gbar = $overline(g)$

    #source(202, "189")
    #heading(level: 1)[
      Generators, Relations and Automorphisms in Chevalley Groups
    ] <ch:generators-relations-and-automorphisms>

    == A Theorem of Steinberg <sec:steinberg-presentation>

    The Chevalley group $G=frak(L)(K)$ is generated by a set of elements
    $x_r (t)$ for all $r in Phi$, $t in K$. We consider the problem of finding
    relations involving these generators which are sufficient to define $G$ as
    an abstract group. Such a system of relations has been discovered by
    Steinberg.

    Let $h_r (t),n_r (t)$ be the elements of $G$ defined as in chapter
    #book-ref(
      "ch",
      "root-sl2-subgroups",
    ) by
    $
      h_r (t)=phi_r mat(t, 0; 0, t^(-1)), quad
      n_r (t)=phi_r mat(0, t; -t^(-1), 0).
    $ <eq:12-1-matrices>
    #block(sticky: true)[By #book-ref("l", "6-4-4", [6.4.4]) we have]
    $
      n_r (t)=x_r (t)x_(-r)(-t^(-1))x_r (t), quad
      h_r (t)=n_r (t)n_r (-1)
    $ <eq:12-1-words>
    and these equations show how to express $n_r (t)$ and $h_r (t)$ in terms of
    the generators of $G$.

    Now the following relations have been shown to hold in $G$:
    $
      x_r (t_1)x_r (t_2) & =x_r (t_1+t_2), \
       [x_s (u),x_r (t)] & =product_(mathclap(i","j>0))
                           x_(i r+j s)(C_(i j r s)(-t)^i u^j), \
      h_r (t_1)h_r (t_2) & =h_r (t_1 t_2), quad t_1 t_2!=0,
    $ <eq:12-1-relations>
    where $C_(i j r s)$ are integers defined as in #book-ref(
      "th",
      "5-2-2",
      [5.2.2],
    ) for linearly independent roots $r,s$. Steinberg’s theorem shows that these
    relations are almost sufficient to define $G$ abstractly, the only
    additional relations required being ones to ensure that the group so defined
    has a trivial centre.

    #source(203, "190")
    #block(sticky: true)[
      #metadata((kind: "anchor")) <th:12-1-1>
      #smallcaps[Theorem 12.1.1.] _Let $frak(L)$ be a simple Lie algebra with
      $frak(L)!=A_1$ and let $K$ be a field. For each root $r$ of $frak(L)$ and
      each element $t$ of $K$ introduce a symbol $xbar_r (t)$. Let $Gbar$ be the
      abstract group generated by the elements $xbar_r (t)$ subject to
      relations_
    ]
    $
      xbar_r (t_1)xbar_r (t_2) & =xbar_r (t_1+t_2), \
       [xbar_s (u),xbar_r (t)] & =product_(mathclap(i","j>0))
                                 xbar_(i r+j s)(C_(i j r s)(-t)^i u^j), \
      hbar_r (t_1)hbar_r (t_2) & =hbar_r (t_1 t_2), quad t_1 t_2!=0,
    $ <eq:12-1-1-relations>
    #block(sticky: true)[_where_]
    $ hbar_r (t)=nbar_r (t)nbar_r (-1) $ <eq:12-1-1-h-definition>
    #block(sticky: true)[_and_]
    $ nbar_r (t)=xbar_r (t)xbar_(-r)(-t^(-1))xbar_r (t). $
    <eq:12-1-1-n-definition>
    _Let $Zbar$ be the centre of $Gbar$. Then $Gbar slash Zbar$ is isomorphic to
    the Chevalley group $G=frak(L)(K)$._

    #metadata((kind: "anchor")) <th:12-1-1-a>
    #smallcaps[Proof.] (a) There is a homomorphism $theta$ of $Gbar$ onto $G$
    such that
    $ theta(xbar_r (t))=x_r (t). $ <eq:12-1-1-homomorphism>
    We must show that the kernel of $theta$ is $Zbar$.

    As usual, let $Phi$ be the set of roots of $frak(L)$ and $Phi^+$ be a
    positive system in $Phi$. Let $Ubar$ be the subgroup of $Gbar$ generated by
    the elements $xbar_r (t)$ for $r in Phi^+$. Then the commutator relation
    shows that each element of $Ubar$ can be expressed in the form
    $ xbar_(r_1)(t_1)xbar_(r_2)(t_2)dots xbar_(r_N)(t_N), $
    <eq:12-1-1-unipotent-word>
    where $r_1,dots,r_N$ is the set of positive roots. Thus
    $
      theta(xbar_(r_1)(t_1)dots xbar_(r_N)(t_N))
      =x_(r_1)(t_1)dots x_(r_N)(t_N).
    $ <eq:12-1-1-unipotent-image>
    However, by #book-ref("th", "5-3-3", [5.3.3]) each element of $U$ is
    uniquely expressible in the form $x_(r_1)(t_1)dots x_(r_N)(t_N)$. Thus the
    map $theta:Ubar->U$ is an isomorphism.

    #metadata((kind: "anchor")) <th:12-1-1-b>
    #block(sticky: true)[(b) We now consider the expression]
    $ n_r (t)x_s (u)n_r (t)^(-1) $ <eq:12-1-1-conjugation-g>
    in $G$. Since $n_r (t)=h_r (t)n_r$ we have
    $
      n_r (t)x_s (u)n_r (t)^(-1) & =h_r (t)n_r x_s (u)n_r^(-1)h_r (t)^(-1) \
                                 & =h_r (t)x_(w_r (s))(eta_(r,s)u)h_r (t)^(-1),
                                   quad "by" #book-ref("l", "7-2-1", [7.2.1]), \
                                 & =x_(w_r (s))(eta_(r,s)t^(A_(r rho))u), \
                                 & quad "where" rho=w_r (s), quad "by section"
                                   #book-ref("sec", "diagonal-subgroup"), \
                                 & =x_(w_r (s))(eta_(r,s)t^(-A_(r s))u).
    $ <eq:12-1-1-conjugation-calculation>

    #source(204, "191")
    #block(sticky: true)[
      We shall show that the corresponding relation
    ]
    $
      nbar_r (t)xbar_s (u)nbar_r (t)^(-1)
      =xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
    $ <eq:12-1-1-conjugation-lift>
    holds in $Gbar$. Suppose $r,s$ are linearly independent. Then
    $
      & nbar_r (t)xbar_s (u)nbar_r (t)^(-1) \
      & quad =xbar_r (t)xbar_(-r)(-t^(-1))xbar_r (t)xbar_s (u) \
      & quad #hide[$=$] dot xbar_r (t)^(-1)xbar_(-r)(-t^(-1))^(-1)
        xbar_r (t)^(-1).
    $ <eq:12-1-1-expanded-conjugation>
    The commutator relation shows that this can be expressed as a product of
    terms of the form $xbar_(i r+j s)(v)$, where $j>0$. Now there is a positive
    system $Phi^+$ in $Phi$ containing all roots of form $i r+j s$, where $i,j$
    are integers and $j>0$. With respect to such a positive system we have
    $
         nbar_r (t)xbar_s (u)nbar_r (t)^(-1) & in Ubar, \
      xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u) & in Ubar.
    $ <eq:12-1-1-two-unipotent-elements>
    But $theta$ is an isomorphism from $Ubar$ onto $U$ and we have
    $
      theta(nbar_r (t)xbar_s (u)nbar_r (t)^(-1))
      =theta(xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)).
    $ <eq:12-1-1-equal-images>
    #block(sticky: true)[Hence]
    $
      nbar_r (t)xbar_s (u)nbar_r (t)^(-1)
      =xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
    $ <eq:12-1-1-independent-roots>
    as required.

    If $r,s$ are not linearly independent we argue differently. Suppose $r=s$.
    Since $Phi$ is a simple root system of rank greater than $1$ (we have
    assumed $frak(L)!=A_1$), there exists $r_1 in Phi$, $r_1!=r$ such that
    $(r,r_1)>0$. Then $r$ does not begin the $r_1$-chain of roots through it.
    Let $r_2$ begin the $r_1$-chain of roots through $r$. Then $r=i r_1+r_2$ for
    some $i>0$. Also
    $ C_(i 1 r_1 r_2)=M_(r_1 r_2 i)=plus.minus 1 $ <eq:12-1-1-unit-constant>
    by #book-ref("th", "5-2-2", [5.2.2]). Now the commutator relation shows that
    $
      [xbar_(r_2)(t_2),xbar_(r_1)(t_1)]
      =product_(mathclap(i","j>0))
      xbar_(i r_1+j r_2)(C_(i j r_1 r_2)(-t_1)^i t_2^j).
    $ <eq:12-1-1-auxiliary-commutator>
    #block(sticky: true)[
      We now transform each term in this relation by $nbar_r (t)$. Let $Phi^+$
      be a positive system in $Phi$ containing all roots of form
    ]
    $ i w_r (r_1)+j w_r (r_2), quad i>=0,j>=0. $ <eq:12-1-1-transformed-cone>
    #block(sticky: true)[Since]
    $
      nbar_r (t)xbar_s (u)nbar_r (t)^(-1)
      =xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
    $ <eq:12-1-1-known-transforms>
    whenever $s!=plus.minus r$, it is evident that all the transformed terms lie
    in $Ubar$ with the possible exception of
    $
      nbar_r (t)xbar_r (C_(i 1 r_1 r_2)(-t_1)^i t_2)nbar_r (t)^(-1).
    $ <eq:12-1-1-exceptional-transform>

    #source(205, "192")
    Hence this term lies in $Ubar$ also. Since $C_(i 1 r_1 r_2)!=0$ it follows
    that
    $ nbar_r (t)xbar_r (u)nbar_r (t)^(-1) in Ubar $ <eq:12-1-1-equal-root-in-u>
    for all $u in K$. Also we have
    $ xbar_(w_r (r))(eta_(r,r)t^(-A_(r r))u) in Ubar. $
    <eq:12-1-1-equal-root-target>
    #block(sticky: true)[But]
    $
      theta(nbar_r (t)xbar_r (u)nbar_r (t)^(-1))
      =theta(xbar_(w_r (r))(eta_(r,r)t^(-A_(r r))u))
    $ <eq:12-1-1-equal-root-images>
    and $theta:Ubar->U$ is an isomorphism. Thus
    $ nbar_r (t)xbar_r (u)nbar_r (t)^(-1)=xbar_(-r)(-t^(-2)u), $
    <eq:12-1-1-equal-root>
    since $eta_(r,r)=-1$, $A_(r r)=2$.

    Finally suppose $s=-r$. Then, from the above formula we have
    $ nbar_r (t)^(-1)xbar_(-r)(u)nbar_r (t)=xbar_r (-t^2 u). $
    <eq:12-1-1-opposite-inverse>
    #block(sticky: true)[But]
    $ nbar_r (t)^(-1)=nbar_r (-t) $ <eq:12-1-1-n-inverse>
    #block(sticky: true)[and so]
    $ nbar_r (t)xbar_(-r)(u)nbar_r (t)^(-1)=xbar_r (-t^2 u). $
    <eq:12-1-1-opposite-root>
    #block(sticky: true)[Thus]
    $
      nbar_r (t)xbar_(-r)(u)nbar_r (t)^(-1)
      =xbar_(w_r (-r))(eta_(r,-r)t^(-A_(r,-r))u),
    $ <eq:12-1-1-opposite-uniform>
    #block(sticky: true)[
      as required, since $eta_(r,-r)=-1$, $A_(r,-r)=-2$. The relation
    ]
    $
      nbar_r (t)xbar_s (u)nbar_r (t)^(-1)
      =xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
    $ <eq:12-1-1-all-roots>
    is therefore valid in $Gbar$ in all cases.

    #metadata((kind: "anchor")) <th:12-1-1-c>
    (c) We now derive some consequences of the relation proved in #book-ref(
      "th",
      "12-1-1-b",
      [(b)],
    ). Let $r,s in Phi$ and $t,u$ be non-zero elements of $K$. Then
    $
      & nbar_r (t)nbar_s (u)nbar_r (t)^(-1) \
      & quad =nbar_r (t)xbar_s (u)xbar_(-s)(-u^(-1))xbar_s (u)nbar_r (t)^(-1) \
      & quad =xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u) \
      & quad #hide[$=$] dot xbar_(w_r (-s))(-eta_(r,-s)t^(-A_(r,-s))u^(-1))
        xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u) \
      & quad =xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u) \
      & quad #hide[$=$] dot xbar_(-w_r (s))(-eta_(r,s)^(-1)t^(A_(r s))u^(-1))
        xbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u) \
      & quad =nbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
    $ <eq:12-1-1-n-conjugation-calculation>
    by #book-ref("p", "6-4-3", [6.4.3]). Thus
    $
      nbar_r (t)nbar_s (u)nbar_r (t)^(-1)
      =nbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u).
    $ <eq:12-1-1-n-conjugation>
    #block(sticky: true)[Now consider the expression]
    $
      nbar_r (t)hbar_s (u)nbar_r (t)^(-1).
    $ <eq:12-1-1-h-conjugation-expression>

    #source(206, "193")
    Using the relation just proved we have
    $
      nbar_r (t)hbar_s (u)nbar_r (t)^(-1)
      & =nbar_r (t)nbar_s (u)nbar_s (-1)nbar_r (t)^(-1) \
      & =nbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
      nbar_(w_r (s))(-eta_(r,s)t^(-A_(r s))) \
      & =hbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)nbar_(w_r (s))(1) \
      & quad dot nbar_(w_r (s))(1)^(-1)
      hbar_(w_r (s))(eta_(r,s)^(-1)t^(A_(r s))) \
      & =hbar_(w_r (s))(eta_(r,s)t^(-A_(r s))u)
      hbar_(w_r (s))(eta_(r,s)^(-1)t^(A_(r s))) \
      & =hbar_(w_r (s))(u).
    $ <eq:12-1-1-h-conjugation-calculation>
    #block(sticky: true)[Hence]
    $ nbar_r (t)hbar_s (u)nbar_r (t)^(-1)=hbar_(w_r (s))(u). $
    <eq:12-1-1-h-conjugation>

    #metadata((kind: "anchor")) <th:12-1-1-d>
    (d) Let $nbar_r=nbar_r (1)$ for each $r in Phi$. Let $Hbar$ be the subgroup
    of $Gbar$ generated by the elements $hbar_r (t)$ for all $r in Phi$,
    $t!=0 in K$, and $Nbar$ be the subgroup generated by $Hbar$ and $nbar_r$ for
    all $r in Phi$. Since $nbar_r (t)=hbar_r (t)nbar_r$ it is clear that
    $nbar_r (t) in Nbar$ for all $t!=0$. Since
    $ nbar_r hbar_s (u)nbar_r^(-1)=hbar_(w_r (s))(u) $
    <eq:12-1-1-h-normal>
    it is evident that $Hbar$ is a normal subgroup of $Nbar$.

    Now $theta(Nbar)=N$ and $theta(Hbar)=H$. Thus $theta$ induces a homomorphism
    from $Nbar slash Hbar$ onto $N slash H$, which is isomorphic to $W$ by
    #book-ref("th", "7-2-2", [7.2.2]). This homomorphism maps $nbar_r Hbar$ to
    $w_r$. However it follows from relations proved in #book-ref(
      "th",
      "12-1-1-c",
      [(c)],
    ) that
    $
      nbar_r nbar_s nbar_r^(-1)
      =nbar_(w_r (s))(eta_(r,s))=hbar_(w_r (s))(eta_(r,s))nbar_(w_r (s)).
    $ <eq:12-1-1-n-lift-relations>
    #block(sticky: true)[This implies that]
    $ nbar_r Hbar dot nbar_s Hbar dot (nbar_r Hbar)^(-1)=nbar_(w_r (s))Hbar. $
    <eq:12-1-1-coset-conjugation>
    #block(sticky: true)[Also]
    $ nbar_r^(-1)=nbar_r (-1)=hbar_r (-1)nbar_r $ <eq:12-1-1-n-unit-inverse>
    #block(sticky: true)[and so]
    $ nbar_r^2=hbar_r (-1) $ <eq:12-1-1-n-square>
    #block(sticky: true)[and]
    $ (nbar_r Hbar)^2=Hbar. $ <eq:12-1-1-coset-square>

    Now the Weyl group $W$ is defined as an abstract group by generators $w_r$,
    $r in Phi$, subject to relations
    $ w_r^2=1, quad w_r w_s w_r^(-1)=w_(w_r (s)), $
    <eq:12-1-1-weyl-relations>
    by #book-ref("th", "2-4-3", [2.4.3]). Also we have a homomorphism from
    $Nbar slash Hbar$ onto $W$ mapping $nbar_r Hbar$ to $w_r$, where
    $
      (nbar_r Hbar)^2=Hbar, quad
      nbar_r Hbar dot nbar_s Hbar dot (nbar_r Hbar)^(-1)=nbar_(w_r (s))Hbar.
    $ <eq:12-1-1-coset-relations>
    #source(207, "194")
    It follows that this homomorphism is an isomorphism, and so
    $Nbar slash Hbar$ is isomorphic to $W$.

    #metadata((kind: "anchor")) <th:12-1-1-e>
    #block(sticky: true)[
      (e) Let $Bbar$ be the subgroup of $Gbar$ generated by $Ubar$ and $Hbar$.
      We show $Hbar$ is in the normalizer of $Ubar$, so that $Bbar=Ubar Hbar$.
      Now
    ]
    $
      hbar_r (t)xbar_s (u)hbar_r (t)^(-1)
      & =nbar_r (t)nbar_r (-1)xbar_s (u)nbar_r (-1)^(-1)nbar_r (t)^(-1) \
      & =nbar_r (t)xbar_(w_r (s))(eta_(r,s)(-1)^(A_(r s))u)nbar_r (t)^(-1) \
      & =xbar_s (eta_(r,s)eta_(r,w_r (s))t^(-A_(r rho))(-1)^(A_(r s))u), \
      & quad "where" rho=w_r (s), \
      & =xbar_s (t^(A_(r s))u),
    $ <eq:12-1-1-torus-action-calculation>
    since $eta_(r,s)eta_(r,w_r (s))=(-1)^(A_(r s))$ by #book-ref(
      "p",
      "6-4-3",
      [6.4.3],
    ) and $A_(r,w_r (s))=-A_(r s)$. Thus
    $ hbar_r (t)xbar_s (u)hbar_r (t)^(-1)=xbar_s (t^(A_(r s))u) $
    <eq:12-1-1-torus-action>
    for all $s in Phi$, and so $Hbar$ is in the normalizer of $Ubar$.

    Let $Xbar_r$ be the subgroup of $Gbar$ generated by $xbar_r (t)$ for all
    $t in K$. Let $Pi$ be the fundamental system contained in $Phi^+$. For each
    root $r in Pi$ let $Ubar_r$ be the subgroup of $Ubar$ generated by $Xbar_s$
    for all $s in Phi^+$ with $s!=r$. The commutator relations show that
    $ Ubar_r=product_(mathclap(s in Phi^+","s!=r)) Xbar_s, $
    <eq:12-1-1-unipotent-without-r>
    where the product can be taken in any order. Moreover, $Xbar_r$ and
    $Xbar_(-r)$ normalize $Ubar_r$ as in #book-ref("l", "8-1-1", [8.1.1]). Thus
    $nbar_r$ normalizes $Ubar_r$ also.

    #metadata((kind: "anchor")) <th:12-1-1-f>
    (f) We now show that $Bbar union Bbar nbar_r Bbar$ is a subgroup of $Gbar$
    for all $r in Pi$. As in #book-ref("p", "8-1-4", [8.1.4]) it is sufficient
    to show that
    $ nbar_r Bbar nbar_r subset.eq Bbar union Bbar nbar_r Bbar. $
    <eq:12-1-1-minimal-parabolic-condition>
    #block(sticky: true)[Now we have]
    $
      nbar_r Bbar nbar_r & =nbar_r Bbar nbar_r^(-1)=nbar_r Ubar Hbar
                           nbar_r^(-1) \
                         & =nbar_r Xbar_r Ubar_r Hbar nbar_r^(-1)
                           =Xbar_(-r)Ubar_r Hbar subset.eq Xbar_(-r)Bbar.
    $ <eq:12-1-1-minimal-parabolic-calculation>
    Moreover $Xbar_(-r) subset.eq Bbar union Bbar nbar_r Bbar$; for
    $xbar_(-r)(t) in Bbar$ if $t=0$, and if $t!=0$
    $
      xbar_(-r)(t) & =xbar_r (t^(-1))nbar_r (-t^(-1))xbar_r (t^(-1)) \
                   & =xbar_r (t^(-1))hbar_r (-t^(-1))nbar_r xbar_r (t^(-1))
                     in Bbar nbar_r Bbar.
    $ <eq:12-1-1-negative-root-cell>
    Hence $Bbar union Bbar nbar_r Bbar$ is a subgroup of $Gbar$.

    #metadata((kind: "anchor")) <th:12-1-1-g>
    #block(sticky: true)[
      (g) It now follows exactly as in #book-ref("p", "8-1-5", [8.1.5]) that
    ]
    $
      Bbar nbar Bbar dot Bbar nbar_r Bbar
      subset.eq Bbar nbar nbar_r Bbar union Bbar nbar Bbar
    $ <eq:12-1-1-double-coset-product>
    for all $nbar in Nbar$, $r in Pi$. Arguing as in #book-ref(
      "p",
      "8-2-2",
      [8.2.2],
    ) we then obtain $Nbar Bbar Nbar subset.eq Bbar Nbar Bbar$ and finally
    $Gbar=Bbar Nbar Bbar$.

    #source(208, "195")
    #block(sticky: true)[For each $w in W$ let]
    $
      Psi_1 & ={r in Phi^+;w(r) in Phi^+}, \
      Psi_2 & ={r in Phi^+;w(r) in Phi^-}
    $ <eq:12-1-1-root-partition>
    #block(sticky: true)[and let]
    $
      Ubar_w^+ & =product_(r in Psi_1) Xbar_r, \
      Ubar_w^- & =product_(r in Psi_2) Xbar_r.
    $ <eq:12-1-1-unipotent-partition>
    Then, since the map $theta:Ubar->U$ is an isomorphism,
    $Ubar=Ubar_w^+ Ubar_w^-$ by #book-ref("l", "8-4-1", [8.4.1]). Also, using
    the relations proved in #book-ref("th", "12-1-1-b", [(b)]), we have
    $ nbar_w Ubar_w^+ nbar_w^(-1) subset.eq Ubar, $
    <eq:12-1-1-positive-conjugate>
    where $nbar_w$ is an element of $Nbar$ corresponding to $w in W$ under the
    natural homomorphism. Hence
    $
      Bbar nbar_w Bbar & =Bbar nbar_w Hbar Ubar_w^+ Ubar_w^- \
                       & =Bbar Hbar nbar_w Ubar_w^+ Ubar_w^-=Bbar
                         nbar_w Ubar_w^-.
    $ <eq:12-1-1-cell-reduction>
    Thus each element $gbar in Gbar$ can be written in the form
    $ gbar=bbar nbar_w ubar, $ <eq:12-1-1-cell-expression>
    where $bbar in Bbar$ and $ubar in Ubar_w^-$.

    #metadata((kind: "anchor")) <th:12-1-1-h>
    (h) For each $w in W$ we choose a fixed coset representative
    $nbar_w in Nbar$ and assume that $nbar_1=1$. We show that each element of
    $Gbar$ has a unique expression of the form
    $ gbar=ubar' hbar nbar_w ubar $ <eq:12-1-1-canonical-expression>
    with $ubar' in Ubar$, $hbar in Hbar$, $w in W$, $ubar in Ubar_w^-$.

    #block(sticky: true)[Suppose that]
    $ ubar'_1 hbar_1 nbar_(w_1)ubar_1=ubar'_2 hbar_2 nbar_(w_2)ubar_2. $
    <eq:12-1-1-canonical-equality>
    #block(sticky: true)[Then]
    $
      theta(ubar'_1)theta(hbar_1)theta(nbar_(w_1))theta(ubar_1)
      =theta(ubar'_2)theta(hbar_2)theta(nbar_(w_2))theta(ubar_2).
    $ <eq:12-1-1-canonical-images>
    By the uniqueness of expression in $G$ proved in #book-ref(
      "cor",
      "8-4-4",
      [8.4.4],
    ) we have
    $
      theta(ubar'_1) & =theta(ubar'_2), \
       theta(hbar_1) & =theta(hbar_2), \
                 w_1 & =w_2, \
       theta(ubar_1) & =theta(ubar_2).
    $ <eq:12-1-1-canonical-factor-images>
    Thus $nbar_(w_1)=nbar_(w_2)$ and, since $theta:Ubar->U$ is an isomorphism,
    we have $ubar'_1=ubar'_2$ and $ubar_1=ubar_2$. It follows that
    $hbar_1=hbar_2$ and so the expression for $gbar$ is unique.

    #source(209, "196")
    #metadata((kind: "anchor")) <th:12-1-1-i>
    (i) We now consider the subgroup $Hbar$. Let $Hbar_r$ be the subgroup of
    $Gbar$ generated by $hbar_r (t)$ for all $t!=0$ in $K$. We show that $Hbar$
    is abelian and that
    $ Hbar=Hbar_(p_1)Hbar_(p_2)dots Hbar_(p_l), $ <eq:12-1-1-torus-factors>
    where $Pi={p_1,p_2,dots,p_l}$. Now
    $
      hbar_r (t)hbar_s (u)hbar_r (t)^(-1)
      & =nbar_r (t)nbar_r (-1)hbar_s (u)nbar_r (-1)^(-1)nbar_r (t)^(-1) \
      & =nbar_r (t)hbar_(w_r (s))(u)nbar_r (t)^(-1) \
      & =hbar_s (u)
    $ <eq:12-1-1-torus-commutation>
    by the relations proved in #book-ref("th", "12-1-1-c", [(c)]). Thus $Hbar$
    is abelian.

    #block(sticky: true)[In order to show that]
    $ Hbar=product_(i=1)^l Hbar_(p_i) $ <eq:12-1-1-torus-factorization-goal>
    #block(sticky: true)[we need the relation]
    $ hbar_r (t)nbar_s (u)hbar_r (t)^(-1)=nbar_s (t^(A_(r s))u). $
    <eq:12-1-1-torus-on-n>
    #block(sticky: true)[
      This can be derived from the relations proved in #book-ref(
        "th",
        "12-1-1-e",
        [(e)],
      ) as follows:
    ]
    $
      hbar_r (t)nbar_s (u)hbar_r (t)^(-1)
      & =hbar_r (t)xbar_s (u)xbar_(-s)(-u^(-1))xbar_s (u)hbar_r (t)^(-1) \
      & =xbar_s (t^(A_(r s))u)xbar_(-s)(-t^(A_(r,-s))u^(-1))
      xbar_s (t^(A_(r s))u) \
      & =nbar_s (t^(A_(r s))u).
    $ <eq:12-1-1-torus-on-n-calculation>

    Let $hbar_r (t)$ be one of the generators of $Hbar$. If $r in Pi$ then
    certainly
    $
      hbar_r (t) in product_(i=1)^l Hbar_(p_i).
    $ <eq:12-1-1-simple-torus-factor>
    Otherwise $r=w(p_i)$ for some $p_i in Pi$ and we use induction on $l(w)$.
    There exists $s in Pi$ such that $w=w_s w'$, where $l(w')=l(w)-1$. Let
    $rho=w'(p_i)$. Then
    $
      hbar_r (t) & =hbar_(w_s (rho))(t)=nbar_s hbar_rho (t)nbar_s^(-1) \
                 & =nbar_s nbar_s (t^(A_(rho s)))^(-1)hbar_rho (t) \
                 & =hbar_s (t^(-A_(rho s)))hbar_rho (t).
    $ <eq:12-1-1-torus-induction>
    Both $hbar_s (t^(-A_(rho s)))$ and $hbar_rho (t)$ may be assumed to lie in
    $ product_(i=1)^l Hbar_(p_i) $ <eq:12-1-1-torus-induction-hypothesis>
    by induction, thus $hbar_r (t)$ is in
    $ product_(i=1)^l Hbar_(p_i) $ <eq:12-1-1-torus-induction-conclusion>
    #source(210, "197")
    also. It follows that
    $ Hbar=product_(i=1)^l Hbar_(p_i). $ <eq:12-1-1-torus-factorization>

    #metadata((kind: "anchor")) <th:12-1-1-j>
    (j) We consider finally the kernel of $theta$. Let $ubar' hbar nbar_w ubar$
    be in this kernel. Then
    $ theta(ubar')theta(hbar)theta(nbar_w)theta(ubar)=1. $
    <eq:12-1-1-kernel-image>
    By uniqueness of expression in $G$ we have
    $
       theta(ubar') & =1, \
        theta(hbar) & =1, \
      theta(nbar_w) & =1, \
        theta(ubar) & =1.
    $ <eq:12-1-1-kernel-factor-images>
    Hence $w=1$ and so $nbar_w=1$. Also $ubar'=1$ and $ubar=1$ since
    $theta:Ubar->U$ is an isomorphism. Thus $ubar' hbar nbar_w ubar=hbar$, and
    so the kernel of $theta$ is contained in $Hbar$. Let
    $ hbar=product_(i=1)^l hbar_(p_i)(t_i) $ <eq:12-1-1-kernel-torus-element>
    be in the kernel of $theta$. Then
    $
      hbar xbar_r (t)hbar^(-1)
      =xbar_r (t product_(i=1)^l t_i^(n_i)), quad "where" n_i=A_(p_i r),
    $ <eq:12-1-1-kernel-conjugation>
    by the relations proved in #book-ref("th", "12-1-1-e", [(e)]). Applying
    $theta$ we have
    $ x_r (t)=x_r (t product_(i=1)^l t_i^(n_i)). $
    <eq:12-1-1-kernel-conjugation-image>
    #block(sticky: true)[Hence]
    $ product_(i=1)^l t_i^(n_i)=1 $ <eq:12-1-1-kernel-weights>
    and so $hbar$ commutes with $xbar_r (t)$. Since the elements $xbar_r (t)$
    generate $Gbar$, $hbar$ must be in the centre $Zbar$ of $Gbar$. Thus the
    kernel of $theta$ is contained in $Zbar$. However the Chevalley group $G$
    has trivial centre by #book-ref("th", "11-1-2", [11.1.2]). Thus $Zbar$ is
    the kernel of $theta$ and the proof is complete. #qed

    The group $Gbar$ defined in #book-ref("th", "12-1-1", [12.1.1]) is called
    the _universal Chevalley group_ of type $frak(L)$ over $K$. It can be shown
    that in the universal Chevalley group each element of $Hbar$ has a unique
    expression of the form
    $ hbar_(p_1)(t_1)hbar_(p_2)(t_2)dots hbar_(p_l)(t_l) $
    <eq:12-1-universal-torus-coordinates>
    #source(211, "198")
    and that $Hbar$ is therefore isomorphic to a direct product of copies of
    $K^*$, the multiplicative group of $K$. A system of relations defining the
    Chevalley group $G$ may be obtained by adding to the relations defining the
    universal group $Gbar$ further relations defining the subgroup $H$ in terms
    of the generators $h_(p_i)(t)$.

    If $frak(L)=A_1$, when the argument of #book-ref("th", "12-1-1", [12.1.1])
    breaks down, it has been shown by Steinberg that the result remains valid if
    the commutator relations are replaced by the relations
    $ nbar_r (t)xbar_r (u)nbar_r (t)^(-1)=xbar_(-r)(-t^(-2)u), $
    <eq:12-1-rank-one-relation>
    where $t,u in K$ and $t!=0$.

    Let $Gbar$ be a universal Chevalley group and $N$ be a subgroup of its
    centre $Zbar$. Then $N$ is normal in $Gbar$ and the factor group
    $Gbar slash N$ is a group generated by elements $xbar_r (t)$ in which the
    relations of theorem #book-ref("th", "12-1-1", [12.1.1]) are valid. Such
    groups $Gbar slash N$ are also often called Chevalley groups. Thus all the
    Chevalley groups for a given $frak(L)$ and $K$ are factor groups of the
    universal Chevalley group $Gbar$, and they all contain as factor groups the
    ‘ordinary’ Chevalley group $G approx.eq Gbar slash Zbar$. The group $G$ is
    often called the _adjoint Chevalley group_ of type $frak(L)$ over $K$.

    It is not difficult to determine which elements
    $ product_(i=1)^l hbar_(p_i)(t_i) $ <eq:12-1-centre-element>
    of $Hbar$ are in the centre $Zbar$. We know that these are precisely the
    elements for which
    $ product_(i=1)^l h_(p_i)(t_i)=1 $ <eq:12-1-centre-adjoint-image>
    in $G$. Now
    $
      product_(i=1)^l h_(p_i)(t_i)
      =product_(i=1)^l h(chi_(p_i,t_i))=h(product_(i=1)^l chi_(p_i,t_i))
    $ <eq:12-1-character-product>
    as in section #book-ref("sec", "diagonal-subgroup"). Thus
    $
      product_(i=1)^l h_(p_i)(t_i)=1
      quad "if and only if" quad product_(i=1)^l chi_(p_i,t_i)=1.
    $ <eq:12-1-character-kernel>
    This is so if and only if this character takes value $1$ at each fundamental
    root. Now
    $
      chi_(p_i,t_i)(p_j)=t_i^(2 lr((p_i,p_j)) slash lr((p_i,p_i)))
      =t_i^(A_(i j)).
    $
    <eq:12-1-character-on-simple-root>
    #block(sticky: true)[Thus]
    $ product_(i=1)^l chi_(p_i,t_i)=1 $ <eq:12-1-trivial-character>
    #source(212, "199")
    #block(sticky: true)[if and only if]
    $ product_(i=1)^l t_i^(A_(i j))=1 $ <eq:12-1-central-torus-equations>
    for $j=1,dots,l$. Now it was shown in section #book-ref(
      "sec",
      "diagonal-subgroup",
    ) that if $P$ is the additive group generated by the fundamental roots and
    $Q$ is the additive group generated by the fundamental weights then
    $Q slash P$ is generated by elements $overline(q)_1,dots,overline(q)_l$
    subject to relations
    $ sum_(i=1)^l A_(i j)overline(q)_i=0. $ <eq:12-1-weight-quotient-relations>
    #block(sticky: true)[If we compare this with the relation]
    $ product_(i=1)^l t_i^(A_(i j))=1 $ <eq:12-1-central-weight-equations>
    #block(sticky: true)[we see that]
    $
      product_(i=1)^l hbar_(p_i)(t_i) in Zbar
    $ <eq:12-1-centre-character-criterion>
    if and only if $t_1,dots,t_l$ determine a $K$-character of $Q slash P$. In
    fact $Zbar$ is isomorphic to the group of $K$-characters of $Q slash P$.
  ]

  #[
    #import "main-defs.typ": book-ref, mathclap, qed, source
    #import "diagrams/graph-symmetries.typ": diagram-symmetries
    #let ad = math.op("ad")
    #let rbar = $overline(r)$
    #let rel(n) = book-ref("eq", "12-2-r" + str(n), $cal(R)_#n$)

    // Source212 was anchored in12.1; this file continues below that section.
    #heading(level: 2)[
      Diagonal, Field and Graph Automorphisms
    ] <sec:diagonal-field-and-graph-automorphisms>

    We turn now to a discussion of automorphisms of Chevalley groups. An
    automorphism is uniquely determined by its effect on the generators
    $x_r (t)$.

    #block(sticky: true)[
      #metadata((kind: "anchor")) <p:12-2-1>
      #smallcaps[Proposition 12.2.1.] _Let $G=frak(L)(K)$ be an adjoint
      Chevalley group. A bijective map of $G$ onto itself is an isomorphism
      provided it preserves the relations_
    ]
    $ cal(R)_1. quad x_r (t_1)x_r (t_2)=x_r (t_1+t_2), $ <eq:12-2-r1>
    $
      cal(R)_2. quad [x_s (u),x_r (t)]=product_(mathclap(i","j>0))
      x_(i r+j s)(C_(i j r s)(-t)^i u^j),
    $ <eq:12-2-r2>
    $ cal(R)_3. quad h_r (t_1)h_r (t_2)=h_r (t_1 t_2), quad t_1,t_2!=0, $
    <eq:12-2-r3>
    _where $h_r (t)=n_r (t)n_r (-1)$ and
    $n_r (t)=x_r (t)x_(-r)(-t^(-1))x_r (t)$._

    #smallcaps[Proof.] Such a map determines an automorphism of the universal
    Chevalley group $overline(G)$ by #book-ref("th", "12-1-1", [12.1.1]). Such
    an automorphism leaves $overline(Z)$ invariant since this is a
    characteristic subgroup of $overline(G)$. It therefore induces an
    automorphism of $overline(G) slash overline(Z)$, which is isomorphic to $G$.
    #qed

    #source(213, "200")
    We next describe some particular kinds of automorphism.

    #metadata((kind: "anchor")) <def:12-2-diagonal>
    #smallcaps[Diagonal automorphisms.] It was shown in section #book-ref(
      "sec",
      "diagonal-subgroup",
    ) that $G$ is normalized by $hat(H)$ in the group of all automorphisms of
    $frak(L)_K$. Thus if $h(chi) in hat(H)$ the map
    $ g->h(chi)g h(chi)^(-1) $ <eq:12-2-diagonal-automorphism>
    is an automorphism of $G$. If $h(chi)$ is in $hat(H)$ but not in $H$ the
    automorphism is called a diagonal automorphism. If the automorphisms of
    $frak(L)_K$ are represented by matrices with respect to the Chevalley basis
    the diagonal automorphisms of $G$ are obtained by transforming by suitable
    diagonal matrices.

    #metadata((kind: "anchor")) <def:12-2-field>
    #smallcaps[Field automorphisms.] Let $f$ be an automorphism of the field
    $K$. Then the map
    $ x_r (t)->x_r (f(t)), quad r in Phi, quad t in K, $
    <eq:12-2-field-automorphism>
    can be extended to an automorphism of $G$. To show this we must verify that
    the relations #rel(1), #rel(2), #rel(3) are preserved. This is clear for
    #rel(
      1,
    ) and #rel(2) and, since $h_r (t)$ is mapped into $h_r (f(t))$, for #rel(3)
    also. The automorphisms obtained in this way are called field automorphisms
    of $G$.

    #metadata((kind: "anchor")) <def:12-2-graph>
    #smallcaps[Graph automorphisms.] Automorphisms of this type arise from
    symmetries of the Dynkin diagram. A symmetry of the Dynkin diagram of
    $frak(L)$ is a permutation $rho$ of the nodes of the diagram such that the
    number of bonds joining nodes $i,j$ is the same as the number of bonds
    joining nodes $rho(i),rho(j)$ for all $i!=j$. The non-trivial symmetries of
    the connected Dynkin diagrams are indicated in the #book-ref(
      "fig",
      "12-2-symmetries",
      [figure],
      highlight: false,
    ).

    #figure(diagram-symmetries(), caption: none, outlined: false)
    <fig:12-2-symmetries>

    #source(214, "201")
    #metadata((kind: "anchor")) <p:12-2-2>
    #smallcaps[Proposition 12.2.2.] _Suppose all the roots of $frak(L)$ have the
    same length and let $rho$ be a symmetry of the Dynkin diagram of $frak(L)$.
    Then $rho$ determines a permutation of the corresponding fundamental system
    $Pi$. Let $tau$ be the linear transformation of $frak(V)$ into itself which
    coincides with this permutation on $Pi$. Then $tau$ is an isometry of
    $frak(V)$ and $tau(Phi)=Phi$._

    #smallcaps[Proof.] Let $n_(i j)$ be the number of bonds joining the nodes
    corresponding to $p_i,p_j in Pi$. Then
    $ n_(i j)=frac(4(p_i,p_j)^2, (p_i,p_i)(p_j,p_j)) $ <eq:12-2-2-bond-number>
    by section #book-ref("sec", "dynkin-diagram"). Now
    $n_(i j)=n_(rho(i)rho(j))$ and, since all the roots have the same length,
    this implies $(p_i,p_j)^2=(p_(rho(i)),p_(rho(j)))^2$. Since $(p_i,p_j)<=0$
    for all $i,j$ with $i!=j$ we have
    $ (p_i,p_j)=(p_(rho(i)),p_(rho(j))), $ <eq:12-2-2-inner-product>
    #block(sticky: true)[i.e.]
    $ (p_i,p_j)=(tau(p_i),tau(p_j)). $ <eq:12-2-2-isometry>
    Thus $tau$ extends by linearity to an isometry of $frak(V)$. Now
    $tau(p_i)=p_(rho(i))$ and therefore $tau w_(p_i)tau^(-1)=w_(p_(rho(i)))$. It
    follows that $tau w tau^(-1) in W$ for all $w in W$, since $W$ is generated
    by its fundamental reflections. Let $r in Phi$. Then $r=w(p_i)$ for some
    $w in W$, $p_i in Pi$. Thus
    $ tau(r)=tau w(p_i)=tau w tau^(-1) dot tau(p_i) in W(Pi)=Phi. $
    <eq:12-2-2-root-permutation>
    Hence $tau(Phi)=Phi$. #qed

    If $tau$ is as in #book-ref("p", "12-2-2", [12.2.2]) we write $tau(r)=rbar$
    for $r in Phi$.

    #block(sticky: true)[
      #metadata((kind: "anchor")) <p:12-2-3>
      #smallcaps[Proposition 12.2.3.] _Suppose $frak(L)$ is a simple Lie algebra
      whose roots all have the same length, and let $r->rbar$ be a map of $Phi$
      into itself arising from a symmetry of the Dynkin diagram of $frak(L)$.
      Then there exist numbers $gamma_r=plus.minus 1$ such that the map_
    ]
    $ x_r (t)->x_rbar (gamma_r t) $ <eq:12-2-3-graph-automorphism>
    _can be extended to an automorphism of $G$. The $gamma_r$ can be chosen so
    that $gamma_r=1$ if $r in Pi$ or $-r in Pi$._

    #smallcaps[Proof.] We use the isomorphism theorem for simple Lie algebras
    given in #book-ref("th", "3-5-2", [3.5.2]). Take $frak(L)'=frak(L)$ and
    $p'_i=p_(rho(i))$. Then there exists an automorphism of $frak(L)$ such that
    $
         e_r & ->e_rbar, \
      e_(-r) & ->e_(-rbar), \
         h_r & ->h_rbar
    $ <eq:12-2-3-simple-root-images>
    #source(215, "202")
    for $r in Pi$. We show that, for each $r in Phi$, $e_r->gamma_r e_rbar$
    under this automorphism, where $gamma_r=plus.minus 1$. This is true for the
    fundamental roots. If $r$ is positive but not fundamental we use induction
    on $h(r)$. $r$ can be written as $r=r_1+r_2$ where $r_1,r_2 in Phi^+$ and
    $h(r_1)<h(r)$, $h(r_2)<h(r)$. By induction we have
    $ e_(r_1)->gamma_(r_1)e_(rbar_1), quad e_(r_2)->gamma_(r_2)e_(rbar_2). $
    <eq:12-2-3-induction-images>
    #block(sticky: true)[Thus]
    $ N_(r_1,r_2)e_r->gamma_(r_1)gamma_(r_2)N_(rbar_1,rbar_2)e_rbar $
    <eq:12-2-3-bracket-image>
    #block(sticky: true)[and so]
    $
      gamma_r=frac(gamma_(r_1)gamma_(r_2)N_(rbar_1,rbar_2), N_(r_1,r_2))
      =plus.minus 1.
    $ <eq:12-2-3-signs>
    For negative roots we use the fact that $[e_r e_(-r)]=h_r$. This shows that
    $gamma_r gamma_(-r)=1$, so that $gamma_(-r)=plus.minus 1$ also.

    We now transfer to an arbitrary field $K$. Since we have an automorphism of
    $frak(L)$ under which
    $ e_r->gamma_r e_rbar, quad h_r->h_rbar $ <eq:12-2-3-integral-images>
    for all $r in Phi$, the same map determines an automorphism of $frak(L)_K$
    for any field $K$. Let this automorphism of $frak(L)_K$ be denoted by
    $theta$. Then
    $
      theta x_r (t)theta^(-1) & =theta exp ad(t e_r)theta^(-1) \
                              & =exp ad theta(t e_r) \
                              & =exp ad(gamma_r t e_rbar)=x_rbar (gamma_r t)
    $ <eq:12-2-3-conjugation>
    by #book-ref("l", "5-1-1", [5.1.1]). Since the elements $x_r (t)$ generate
    $G$ it follows that $theta$ normalizes $G$ in the automorphism group of
    $frak(L)_K$. Hence the map
    $ g->theta g theta^(-1) $ <eq:12-2-3-induced-automorphism>
    is an automorphism of $G$ which transforms $x_r (t)$ into
    $x_rbar (gamma_r t)$.

    We obtain in this way automorphisms of order $2$ of $A_l (K)$, $l>=2$;
    $D_l (K)$, $l>=4$; and $E_6(K)$. We also obtain automorphisms of order $3$
    of $D_4(K)$.
    #qed
  ]

  #[
    #import "main-defs.typ": book-ref, figure-ref, qed, source
    #import "diagrams/b2-duality.typ": b2-duality
    #let rbar = $overline(r)$
    #let sbar = $overline(s)$
    #let rsbar = $overline(r+s)$
    #let rrsbar = $overline(2r+s)$
    #let rel(n) = book-ref("eq", "12-2-r" + str(n), $cal(R)_#n$)
    #let case-ref(c) = book-ref("eq", "12-3-case-" + c, [(#c)])

    // Source215 was anchored in12.2; continue below that section.
    #heading(level: 2)[
      Graph Automorphisms of $B_2(K)$ and $F_4(K)$
    ] <sec:graph-automorphisms-b2-and-f4>

    If the roots of $frak(L)$ are not all of the same length the situation is
    more complicated, since the argument of #book-ref("p", "12-2-2", [12.2.2])
    and #book-ref("p", "12-2-3", [12.2.3]) no longer applies. The linear
    transformation of $frak(V)$ which extends the permutation of the fundamental
    roots is not an isometry, nor does it map the root system into itself. For
    example, consider the case $frak(L)=B_2$ and
    $ Phi^+={a,b,a+b,2a+b}. $ <eq:12-3-b2-positive-roots>
    #source(216, "203")
    Then the transformation maps $a$ into $b$, $b$ into $a$ and $2a+b$ into
    $2b+a$, which is not a root. Thus the symmetries of the Dynkin diagrams of
    type $B_2$, $G_2$ and $F_4$ do not in general give rise to graph
    automorphisms. However, it is in fact possible to find such graph
    automorphisms over certain fields $K$, although the form of these
    automorphisms is more complicated than that given in #book-ref(
      "p",
      "12-2-3",
      [12.2.3],
    ). We shall describe graph automorphisms of the groups $B_2(K)$ and $F_4(K)$
    when $K$ is a perfect field of characteristic $2$, and a graph automorphism
    of $G_2(K)$ if $K$ is a perfect field of characteristic $3$.

    #block(sticky: true)[
      #metadata((kind: "anchor")) <l:12-3-1>
      #smallcaps[Lemma 12.3.1.] _Suppose $Phi$ is an indecomposable self-dual
      root system of type $B_2$, $G_2$ or $F_4$. Let $rho$ be the non-trivial
      symmetry of the Dynkin diagram. Then if $Pi={p_1,dots,p_l}$ is a
      fundamental system of $Phi$,_
    ]
    $ {p_(rho(1)),dots,p_(rho(l))} $ <eq:12-3-1-dual-system>
    _is a fundamental system of $Phi$ dual to $Pi$ (cf. #book-ref(
      "p",
      "3-6-1",
      [3.6.1],
    ))._

    #smallcaps[Proof.] The angle between $p_(rho(i)),p_(rho(j))$ is the same as
    the angle between $p_i,p_j$ since $rho$ is a symmetry of the diagram. Also
    $p_(rho(i))$ is a long root if and only if $p_i$ is a short one. #qed

    #block(sticky: true)[
      #metadata((kind: "anchor")) <l:12-3-2>
      #smallcaps[Lemma 12.3.2.] _Let $r in Phi$, where $Phi$ is as in #book-ref(
        "l",
        "12-3-1",
        [12.3.1],
      ). Suppose the co-root $h_r$ satisfies_
    ]
    $ h_r=sum_(i=1)^l n_i h_(p_i). $ <eq:12-3-2-coroot-coordinates>
    #block(sticky: true)[_Then the element_]
    $ rbar=sum_(i=1)^l n_i p_(rho(i)) $ <eq:12-3-2-root-image>
    _is in $Phi$._

    #smallcaps[Proof.] $Phi$ is self-dual and ${p_1,dots,p_l}$;
    ${p_(rho(1)),dots,p_(rho(l))}$ are dual fundamental systems. Thus
    $ sum_(i=1)^l n_i p_(rho(i)) $ <eq:12-3-2-dual-root>
    #block(sticky: true)[is in $Phi$ if and only if]
    $ sum_(i=1)^l n_i h_(p_i) $ <eq:12-3-2-dual-coroot>
    has the form $h_r$ for some $r in Phi$. #qed

    #source(217, "204")
    Since $Phi^(**)=Phi$, the map $r->rbar$ of $Phi$ into itself defined by
    #book-ref("l", "12-3-2", [12.3.2]) has order $2$. We observe that if
    $ r=sum_(i=1)^l n_i p_i $ <eq:12-3-root-coordinates>
    #block(sticky: true)[then]
    $ rbar=sum_(i=1)^l n_i frac((p_i,p_i), (r,r)) p_(rho(i)). $
    <eq:12-3-duality-coordinates>

    For example, suppose $frak(L)=B_2$ and $p_1=a$, $p_2=b$ as shown in
    #figure-ref(
      "7",
    ). Then for each $r in Phi$, $rbar$ is the root in the direction obtained by
    reflecting $r$ in the line bisecting $a,b$.

    #figure(
      [#b2-duality() #align(center)[Figure 7]],
      caption: none,
      outlined: false,
    ) <fig:7>

    #block(sticky: true)[
      #metadata((kind: "anchor")) <p:12-3-3>
      #smallcaps[Proposition 12.3.3.] _Suppose $G$ is a Chevalley group $B_2(K)$
      or $F_4(K)$, where $K$ is a perfect field of characteristic $2$. For each
      root $r in Phi$ define $lambda(r)$ to be $1$ if $r$ is a short root and
      $2$ if $r$ is a long root. Then the map_
    ]
    $ x_r (t)->x_rbar (t^(lambda(rbar))), quad r in Phi, quad t in K, $
    <eq:12-3-3-graph-automorphism>
    _can be extended to an automorphism of $G$._

    #smallcaps[Proof.] We show that this map preserves the relations #rel(1),
    #rel(
      2,
    ), #rel(3). To prove that #rel(1) is preserved we must have
    $
      x_rbar (t_1^(lambda(rbar))) x_rbar (t_2^(lambda(rbar)))
      =x_rbar ((t_1+t_2)^(lambda(rbar))).
    $ <eq:12-3-3-addition>
    This is clear if $lambda(rbar)=1$, and if $lambda(rbar)=2$ it is valid over
    a field of characteristic $2$ since $t_1^2+t_2^2=(t_1+t_2)^2$.

    #block(sticky: true)[
      Consider now the relation #rel(3). Under the above map we have
    ]
    #block(breakable: false, width: 100%)[
      $
        n_r (t) & ->x_rbar (t^(lambda(rbar)))
                  x_(-rbar)((-t^(-1))^(lambda(rbar))) x_rbar
                  (t^(lambda(rbar))) \
                & =n_rbar (t^(lambda(rbar))),
      $ <eq:12-3-3-weyl-image>
    ]
    $
      h_r (t)->n_rbar (t^(lambda(rbar))) n_rbar (-1)
      =h_rbar (t^(lambda(rbar))),
    $ <eq:12-3-3-torus-image>
    #source(218, "205")
    again using the fact that $K$ has characteristic $2$. It is now clear that
    #rel(
      3,
    ) is preserved.

    Finally consider relation #rel(2). If $r,s$ are roots such that $r+s$ is a
    root, the roots in the subspace spanned by $r,s$ form a system of type $A_2$
    or $B_2$. (The former possibility cannot occur if $frak(L)=B_2$.) Thus it is
    sufficient to show that the following relations are preserved:

    $ "(a)" quad [x_s (u),x_r (t)]=x_(r+s)(-N_(r,s)t u), $ <eq:12-3-case-a>
    where $r,s$ are of equal length and inclined at $2pi slash 3$.

    $ "(b)" quad [x_s (u),x_r (t)]=x_(r+s)(-N_(r,s)t u), $ <eq:12-3-case-b>
    where $r,s$ are short roots inclined at $pi slash 2$.

    $
      "(c)" quad [x_s (u),x_r (t)]=x_(r+s)(-N_(r,s)t u)
      x_(2r+s)(C_(21r s)t^2 u),
    $ <eq:12-3-case-c>
    where $r$ is short, $s$ is long, and $r,s$ are inclined at $3pi slash 4$.

    Now $K$ has characteristic $2$, so #case-ref("a") becomes
    $ [x_s (u),x_r (t)]=x_(r+s)(t u). $ <eq:12-3-case-a-char2>
    #block(sticky: true)[Applying the given map we obtain]
    $
      [x_sbar (u^(lambda(sbar))),x_rbar (t^(lambda(rbar)))]
      =x_rsbar ((t u)^(lambda(rsbar))).
    $ <eq:12-3-case-a-image>
    #block(sticky: true)[However]
    $
      [x_sbar (u^(lambda(sbar))),x_rbar (t^(lambda(rbar)))]
      =x_(rbar+sbar)(t^(lambda(rbar))u^(lambda(sbar)))
    $ <eq:12-3-case-a-check>
    and so we have a valid relation, since $rsbar=rbar+sbar$ and
    $lambda(rbar)=lambda(sbar)=lambda(rsbar)$.

    #case-ref("b") becomes $[x_s (u),x_r (t)]=1$ since $N_(r,s)=plus.minus 2=0$.
    Thus #case-ref("b") is preserved.

    #block(sticky: true)[#case-ref("c") becomes]
    $ [x_s (u),x_r (t)]=x_(r+s)(t u) x_(2r+s)(t^2 u). $ <eq:12-3-case-c-char2>
    #block(sticky: true)[Applying the given map we obtain]
    $ [x_sbar (u),x_rbar (t^2)]=x_rsbar (t^2 u^2) x_rrsbar (t^2 u). $
    <eq:12-3-case-c-image>
    #block(sticky: true)[However]
    $ [x_sbar (u),x_rbar (t^2)]=x_(rbar+sbar)(t^2 u) x_(rbar+2sbar)(t^2 u^2). $
    <eq:12-3-case-c-check>
    Also $rsbar=rbar+2sbar$, $rrsbar=rbar+sbar$ and so #case-ref("c") is
    preserved.

    Since $K$ is perfect, every element of $K$ is a square. Hence the
    monomorphism of $G$ into itself which extends the above map is bijective, so
    is an automorphism of $G$. #qed
  ]

  #[
    #import "main-defs.typ": book-ref, figure-ref, qed, source
    #import "diagrams/g2-duality.typ": g2-duality
    #import "diagrams/g2-constants-table.typ": constants-table
    #let rbar = $overline(r)$
    #let sbar = $overline(s)$
    #let rsbar = $overline(r+s)$
    #let rrsbar = $overline(2r+s)$
    #let rrrsbar = $overline(3r+s)$
    #let rrrssbar = $overline(3r+2s)$
    #let rel(n) = book-ref("eq", "12-2-r" + str(n), $cal(R)_#n$)
    #let case-ref(c) = book-ref("eq", "12-4-case-" + c, [(#c)])

    #source(219, "206")
    == A Graph Automorphism of $G_2(K)$ <sec:graph-automorphism-g2>

    We now consider the group $G_2(K)$ and show that this has a graph
    automorphism when $K$ is a perfect field of characteristic $3$. Let $p_1=a$,
    $p_2=b$ be fundamental roots of $G_2$. Then, for each $r in Phi$, $rbar$ is
    the root in the direction obtained by reflecting $r$ in the line bisecting
    $a,b$.

    #figure(
      [#g2-duality(bisector: true) #align(center)[Figure 8]],
      caption: none,
      outlined: false,
    ) <fig:8>

    It is considerably more difficult to prove the existence of the graph
    automorphism for $G_2(K)$ than for $B_2(K)$ and $F_4(K)$. There are two
    reasons for this difficulty. Firstly, since $K$ has characteristic $3$
    instead of $2$, care must be taken over the signs of the structure constants
    $N_(r,s)$. Secondly, the graph automorphism of $G_2(K)$ has a ‘nice form’
    only if the structure constants are chosen in a special way, whereas for
    $B_2(K)$ and $F_4(K)$ they could be chosen arbitrarily.

    #block(sticky: true)[
      #metadata((kind: "anchor")) <p:12-4-1>
      #smallcaps[Proposition 12.4.1.] _Let $G=G_2(K)$, where $K$ is a perfect
      field of characteristic $3$. For each $r in Phi$ define $lambda(r)$ to be
      $1$ if $r$ is short and $3$ if $r$ is long. Then the structure constants
      $N_(r,s)$ of $G_2$ can be chosen in such a way that the map_
    ]
    $ x_r (t)->x_rbar (t^(lambda(rbar))), quad r in Phi, quad t in K, $
    <eq:12-4-1-graph-automorphism>
    _extends to an automorphism of $G$._

    #smallcaps[Proof.] It is sufficient to show that the given map transforms
    all relations #rel(1), #rel(2), #rel(3) into valid relations, since the
    perfectness of $K$ then implies that the map induced on $G$ is surjective.

    #source(220, "207")
    Now the relations #rel(1) are certainly preserved. Since
    $
      n_r (t)->n_rbar (t^(lambda(rbar))), quad
      h_r (t)->h_rbar (t^(lambda(rbar))),
    $ <eq:12-4-1-monomial-images>
    the relations #rel(3) are also preserved. The non-trivial relations #rel(2)
    to be considered have the following forms:

    $ "(a)" quad [x_s (u),x_r (t)]=x_(r+s)(-N_(r,s)t u), $ <eq:12-4-case-a>
    where $r,s$ are short roots inclined at $pi slash 3$.

    $ "(b)" quad [x_s (u),x_r (t)]=x_(r+s)(-N_(r,s)t u), $ <eq:12-4-case-b>
    where $r,s$ have the same length and are inclined at $2pi slash 3$.

    $
      "(c)" quad [x_s (u),x_r (t)] & =x_(r+s)(-C_(11r s)t u)
                                     x_(2r+s)(C_(21r s)t^2 u) \
                                   & quad times x_(3r+s)(-C_(31r s)t^3 u)
                                     x_(3r+2s)(-C_(32r s)t^3 u^2),
    $ <eq:12-4-case-c>
    where $r$ is short, $s$ is long, and $r,s$ are inclined at $5pi slash 6$.

    #block(sticky: true)[Now #case-ref("a") becomes]
    $ [x_s (u),x_r (t)]=1, $ <eq:12-4-case-a-char3>
    since $N_(r,s)=plus.minus 3=0$. Hence #case-ref("a") is preserved.

    #block(sticky: true)[Applying the given map to #case-ref("b") we obtain]
    $
      [x_sbar (u^(lambda(sbar))),x_rbar (t^(lambda(rbar)))]
      =x_rsbar (-N_(r,s)t^(lambda(rsbar))u^(lambda(rsbar))).
    $ <eq:12-4-case-b-image>
    #block(sticky: true)[But]
    $
      [x_sbar (u^(lambda(sbar))),x_rbar (t^(lambda(rbar)))]
      =x_(rbar+sbar)(-N_(rbar,sbar)t^(lambda(rbar))u^(lambda(sbar))).
    $ <eq:12-4-case-b-check>
    Since $rsbar=rbar+sbar$ and $lambda(rbar)=lambda(sbar)=lambda(rsbar)$ we
    obtain a valid relation by transforming #case-ref("b") if and only if
    $ N_(rbar,sbar)=N_(r,s). $ <eq:12-4-case-b-condition>

    #block(sticky: true)[
      We now apply the given map to #case-ref("c"). We obtain
    ]
    $
      [x_sbar (u),x_rbar (t^3)] & =x_rsbar (-C_(11r s)t^3 u^3)
                                  x_rrsbar (C_(21r s)t^6 u^3) \
                                & quad times x_rrrsbar (-C_(31r s)t^3 u)
                                  x_rrrssbar (-C_(32r s)t^3 u^2).
    $ <eq:12-4-case-c-image>
    #block(sticky: true)[
      We wish to know when this is a valid relation. However
    ]
    $
      & [x_sbar (u),x_rbar (t^3)]=[x_rbar (t^3),x_sbar (u)]^(-1) \
      & =mat(
          delim: "{", align: #left, row-gap: #0.3em,
          x_(sbar+rbar)(-C_(11sbar rbar)t^3 u)
          x_(2sbar+rbar)(C_(21sbar rbar)t^3 u^2);
          quad times x_(3sbar+rbar)(-C_(31sbar rbar)t^3 u^3)
          x_(3sbar+2rbar)(-C_(32sbar rbar)t^6 u^3)
        )^(-1) \
      & =x_(3sbar+2rbar)(C_(32sbar rbar)t^6 u^3)
        x_(3sbar+rbar)(C_(31sbar rbar)t^3 u^3) \
      & quad times x_(2sbar+rbar)(-C_(21sbar rbar)t^3 u^2)
        x_(sbar+rbar)(C_(11sbar rbar)t^3 u) \
      & =x_(3sbar+rbar)(C_(31sbar rbar)t^3 u^3)
        x_(3sbar+2rbar)(C_(32sbar rbar)t^6 u^3) \
      & quad times x_(sbar+rbar)(C_(11sbar rbar)t^3 u)
        x_(2sbar+rbar)(-C_(21sbar rbar)t^3 u^2),
    $ <eq:12-4-case-c-inverse>
    #source(221, "208")
    the terms involving $sbar+rbar$, $2sbar+rbar$ commuting since
    $ N_(sbar+rbar,2sbar+rbar)=plus.minus 3=0. $ <eq:12-4-commuting-factors>
    #block(sticky: true)[Now we have]
    $
         rsbar & =3sbar+rbar, \
        rrsbar & =3sbar+2rbar, \
       rrrsbar & =sbar+rbar, \
      rrrssbar & =2sbar+rbar.
    $ <eq:12-4-dual-root-identities>
    #block(sticky: true)[
      Thus the transform of #case-ref("c") is a valid relation provided
    ]
    #block(breakable: false, width: 100%)[
      $
        -C_(11r s) & =C_(31sbar rbar), && quad C_(31r s) & =-C_(11sbar rbar), \
         C_(32r s) & =C_(21sbar rbar), && quad C_(21r s) &  =C_(32sbar rbar).
      $ <eq:12-4-four-constant-identities>
    ]
    The first two sets of equations are clearly equivalent, since whenever $r,s$
    are a pair of roots related as in #case-ref("c"), $sbar,rbar$ are also.
    Similarly the last two sets of equations are equivalent. Thus the given map
    preserves all the relations provided
    $
      N_(r,s)=N_(rbar,sbar) quad "whenever" r,s "are as in" #case-ref("b").
    $ <eq:12-4-short-condition>
    $
      cases(-C_(31r s)=C_(11sbar rbar), C_(32r s)=C_(21sbar rbar))
      quad "whenever" r,s "are as in" #case-ref("c").
    $ <eq:12-4-mixed-condition>
    It is more convenient to write the first of these conditions in the form
    $ -frac(1, 2)N_(r,s)=N_(rbar,sbar) $ <eq:12-4-integral-condition>
    whenever $r,s$ are short roots inclined at $2pi slash 3$, since both sides
    of this equation, when interpreted as rational integers, now have absolute
    value $1$. (Note that $-1 slash 2=1$ in $K$!)

    In order to complete the proof of #book-ref("p", "12-4-1", [12.4.1]) it is
    sufficient to prove the following lemma.

    #block(sticky: true)[
      #metadata((kind: "anchor")) <l:12-4-2>
      #smallcaps[Lemma 12.4.2.] _The structure constants of the Lie algebra
      $G_2$ over the complex field can be chosen so that_
    ]
    $ -frac(1, 2)N_(r,s)=N_(rbar,sbar) $ <eq:12-4-2-first-condition>
    _whenever $r,s$ are short roots inclined at $2pi slash 3$,_
    $ -C_(31r s)=C_(11sbar rbar) $ <eq:12-4-2-second-condition>
    _whenever $r$ is short, $s$ is long, and $r,s$ are inclined at
    $5pi slash 6$._

    #source(222, "209")
    #block(sticky: true)[_They then also satisfy the condition_]
    $ C_(32r s)=C_(21sbar rbar) $ <eq:12-4-2-third-condition>
    _whenever $r$ is short, $s$ is long, and $r,s$ are inclined at
    $5pi slash 6$._

    #block(sticky: true)[
      #smallcaps[Proof.] We show that the third condition follows from the other
      two. We have
    ]
    #block(breakable: false, width: 100%)[
      $
        C_(21sbar rbar) & =frac(1, 2)N_(sbar,rbar)N_(sbar,sbar+rbar) \
                        & =frac(1, 2) dot -frac(1, 6)N_(r,s)N_(r,r+s)N_(r,2r+s)
                          dot -2N_(s,3r+s)
      $ <eq:12-4-2-third-from-first-two>
    ]
    using relations of the first and second types. However the relation
    $ N_(r,s)N_(r,2r+s)=-N_(r+s,2r+s)N_(s,3r+s) $ <eq:12-4-2-four-root-relation>
    is easily deduced from the fact that
    $ (r+s)+(2r+s)+(-s)+(-3r-s)=0, $ <eq:12-4-2-four-root-sum>
    as in #book-ref("l", "5-2-1", [5.2.1]). Therefore we have
    $
      C_(21sbar rbar) & =-frac(1, 6)N_(r,r+s)N_(r+s,2r+s)N_(s,3r+s)^2 \
                      & =frac(1, 6)N_(r+s,r)N_(r+s,2r+s) \
                      & =frac(1, 3)M_(r+s,r,2) \
                      & =C_(32r s).
    $ <eq:12-4-2-third-condition-proof>

    We now show that it is possible to choose the signs of the structure
    constants $N_(r,s)$ so that the given conditions are satisfied. The result
    of #book-ref(
      "p",
      "4-2-2",
      [4.2.2],
    ) shows that the signs of $N_(a,b)$, $N_(a,a+b)$, $N_(a,2a+b)$ and
    $N_(b,3a+b)$ can
    #source(223, "210")
    be chosen arbitrarily and that the remaining $N_(r,s)$ are then determined.
    Define $epsilon_i=plus.minus 1$ by
    $
         N_(a,b) & =epsilon_1, \
       N_(a,a+b) & =2epsilon_2, \
      N_(a,2a+b) & =3epsilon_3, \
      N_(b,3a+b) & =epsilon_4.
    $ <eq:12-4-extraspecial-signs>
    #figure(
      [#block[#g2-duality() #align(center)[Figure 9]] <fig:9>],
      placement: top,
      caption: none,
      outlined: false,
    )
    #block(sticky: true)[Then]
    $ N_(a+b,2a+b)=-3frac(epsilon_1 epsilon_3, epsilon_4) $
    <eq:12-4-fifth-positive-constant>
    by #book-ref("th", "4-1-2", [4.1.2]) (iv) and the remaining $N_(r,s)$ may be
    calculated using #book-ref("th", "4-1-2", [4.1.2]) (i), (ii), (iii).

    Now if $r,s$ are short roots inclined at $2pi slash 3$ so are $-r,-s$ and
    the relation $-frac(1, 2)N_(r,s)=N_(rbar,sbar)$ is equivalent to
    $-frac(1, 2)N_(-r,-s)=N_(-rbar,-sbar)$. Thus it is sufficient to check this
    relation when $(r,s)$ is $(a,a+b)$, $(2a+b,-a)$ or $(a+b,-2a-b)$. In all
    these three cases the relation holds if and only if $epsilon_2=-epsilon_4$.

    Similarly, if $r$ is short, $s$ is long and $r,s$ are inclined at
    $5pi slash 6$ the same is true of $-r,-s$; and the relation
    $-C_(31r s)=C_(11sbar rbar)$ is equivalent to
    $-C_(3,1,-r,-s)=C_(1,1,-sbar,-rbar)$. Thus it is sufficient to check this
    relation when $(r,s)$ is $(a,b)$, $(2a+b,-3a-b)$, $(a,-3a-b)$,
    $(2a+b,-3a-2b)$, $(a+b,-3a-2b)$ or $(a+b,-b)$. In the first four cases the
    relation holds if and only if $epsilon_2=-epsilon_3$ and in the last two
    cases if and only if $epsilon_2=-epsilon_4$. Thus the structure constants
    satisfy the required conditions if and only if
    $-epsilon_2=epsilon_3=epsilon_4$. This completes the proof. #qed

    It may be useful to give an explicit choice of the structure constants for
    which the graph automorphism has the form given in #book-ref(
      "p",
      "12-4-1",
      [12.4.1],
    ). This is done in the #book-ref(
      "fig",
      "12-4-constants",
      [table below],
      highlight: false,
    ). The structure constant $N_(r,s)$ appears in the row indexed by $r$ and
    the column indexed by $s$. In this presentation we have chosen
    $epsilon_1=-1$, $epsilon_2=-1$, $epsilon_3=1$, $epsilon_4=1$.

    #source(224, "211")
    #metadata((kind: "anchor")) <fig:12-4-constants>
    #constants-table()
  ]

  #[
    #import "main-defs.typ": book-ref, chapter-ref, qed, source

    // Source223 lower follows the12.4 table; its anchor already exists.
    #heading(level: 2)[
      Automorphisms of Finite Chevalley Groups
    ] <sec:finite-chevalley-group-automorphisms>

    The automorphisms so far described, the diagonal, field and graph
    automorphisms, together with the inner automorphisms, are sufficient to
    generate the whole group of automorphisms of $G=frak(L)(K)$ if the field $K$
    is finite. We shall now prove this result, which is due to Steinberg.

    // Source224 below the table; source-page anchor already exists in12.4.
    #block(sticky: true)[
      #metadata((kind: "anchor")) <th:12-5-1>
      #smallcaps[Theorem 12.5.1.] _Let $G=frak(L)(K)$ when $frak(L)$ is simple
      and $K=G F(q)$. Let $theta$ be an automorphism of $G$. Then there exist
      inner, diagonal, graph and field automorphisms $i,d,g,f$ such that
      $theta=i d g f$._
    ]

    #smallcaps[Proof.] Let $q$ be a power of the prime $p$. Then $U,V$ are Sylow
    $p$-subgroups of $G$, by #book-ref("th", "9-4-10", [9.4.10]). By Sylow’s
    theorem, any two Sylow $p$-subgroups are conjugate. Now $theta(U)$ is also a
    Sylow $p$-subgroup of $G$, so is conjugate to $U$. Thus there exists an
    inner automorphism $i_1$ of $G$ such that $theta(U)=i_1 (U)$. Let
    $theta_1=i_1^(-1)
    theta$. Then $theta_1 (U)=U$. Now $theta_1 (V)$ is a Sylow $p$-subgroup of
    $G$ so is conjugate to $U$. Thus $theta_1 (V)=x^(-1)U x$ for some $x in G$.
    However, $x$ can be written in the form $x=b n_w u$, where $b in B,w in W,
    u in U_w^-$ as in #book-ref("th", "8-4-3", [8.4.3]). Since $b$ normalizes
    $U$ we have
    $ theta_1 (V)=u^(-1)n_w^(-1)U n_w u. $ <eq:12-5-opposite-sylow-image>
    Now $U inter V=1$ and so $theta_1 (U) inter theta_1 (V)=1$. Hence
    $U inter u^(-1)n_w^(-1)U n_w u=1$ and it follows that
    $n_w U n_w^(-1) inter U=1$. By #book-ref("l", "7-2-1", [7.2.1]) this implies
    that $w$ transforms every positive root into a negative root, thus $w=w_0$
    by #book-ref("p", "2-2-6", [2.2.6]). Therefore
    $ n_w^(-1)U n_w=n_(w_0)^(-1)U n_(w_0)=V. $ <eq:12-5-longest-element>
    It follows that $theta_1 (V)=u^(-1)V u$. Let $i_2$ be the inner automorphism
    $y->u^(-1)y u$ of $G$ and let $theta_2=i_2^(-1)theta_1$. Then
    $theta_2 (U)=U$ and $theta_2 (V)=V$.

    Now $frak(N)_G (U)=U H$ by #book-ref("th", "8-5-2", [8.5.2]) (iii) and
    similarly we have $frak(N)_G (V)=V H$. Thus $theta_2$ leaves $U H$ and $V H$
    invariant. Also $U H inter V H=H$ by #book-ref("cor", "7-1-3", [7.1.3]) and
    so $theta_2 (H)=H$. Since $theta_2$ leaves $U H=B$ invariant, it permutes
    the minimal parabolic subgroups containing $B$. By #book-ref(
      "th",
      "8-3-2",
      [8.3.2],
    ) these have the
    #source(225, "212")
    form
    $ P_{r}=B union B n_r B, quad r in Pi. $ <eq:12-5-minimal-parabolics>
    #block(sticky: true)[
      We shall show now that $P_{r} inter V=X_(-r)$. We have
    ]
    $
      P_{r} & =B union B n_r B \
            & =(B union B n_r B)n_r^(-1) \
            & =B n_r^(-1) union B n_r B n_r^(-1) \
            & =B n_r^(-1) union B X_(-r).
    $ <eq:12-5-parabolic-decomposition>
    #block(sticky: true)[Consider the subset $B n_r^(-1) inter V$. We have]
    $
      B n_r^(-1) inter V & =B n_r^(-1) inter n_(w_0)U n_(w_0)^(-1) \
                         & subset (B n_r^(-1)n_(w_0) inter
                             n_(w_0)U)n_(w_0)^(-1) \
                         & subset (B n_r^(-1)n_(w_0)B inter B
                             n_(w_0)B)n_(w_0)^(-1).
    $ <eq:12-5-disjoint-cells>
    #block(sticky: true)[However]
    $
      B n_r^(-1)n_(w_0)B inter B n_(w_0)B=emptyset
    $ <eq:12-5-empty-intersection>
    by #book-ref("p", "8-2-3", [8.2.3]), thus $B n_r^(-1) inter V=emptyset$
    also. Hence
    $ P_{r} inter V=B X_(-r) inter V=(B inter V)X_(-r)=X_(-r) $
    <eq:12-5-negative-root-intersection>
    since $B inter V=1$ by #book-ref("l", "7-1-2", [7.1.2]).

    Now $theta_2$ maps $V$ into itself and permutes the subgroups $P_{r}$ for
    the fundamental roots $r in Pi$. Thus $theta_2$ permutes the subgroups
    $X_(-r)$ for $r in Pi$. One can show in a similar way that $theta_2$
    permutes the subgroups $X_r,r in Pi$. However, if $r,s$ are distinct
    fundamental roots, the commutator formula implies that $[X_r,X_(-s)]=1$,
    whereas the result of #chapter-ref("root-sl2-subgroups") implies that
    $[X_r,X_(-r)]!=1$. Thus, if $r,s in Pi$, $[X_r,X_(-s)]=1$ if and only if
    $r!=s$. #block(
      sticky: true,
    )[Since this relation is preserved by $theta_2$ we have]
    #block(breakable: false, width: 100%)[
      $
           theta_2 (X_r) & =X_(rho(r)), \
        theta_2 (X_(-r)) & =X_(-rho(r)), quad r in Pi,
      $ <eq:12-5-root-permutation>
    ]
    where $rho$ is a permutation of $Pi$.

    Let $theta_2 dot x_r (1)=x_(rho(r))(t_r)$. Let $chi$ be the $K$-character of
    $P$ defined by
    $ chi(rho(r))=t_r, quad r in Pi. $ <eq:12-5-diagonal-character>
    #block(sticky: true)[Let $d$ be the diagonal automorphism]
    $ y->h(chi)y h(chi)^(-1) $ <eq:12-5-diagonal-automorphism>
    #block(sticky: true)[of $G$. Then we have]
    $
      theta_2 dot x_r (1)=d dot x_(rho(r))(1).
    $ <eq:12-5-diagonal-normalization>

    #source(226, "213")
    #block(sticky: true)[Let $theta_3=d^(-1)theta_2$. Then]
    $ theta_3 dot x_r (1)=x_(rho(r))(1). $ <eq:12-5-positive-normalization>
    #block(sticky: true)[We shall show that]
    $ theta_3 dot x_(-r)(1)=x_(-rho(r))(1). $ <eq:12-5-negative-normalization>
    Let $theta_3 dot x_(-r)(1)=x_(-rho(r))(lambda)$. We prove that $lambda=1$ by
    using the homomorphism from $S L_2 (K)$ into $lr(⟨X_r,X_(-r)⟩)$. We have
    $
      mat(1, 1; 0, 1)mat(1, 0; -1, 1)mat(1, 1; 0, 1)
      =mat(1, 0; -1, 1)mat(1, 1; 0, 1)mat(1, 0; -1, 1)
    $ <eq:12-5-sl2-braid>
    #block(sticky: true)[and it follows that]
    $ x_r (1)x_(-r)(-1)x_r (1)=x_(-r)(-1)x_r (1)x_(-r)(-1). $
    <eq:12-5-root-braid>
    #block(sticky: true)[Applying $theta_3$ we obtain]
    $
      x_(rho(r))(1)x_(-rho(r))(-lambda)x_(rho(r))(1)
      =x_(-rho(r))(-lambda)x_(rho(r))(1)x_(-rho(r))(-lambda).
    $ <eq:12-5-braid-image>
    #block(sticky: true)[However]
    $
      mat(1, 1; 0, 1)mat(1, 0; -lambda, 1)mat(1, 1; 0, 1)
      &=mat(1-lambda, 2-lambda; -lambda, 1-lambda), \
      mat(1, 0; -lambda, 1)mat(1, 1; 0, 1)mat(1, 0; -lambda, 1)
      &=mat(1-lambda, 1; lambda^2-2lambda, 1-lambda)
    $ <eq:12-5-braid-matrices>
    and, since the kernel of the homomorphism
    $S L_2 (K)->lr(⟨X_(rho(r)),X_(-rho(r))⟩)$ contains only $I_2$ and possibly
    $-I_2$, we have $lambda=1$ by comparing the above matrices. Thus
    #block(breakable: false, width: 100%)[
      $
          theta_3 dot x_r (1) & =x_(rho(r))(1), \
        theta_3 dot x_(-r)(1) & =x_(-rho(r))(1)
      $ <eq:12-5-normalized-root-elements>
    ]
    #block(sticky: true)[and it follows that]
    $
      theta_3 (n_r)=theta_3 (x_r (1)x_(-r)(-1)x_r (1))=n_(rho(r)).
    $ <eq:12-5-normalized-weyl-representatives>

    We now show that the permutation $rho$ of $Pi$ induces a symmetry of the
    Dynkin diagram. Since $theta_3 (H)=H$ and
    $theta_3 (n_r n_s)=n_(rho(r))n_(rho(s))$, the order of the coset $n_r n_s H$
    is the same as the order of the coset $n_(rho(r))n_(rho(s))H$ in the group
    $N slash H$. Using the isomorphism between $N slash H$ and $W$, the order of
    $w_r w_s$ is the same as the order of $w_(rho(r))w_(rho(s))$ in $W$. Thus
    the number of bonds joining the nodes $r,s$ in the Dynkin diagram is the
    same as the number of bonds joining $rho(r),rho(s)$. Hence $rho$ is a
    symmetry of the Dynkin diagram.

    #source(227, "214")
    We prove next that there is a graph automorphism $g$ of $G$ such that
    $g(X_r)=X_(rho(r))$ for all $r in Pi$. By #book-ref("p", "12-3-3", [12.3.3])
    and #book-ref("p", "12-4-1", [12.4.1]) this is so provided $K$ has
    characteristic $2$ if $frak(L)=B_2$ or $F_4$ and $rho$ is not the identity,
    and $K$ has characteristic $3$ if $frak(L)=G_2$ and $rho$ is not the
    identity. Suppose $rho$ is the non-trivial symmetry of the Dynkin diagram of
    $frak(L)$, where $frak(L)=B_2$ or $F_4$. Then there exist roots $a,b in Pi$
    interchanged by $rho$ such that the roots which are linear combinations of
    $a,b$ are
    $
      plus.minus a, quad plus.minus b, quad plus.minus(a+b), quad
      plus.minus(2a+b).
    $ <eq:12-5-b2-subsystem>
    Now $n_b X_a n_b^(-1)=X_(a+b)$. Applying $theta_3$ we have
    $n_a X_b n_a^(-1)=theta_3 (X_(a+b))$. Hence $theta_3 (X_(a+b))=X_(2a+b)$.
    However $[X_(2a+b),X_b]=1$. Applying $theta_3^(-1)$ we obtain
    $[X_(a+b),X_a]=1$.

    #block(sticky: true)[But]
    $ [x_(a+b)(1),x_a (1)]=x_(2a+b)(-N_(a,a+b)). $ <eq:12-5-characteristic-two>
    Thus $N_(a,a+b)=0$. But $N_(a,a+b)=plus.minus 2$ and so $K$ has
    characteristic $2$.

    Now suppose $frak(L)=G_2$ and $rho$ is the non-trivial symmetry of the
    Dynkin diagram of $frak(L)$. Then $rho$ interchanges the fundamental roots
    $a,b$ of $frak(L)$ and the other roots are
    $
      plus.minus a, quad plus.minus b, quad plus.minus(a+b), quad
      plus.minus(2a+b), quad plus.minus(3a+b), quad plus.minus(3a+2b).
    $ <eq:12-5-g2-roots>
    Now $n_b X_a n_b^(-1)=X_(a+b)$ and so, applying $theta_3$, we have
    $n_a X_b n_a^(-1)=theta_3 (X_(a+b))$. Thus $theta_3 (X_(a+b))=X_(3a+b)$.
    Also $n_a X_(a+b)n_a^(-1)=X_(2a+b)$ and, applying $theta_3$,
    $n_b X_(3a+b)n_b^(-1)=theta_3 (X_(2a+b))$. Thus
    $theta_3 (X_(2a+b))=X_(3a+2b)$. Now $[X_(3a+2b),X_b]=1$. Applying
    $theta_3^(-1)$ gives $[X_(2a+b),X_a]=1$. However
    $
      [x_(2a+b)(1),x_a (1)]=x_(3a+b)(-N_(a,2a+b)).
    $ <eq:12-5-characteristic-three>
    Thus $N_(a,2a+b)=0$. But $N_(a,2a+b)=plus.minus 3$ and so $K$ has
    characteristic $3$.

    Thus in each case there is a graph automorphism $g$ of $G$ such that
    $g(X_r)=X_(rho(r))$ for $r in Pi$. Let $theta_4=g^(-1)theta_3$. Then
    $theta_4 (X_r)=X_r$ and $theta_4 (X_(-r))=X_(-r)$ for all $r in Pi$. Also
    $theta_4$ fixes $x_r (1)$ and $x_(-r)(1)$, thus $theta_4$ fixes $n_r$ for
    all $r in Pi$. It follows that $theta_4$ fixes each $X_r,r in Phi$. For
    $r=w(s)$ for some $s in Pi$ and $w=w_(r_1)dots w_(r_k)$ with $r_i in Pi$.
    Hence
    $ X_r=n_(r_1)dots n_(r_k)X_s n_(r_k)^(-1)dots n_(r_1)^(-1) $
    <eq:12-5-all-root-subgroups>
    and so $theta_4 (X_r)=X_r$.

    Let $r,s in Pi$ be fundamental roots which are joined in the Dynkin diagram.
    Then $r+s in Phi$. Let
    $
         theta_4 dot x_r (t) & =x_r (f(t)), \
         theta_4 dot x_s (t) & =x_s (g(t)), \
      theta_4 dot x_(r+s)(t) & =x_(r+s)(h(t)).
    $ <eq:12-5-parameter-maps>

    #source(228, "215")
    #block(sticky: true)[Since]
    $ [x_s (u),x_r (t)]=x_(r+s)(-N_(r,s)t u)dots, $
    <eq:12-5-commutator-parameters>
    #block(sticky: true)[we have, on applying $theta_4$,]
    $ [x_s (g(u)),x_r (f(t))]=x_(r+s)(h(-N_(r,s)t u))dots. $
    <eq:12-5-commutator-parameter-image>
    #block(sticky: true)[But]
    $ [x_s (g(u)),x_r (f(t))]=x_(r+s)(-N_(r,s)f(t)g(u))dots $
    <eq:12-5-commutator-parameter-check>
    #block(sticky: true)[and so]
    $ h(-N_(r,s)t u)=-N_(r,s)f(t)g(u). $ <eq:12-5-parameter-relation>
    Now $N_(r,s)=plus.minus 1$, hence $h(t u)=f(t)g(u)$ for all $t,u in K$.
    Putting $u=1$ we have $f(t)=h(t)$ and putting $t=1$ we have $g(u)=h(u)$.
    Hence
    $ f(t)=g(t)=h(t) $ <eq:12-5-equal-parameter-maps>
    for all $t$. We also have $f(t u)=f(t)f(u)$ for all $t,u$. Since the map
    $f:K->K$ is bijective and additive it must be an automorphism of $K$.

    Now $frak(L)$ is simple and so its Dynkin diagram is connected. Thus there
    exists an automorphism $f$ of $K$ such that
    $ theta_4 dot x_r (t)=x_r (f(t)) $ <eq:12-5-field-automorphism>
    for all $r in Pi$. $f$ can be extended to a field automorphism of $G$. Let
    $theta_5=f^(-1)theta_4$. Then
    $ theta_5 dot x_r (t)=x_r (t) $ <eq:12-5-fixed-generators>
    for all $r in Phi,t in K$. Since these elements $x_r (t)$ generate $G$,
    $theta_5$ must be the identity.

    #block(sticky: true)[Now]
    $
      theta_5 & =f^(-1)theta_4=f^(-1)g^(-1)theta_3
                =f^(-1)g^(-1)d^(-1)theta_2 \
              & =f^(-1)g^(-1)d^(-1)i_2^(-1)theta_1 \
              & =f^(-1)g^(-1)d^(-1)i_2^(-1)i_1^(-1)theta.
    $ <eq:12-5-automorphism-decomposition>
    Therefore $theta=i_1 i_2 d g f$ and the theorem is proved. #qed

    #block(sticky: true)[
      (We note that the proof that the function $f$ on $K$ satisfies
    ]
    $ f(t_1)f(t_2)=f(t_1 t_2) $ <eq:12-5-rank-one-caveat>
    breaks down if $frak(L)=A_1$ since we cannot choose two distinct fundamental
    roots. It is not difficult to find an alternative argument to cover this
    case.)

    The result of #book-ref("th", "12-5-1", [12.5.1]) is also valid for perfect
    fields which are not finite. However the proof is more difficult there as
    Sylow’s theorem cannot be used to show that the automorphism can be modified
    to fix $U$ and $V$.
  ]
]

#import "chapter-preview.typ": chapter-preview
#chapter-preview(12, chapter)
