#let chapter = [
  #[
    #import "main-defs.typ": bib-ref, book-ref, source

    #source(316, "303")
    = Sporadic Simple Groups <ch:sporadic-simple-groups>

    The simple groups of Lie type which we have described in the earlier
    chapters include almost all the finite simple groups at present known. In
    addition to the cyclic groups, alternating groups and simple groups of Lie
    type over finite fields, there are nineteen further finite simple groups
    known at the time of writing (February 1971). In order to complete the
    picture regarding the finite simple groups as it now stands, we give a
    description in this final chapter of these nineteen so-called 'sporadic'
    simple groups. This description will be exceedingly brief in comparison with
    the amount of information available about these groups. Further information
    can be found in the survey articles of Tits #bib-ref("bib334-237") and Feit
    #bib-ref("bib327-75"), whose notation we follow here, and in papers dealing
    with each group individually.

    == The Mathieu Groups <sec:mathieu-groups>

    Five sporadic simple groups, which we denote by $M_(11)$, $M_(12)$,
    $M_(22)$, $M_(23)$, $M_(24)$ were described by Mathieu in papers in 1861 and
    1873 #bib-ref("mathieu1861", "mathieu1873"). They can be described most
    easily as groups of automorphisms of Steiner systems.

    A Steiner system of type $(r, s, t)$ is a set $A$ together with a family of
    subsets $B_(i)$ of $A$, called blocks, such that $abs(A)=t$, $abs(B_(i))=s$,
    and each subset of $A$ with $r$ elements is contained in exactly one block
    $B_(i)$. It is known that there is, to within isomorphism, exactly one
    Steiner system of each of the types (5, 6, 12) and (5, 8, 24) (see Witt
    #bib-ref(
      "bib335-250",
      "bib335-251",
    )). These Steiner systems will be denoted by $S(5, 6, 12)$ and
    $S(5, 8, 24)$.

    An automorphism of a Steiner system $A$ is a permutation of $A$ which maps
    each block into a block. It can be shown that the groups of automorphisms of
    $S(5, 6, 12)$ and $S(5, 8, 24)$ are simple and we write

    $ M_12=op("Aut") S(5,6,12), $ <eq:16-1-m12-definition>

    $ M_24=op("Aut") S(5,8,24). $ <eq:16-1-m24-definition>

    The groups $M_(12)$ and $M_(24)$ have the property of being quintuply
    transitive permutation groups. They are in fact the only known quintuply
    transitive
    #source(317, "304")
    permutation groups other than the symmetric and alternating groups. In
    $M_(12)$, the only element which fixes five symbols is the identity, but in
    $M_(24)$ the elements stabilizing each of five given symbols form a subgroup
    of order 48.
    #block(width: 100%, breakable: false)[
      Thus the orders of these groups are given by

      $
        abs(M_12) & =12 dot 11 dot 10 dot 9 dot 8, \
        abs(M_24) & =24 dot 23 dot 22 dot 21 dot 20 dot 48.
      $ <eq:16-1-mathieu-orders>
    ]

    Given a Steiner system of type $(r, s, t)$ we can obtain a Steiner system of
    type $(r-1, s-1, t-1)$ by taking all the blocks $B_(i)$ of $A$ which contain
    a fixed element $a in A$, and then taking the sets $B_(i)-\{a\}$ as blocks
    in the set $A-\{a\}$. Steiner systems $S(4, 7, 23)$ and $S(3, 6, 22)$ can be
    obtained from $S(5, 8, 24)$ by this process, and a Steiner system
    $S(4, 5, 11)$ from $S(5, 6, 12)$.

    We define $M_(23)$ to be the subgroup of $M_(24)$ stabilizing one symbol
    $a in A$. Thus $M_(23)$ is a permutation group on twenty-three symbols, and
    is a group of automorphisms of $S(4,7,23)$. Define $M_(22)$ to be the
    stabilizer of one symbol in $M_(23)$ and $M_(11)$ to be the stabilizer of
    one symbol in $M_(12)$. Then $M_(22)$ is a group of automorphisms of
    $S(3,6,22)$ and $M_(11)$ is a group of automorphisms of $S(4,5,11)$. It is
    known that $M_(23), M_(11)$ are the full automorphism groups of
    $S(4,7,23), S(4,5,11)$ respectively, and that $M_(22)$ is a subgroup of
    index 2 in Aut $S(3,6,22)$.

    Let $M_(10)$, $M_(21)$ be the stabilizers of one symbol in $M_(11)$,
    $M_(22)$ respectively. Then $M_(10)$ has a subgroup of index 2 isomorphic to
    $P S L_(2)(9)$ and operates as a permutation group on the ten points of the
    projective line over $G F(9)$. By #book-ref("th", "12-5-1", [12.5.1]) Aut
    $P S L_(2)(9)$ is generated by the inner automorphisms and by a diagonal
    automorphism $d$ of order 2 and a field automorphism $f$ of order 2. Thus

    $ abs(op("Aut") P S L_2(9):P S L_2(9))=4. $ <eq:16-1-m10-outer-index>

    $M_(10)$ is the subgroup of Aut $P S L_(2)(9)$ generated by $P S L_(2)(9)$
    and the automorphism $d f$.

    $M_(21)$ turns out to be isomorphic to $P S L_(3)(4)$ and operates as a
    permutation group on the twenty-one points of the projective plane over
    $G F(4)$.

    The Mathieu groups may also be defined as transitive extensions. A
    transitive extension of a permutation group $G$ on a set $A$ is a transitive
    permutation group $overline(G)$ on a set
    $overline(A)=A union \{overline(a)\}$ such that the stabilizer of
    $overline(a)$ in $overline(G)$, when restricted to $A$, is $G$. It can be
    shown that $M_(11), M_(12), M_(22), M_(23), M_(24)$ are the unique
    transitive extensions of $M_(10), M_(11), M_(21), M_(22), M_(23)$
    respectively, and that $M_(12), M_(24)$ do not possess transitive
    extensions.
    #source(318, "305")
    Thus the Mathieu groups are uniquely determined in terms of the classical
    groups $M_(10)$ and $M_(21)$.

  ]

  #[
    #import "main-defs.typ": bib-ref, book-ref, source

    #heading(level: 2)[
      Sporadic Simple Groups Characterized by the Centralizer of an Involution
    ] <sec:involution-centralizers>

    Apart from the Mathieu groups, all the other known sporadic simple groups
    have been discovered within the last ten years. The Feit–Thompson theorem
    #bib-ref(
      "bib327-77",
    ) shows that every non-cyclic finite simple group contains an element of
    order 2, i.e. an involution. It was shown by Brauer and Fowler #bib-ref(
      "bib325-21",
    ) that if $C$ is any finite group, there are only finitely many finite
    simple groups $G$ which have an involution $j$ whose centralizer $C(j)$ is
    isomorphic to $C$. Brauer initiated the programme of trying to characterize
    all finite simple groups in which the centralizer of an involution is a
    given group, and very many such characterizations have been obtained. This
    programme has in fact led to the discovery of several sporadic simple
    groups. A typical result of this type asserts that if $G$ is a simple group
    which has an involution $j$ whose centralizer $C(j)$ is isomorphic to a
    fixed group $C$, then $G$ is either one of the previously known simple
    groups or (say) a group determined to within isomorphism whose order and
    character table are both known. The existence or non-existence of this
    hypothetical new simple group then has to be decided. In most of the cases
    which have arisen, the existence of the new group has been checked with the
    aid of a computer.

    An involution in $G$ is called a central involution if it is contained in
    the centre of some Sylow 2-subgroup of $G$. Every non-cyclic simple group
    contains some central involution, and the characterizations of simple groups
    are often carried out in terms of centralizers of central involutions.

    Five sporadic simple groups, denoted by _Ja_, _HaJ_, _HJM_, _HHM_, _LyS_
    have been discovered by these methods. Janko #bib-ref("bib329-119")
    characterized simple groups with a central involution $j$ such that $C(j)$
    is isomorphic to $C_(2) times A_(5)$, and showed that there is at most one
    such simple group and that its order must be 175560. He also succeeded in
    constructing such a group as a subgroup of the orthogonal group $O_(7)(11)$.
    This group is denoted by _Ja_. It is known that _Ja_ is a subgroup of the
    Chevalley group $G_(2)(11)$ (Janko #bib-ref("bib329-119")).

    Janko then considered simple groups with a central involution $j$ such that
    $C(j)$ is an extension of a group of order $2^(5)$ by $A_(5)$. He showed
    that
    #source(319, "306")
    there are at most two such groups, of orders 604,800 and 50,232,960 but did
    not prove their existence. The existence of the smaller group, denoted by
    _HaJ_, was proved by M. Hall using a computer, although it can now be
    described by other methods. The existence of the larger group, called _HJM_,
    was proved by G. Higman and McKay, also using a computer.

    The existence of a further sporadic simple group was predicted by Held. Let
    $G_(0)=P S L_(5)(2)$ and $j_(0)$ be the involution $x_(r)(1)$ in $G_(0)$,
    where $r$ is some root. Let $C$ be the centralizer of $j_(0)$ in $G_(0)$.
    Held investigated simple groups $G$ with an involution $j$ such that $C(j)$
    is isomorphic to $C$, and was able to show that there are at most three such
    groups. The first is $P S L_(5)(2)$, the second is $M_(24)$, and the third
    would be a sporadic group of order 4,030,387,200. Held did not prove the
    existence of this third group, denoted by $H H M$, but this was later
    checked by G. Higman and McKay by computer.

    Lyons has recently investigated simple groups in which there is a central
    involution $j$ whose centralizer $C(j)$ is a non-split central extension of
    $C_(2)$ by $A_(11)$. There is at most one such group, of order

    $ 51,765,179,004,000,000, $ <eq:16-2-lyons-order>

    and its existence has recently been proved by Sims using a computer. This
    group is denoted by _LyS_.

  ]

  #[
    #import "main-defs.typ": bib-ref, book-ref, source

    == Towers of Permutation Groups <sec:permutation-group-towers>

    A further method of constructing sporadic simple groups was suggested by a
    property of the group _HaJ_. This group, whose existence had been
    conjectured by Janko, was exhibited by M. Hall as a transitive permutation
    group of degree 100. The stabilizer of one symbol is a simple subgroup
    isomorphic to $P S U_(3)(3^(2))$, and this subgroup has three orbits in the
    given representation of degrees 1, 36, 63. Thus _HaJ_ can be obtained as a
    permutation group by taking two permutational representations of
    $P S U_(3)(3^(2))$, adjoining one additional point, and enlarging the group
    to a transitive extension on the resulting set of 100 elements.

    The question then arose as to whether a similar procedure could be adopted
    beginning with two permutational representations of some other classical
    group. If $G$ is a group operating transitively on two sets $A_(1)$,
    $A_(2)$, we introduce an additional element $overline(a)$ and seek to
    construct a transitive extension $tilde(G)$ of $G$ on
    $overline(A)=A_(1) union A_(2) union \{overline(a)\}$. Such a transitive
    extension is usually found, when it exists, as a group of automorphisms of a
    #source(320, "307")
    graph with the elements of $overline(A)$ as vertices. The problem thus
    becomes to construct a graph with vertex set $overline(A)$ on which $G$
    operates as a group of automorphisms, such that the full automorphism group
    of the graph is transitive on $overline(A)$. This can be done in a number of
    special cases to give further sporadic simple groups.

    The first new group to be discovered by this method was obtained by D.
    Higman and C. Sims. They started with the Mathieu group $M_(22)$, taking the
    two transitive permutational representations of degrees 22, 77 obtained from
    the 22 points and 77 blocks of the Steiner system $S(3, 6, 22)$. Adding one
    additional point, they showed that $M_(22)$ could be extended to a group
    _HiS_ operating transitively on these 100 symbols. _HiS_ is a simple group
    of order 44,352,000.

    A similar construction was carried out by McLaughlin starting from the group
    $P S U_(4)(3^(2))$. He took two permutational representations of this group
    of degrees 112 and 162. The representation of degree 112 is obtained from
    the operation of $P S U_(4)(3^(2))$ on the 112 isotropic lines on the
    ‘Hermitian quadric’ in 3-dimensional projective space over $G F(3^(2))$ left
    invariant by $P S U_(4)(3^(2))$. The representation of degree 162 is
    obtained from the fact that $P S U_(4)(3^(2))$ contains a subgroup
    $P S L_(3)(4)$ of index 162. Taking these two representations together and
    adding an extra point we obtain an intransitive representation of
    $P S U_(4)(3^(2))$ of degree 275. It is possible, by constructing a suitable
    graph with these vertices, to find a transitive extension $M c L$. $M c L$
    turns out to be a simple group of order 898,128,000.

    The next group of this type was obtained by Suzuki, beginning with
    $G_(2)(4)$. This group has permutational representations of degree 416
    and 1365. The stabilizer of a symbol in the first representation is
    isomorphic to _HaJ_ and the stabilizer of a symbol in the second
    representation is the centralizer of the centre of a Sylow 2-subgroup of
    $G_(2)(4)$. Adding one extra point we obtain an intransitive representation
    of degree 1782, and by constructing a suitable graph with this vertex set
    the existence of a transitive extension can be proved. This is a simple
    group, denoted by _Suz_, of order 448,345,497,600.

  ]

  #[
    #import "main-defs.typ": bib-ref, book-ref, source

    == The Leech Lattice <sec:leech-lattice>

    We mention next three sporadic simple groups discovered by Conway. These can
    be described as groups of isometries of positive definite quadratic forms
    over the integers. Let $ZZ^n$ be a free Abelian group of rank $n$.
    #source(321, "308")
    A positive definite quadratic form of degree $n$ over $ZZ$ is a map
    $Q: ZZ^n -> ZZ$ given by

    $ Q(x_1,dots.c,x_n)=sum_(i,j) a_(i j) x_i x_j, $ <eq:16-4-quadratic-form>

    where $a_(i j) in ZZ$ and $a_(j i)=a_(i j)$, such that $Q(x) >= 0$ for all
    $x in ZZ^n$ and $Q(x)=0$ only if $x=0$. The group $ZZ^n$ together with the
    map $Q:ZZ^n -> ZZ$ is called a lattice.

    We restrict attention to positive definite integral quadratic forms with two
    further properties. We assume $Q$ is unimodular, i.e. det $(a_(i j))=1$, and
    that $Q$ is even, i.e. $Q(x)$ is an even integer for all $x$. It is known
    that there is an even unimodular, positive definite $ZZ$-form of degree $n$
    if and only if $n$ is divisible by 8 (cf. O’Meara #bib-ref("bib331-155")).
    If $n=8$ there is, to within isomorphism, just one such form. If $n=16$
    there are two such forms. If $n=24$ the forms of this type have recently
    been classified by Niemeier #bib-ref("bib331-154"). There are twenty-four
    such forms. One of them is distinguished from all the others by the fact
    that there is no $x$ for which $Q(x)=2$. The corresponding lattice was
    discovered independently by Leech, as the set of centres of spheres in a
    sphere-packing of greatest density in twenty-four dimensions #bib-ref(
      "bib330-135",
    ). It is called the Leech lattice. Let $G$ be the group of integral
    unimodular matrices which are isometries of this form. The centre $Z$ of $G$
    consists of the two elements $plus.minus I$, and $G slash Z$ can be shown to
    be a simple group. It was first investigated by Conway and its simplicity
    was proved by Thompson. It is denoted by $C o_1$ and its order is

    $ "4,157,776,806,543,360,000". $ <eq:16-4-co1-order>

    Since $G$ is represented geometrically as the group of automorphisms of the
    Leech lattice, subgroups of $G$ can readily be obtained as stabilizers of
    sublattices. Consider the set of points $x in ZZ^(24)$ such that $Q(x)=4$.
    These points are permuted transitively by $G$. The stabilizer of such a
    point in $G$ can also be shown to be a simple group. This group is denoted
    by $C o_(2)$ and its order is 42,305,421,312,000.

    We next consider points $x in ZZ^(24)$ such that $Q(x)=6$. These points are
    also permuted transitively by $G$, and the stabilizer of one of them is also
    a simple group. It is denoted by $C o_(3)$ and its order is 495,766,656,000.

    In addition to the three new sporadic simple groups $C o_(1)$, $C o_(2)$,
    $C o_(3)$ arising from $G$, several of the other sporadic groups occur in
    $G$ as stabilizers of sublattices or as composition factors of such
    stabilizers. The groups _HiS_ and _McL_ and all five Mathieu groups can be
    obtained in this way. A sixfold central extension of _Suz_ also occurs
    inside $G$, although not (so far as is known) as the stabilizer of a
    sublattice.

  ]

  #[
    #import "main-defs.typ": bib-ref, book-ref, source

    #source(322, "309")
    #heading(level: 2)[
      Groups Generated by a Class of 3-Transpositions
    ] <sec:three-transposition-groups>

    We conclude by describing three further sporadic simple groups discovered by
    B. Fischer #bib-ref("bib327-78"). Fischer investigated groups generated by a
    class of conjugate involutions such that the product of two distinct
    involutions in the class has order 2 or 3. Such a conjugacy class of
    involutions is called by Fischer a class of 3-transpositions. For example,
    each symmetric group is generated in this way by its class of
    transpositions. More generally, the Weyl groups of type
    $A_(l), D_(l), E_(6), E_(7), E_(8)$ are generated in this way by their
    classes of reflections. In addition certain classical groups over very small
    fields are also generated in this way. The symplectic groups $S p_(2l)(2)$
    are generated in this way by the class of symplectic transvections, the
    orthogonal groups $O_(2l)^+(2),O_(2l)^-(2)$ by orthogonal transvections and
    the unitary groups $P S U_(n)(2^2)$ by unitary transvections. Moreover, in
    the orthogonal groups $O_(2l)^+(3),O_(2l)^-(3),O_(2l+1)(3)$ the reflections
    corresponding to the elements $a$ satisfying $(a, a)=1$ form a class of
    3-transpositions in the subgroup they generate, and so do the reflections
    corresponding to the elements satisfying $(a, a)=-1$.

    Fischer considered finite groups $G$ generated by a class of
    3-transpositions which satisfy the further conditions:

    #enum(
      numbering: "(i)",
      [Every normal subgroup of $G$ of order a power of 2 or a power of 3 lies
        in the centre of $G$.],
      [The derived group $G'$ of $G$ is its own derived group, viz., $G'=G''$.],
    )

    He showed that if $G$ is such a group with centre $Z(G)$ then $G slash Z(G)$
    is isomorphic to either a symmetric group, or one of the classical groups
    mentioned above (factored by the centre in the case of the groups over
    $G F(3)$), or one of three further groups which we shall denote by
    $F i_(22)$, $F i_(23)$, $F i_(24)$. Moreover, there is just one class of
    3-transpositions generating each of these groups, except in the group
    $S_(6) approx.eq S p_(4)(2) approx.eq P O_(4)^(-)(3)$ which has two such
    classes. We observe that the Weyl groups of type $E_(6)$, $E_(7)$, $E_(8)$
    are included in this classification in view of the isomorphisms

    $
              W(E_6) & approx.eq O_6^-(2), \
      W(E_7) slash Z & approx.eq S p_6(2), \
      W(E_8) slash Z & approx.eq O_8^+(2).
    $ <eq:16-5-weyl-isomorphisms>

    In what follows we replace $G$ by its central quotient $G slash Z(G)$, again
    denoted by $G$.

    If $d$ is an element in the class of 3-transpositions of $G$ it is shown in
    Fischer #bib-ref("bib327-78") that the set $D_(d)$ of elements of this class
    distinct from $d$ but commuting with it forms a conjugacy class of
    3-transpositions in the group it generates. Thus the classification of
    groups generated by 3-transpositions proceeds by induction. In particular
    Fischer is able to show
    #source(323, "310")
    that if the group $chevron.l D_d chevron.r slash Z chevron.l D_d chevron.r$
    is a symmetric group or a classical group not isomorphic to $P S U_6(2^2)$
    then $G$ is either a symmetric group or one of the classical groups
    described above. If
    $chevron.l D_d chevron.r slash Z chevron.l D_d chevron.r$ is isomorphic to
    $P S U_6(2^2)$ then the class $D$ has 3510 elements and $G$ is shown to be a
    simple group $F i_(22)$ of order
    $2^(17) dot 3^9 dot 5^2 dot 7 dot 11 dot 13$. A maximal commuting subset $L$
    of $D$ has twenty-two elements and the group
    $cal(N)_G (L) slash chevron.l L chevron.r$ of permutations induced by $G$ on
    $L$ is isomorphic to the Mathieu group $M_(22)$.

    If $chevron.l D_d chevron.r slash Z chevron.l D_d chevron.r$ is isomorphic
    to $F i_(22)$ then the class $D$ has 31,671 elements and $G$ is a simple
    group $F i_(23)$ of order
    $2^(18) dot 3^(13) dot 5^(2) dot 7 dot 11 dot 13 dot 17 dot 23$. A maximal
    commuting subset $L$ of $D$ has twenty-three elements and the group
    $cal(N)_G (L) slash chevron.l L chevron.r$ of permutations induced by $G$ on
    $L$ is isomorphic to the Mathieu group $M_(23)$.

    If $chevron.l D_d chevron.r slash Z chevron.l D_d chevron.r$ is isomorphic
    to $F i_(23)$ then the class $D$ has 306,936 elements and $G$ is a group
    $F i_(24)$ of order
    $2^22 dot 3^16 dot 5^2 dot 7^3 dot 11 dot 13 dot 17 dot 23 dot 29$.
    $F i_(24)$ is not simple, but contains a simple subgroup $F i'_(24)$ of
    index 2. A maximal commuting subset $L$ of $D$ has twenty-four elements and
    the group $cal(N)_G (L) slash chevron.l L chevron.r$ of permutations induced
    by $G$ on $L$ is isomorphic to the Mathieu group $M_(24)$.

    Finally it can be shown that there can be no group $G$ in which
    $chevron.l D_d chevron.r slash Z chevron.l D_d chevron.r$ is isomorphic to
    $F i_(24)$.

    We conclude our brief survey of the sporadic simple groups with a table
    comparing their orders.


    #block(breakable: false)[
      #set text(size: 11pt)
      #table(
        columns: (auto, auto, 1fr),
        column-gutter: 0.75em,
        row-gutter: 0.35em,
        inset: 0pt,
        stroke: none,
        [$M_(11)$], [$2^(4) dot 3^(2) dot 5 dot 11$], [Mathieu],
        [$M_(12)$], [$2^(6) dot 3^(3) dot 5 dot 11$], [Mathieu],
        [$M_(22)$], [$2^(7) dot 3^(2) dot 5 dot 7 dot 11$], [Mathieu],
        [$M_(23)$], [$2^(7) dot 3^(2) dot 5 dot 7 dot 11 dot 23$], [Mathieu],
        [$M_(24)$], [$2^(10) dot 3^(3) dot 5 dot 7 dot 11 dot 23$], [Mathieu],
        [_Ja_], [$2^(3) dot 3 dot 5 dot 7 dot 11 dot 19$], [Janko],
        [_HaJ_], [$2^(7) dot 3^(3) dot 5^(2) dot 7$], [M. Hall, Janko],
        [_HJM_],
        [$2^(7) dot 3^(5) dot 5 dot 17 dot 19$],
        [G. Higman, Janko, McKay],

        [_HiS_], [$2^(9) dot 3^(2) dot 5^(3) dot 7 dot 11$], [D. Higman, Sims],
        [_McL_], [$2^(7) dot 3^(6) dot 5^(3) dot 7 dot 11$], [McLaughlin],
        [_Suz_], [$2^(13) dot 3^(7) dot 5^(2) dot 7 dot 11 dot 13$], [Suzuki],
        [_HHM_],
        [$2^(10) dot 3^(3) dot 5^(2) dot 7^(3) dot 17$],
        [Held, G. Higman, McKay],

        [$C o_(1)$],
        [$2^(21) dot 3^(9) dot 5^(4) dot 7^(2) dot 11 dot 13 dot 23$],
        [Conway, Thompson],

        [$C o_(2)$],
        [$2^(18) dot 3^(6) dot 5^(3) dot 7 dot 11 dot 23$],
        [Conway, Thompson],

        [$C o_(3)$],
        [$2^(10) dot 3^(7) dot 5^(3) dot 7 dot 11 dot 23$],
        [Conway, Thompson],

        [$F i_(22)$], [$2^17 dot 3^9 dot 5^2 dot 7 dot 11 dot 13$], [Fischer],
        [$F i_(23)$],
        [$2^(18) dot 3^(13) dot 5^(2) dot 7 dot 11 dot 13 dot 17 dot 23$],
        [Fischer],

        [$F i'_24$],
        [$2^21 dot 3^16 dot 5^2 dot 7^3 dot 11 dot 13 dot 17 dot 23 dot 29$],
        [Fischer],

        [_LyS_],
        [$2^(8) dot 3^(7) dot 5^(6) dot 7 dot 11 dot 31 dot 37 dot 67$],
        [Lyons, Sims],
      )
    ] <fig:16-sporadic-orders>
  ]
]

// Preview this file in the context of the complete book.
#context { include "main.typ" }
