#import "main-defs.typ": index-ref, source
#let tw(i, body) = math.attach(body, tl: i)

= Index of Notation <sec:notation-index>

#set par(first-line-indent: 0pt, justify: false, leading: 0.55em)
#set text(size: 11pt)
#table(
  columns: (28mm, 1fr, 17mm),
  column-gutter: 2mm,
  row-gutter: 0.6em,
  inset: 0pt,
  stroke: none,
  align: (left, left, right),
  table.header([_Symbol_], [_Meaning_], [_Page of definition_]),
  [#metadata((kind: "index-entry", id: "notation-001", original: ()))#source(
      336,
      "323",
    )$bar.v thin bar.v$],
  [The order of a group],
  [—],

  [#metadata((
      kind: "index-entry",
      id: "notation-002",
      original: (),
    ))$chevron.l dots chevron.r$],
  [The group generated by a given set of elements],
  [—],

  [#metadata((kind: "index-entry", id: "notation-003", original: ()))$perp$],
  [The orthogonal subspace of a given subspace],
  [—],

  [#metadata((
      kind: "index-entry",
      id: "notation-004",
      original: ((148, 148),),
    ))$A$],
  [The rational group algebra of $e(Q)$],
  [#index-ref(148, target: "def:rational-group-algebra")],

  [#metadata((
      kind: "index-entry",
      id: "notation-005",
      original: ((43, 43),),
    ))$A_l$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-006",
      original: ((64, 64),),
    ))$A_l (K)$],
  [The Chevalley group of type $A_l$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-007",
      original: ((121, 121),),
    ))$A_l (q)$],
  [The Chevalley group of type $A_l$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-008",
      original: ((251, 251),),
    ))$tw(2, A_l)(K)$],
  [The twisted group of type $A_l$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-009",
      original: ((251, 251),),
    ))$tw(2, A_l)(q^2)$],
  [The twisted group of type $A_l$ over $G F(q^2)$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-010",
      original: ((38, 38),),
    ))$A_(r s)$],
  [The Cartan integer associated with a pair of roots],
  [#index-ref(38, target: "def:cartan-integer")],

  [#metadata((
      kind: "index-entry",
      id: "notation-011",
      original: ((34, 34),),
    ))$op("ad") x$],
  [The adjoint map of left multiplication by the element $x$ in a Lie algebra],
  [#index-ref(34)],

  [#metadata((
      kind: "index-entry",
      id: "notation-012",
      original: ((104, 104),),
    ))$B$],
  [The subgroup $U H$ of a Chevalley group],
  [#index-ref(104)],

  [#metadata((
      kind: "index-entry",
      id: "notation-013",
      original: ((230, 230),),
    ))$B^1$],
  [The subgroup $B inter G^1$ of a twisted group $G^1$],
  [#index-ref(230)],

  [#metadata((
      kind: "index-entry",
      id: "notation-014",
      original: ((43, 43),),
    ))$B_l$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-015",
      original: ((64, 64),),
    ))$B_l (K)$],
  [The Chevalley group of type $B_l$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-016",
      original: ((121, 121),),
    ))$B_l (q)$],
  [The Chevalley group of type $B_l$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-017",
      original: ((251, 251),),
    ))$tw(2, B_2)(K)$],
  [The twisted Suzuki group of type $B_2$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-018",
      original: ((251, 251),),
    ))$tw(2, B_2)(2^(2m+1))$],
  [The twisted Suzuki group of type $B_2$ over $G F(2^(2m+1))$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-019",
      original: ((34, 34),),
    ))$CC$],
  [The complex field],
  [#index-ref(34)],

  [#metadata((
      kind: "index-entry",
      id: "notation-020",
      original: ((21, 21),),
    ))$C$],
  [A chamber],
  [#index-ref(21)],

  [#metadata((
      kind: "index-entry",
      id: "notation-021",
      original: ((31, 31),),
    ))$C_J$],
  [The element of the Coxeter complex associated with a set $J$ of fundamental
    roots],
  [#index-ref(31, target: "def:fundamental-faces")],

  [#metadata((
      kind: "index-entry",
      id: "notation-022",
      original: ((77, 77),),
    ))$C_(i j r s)$],
  [The constants occurring in Chevalley’s commutator formula],
  [#index-ref(77)],

  [#metadata((
      kind: "index-entry",
      id: "notation-023",
      original: ((43, 43),),
    ))$C_l$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-024",
      original: ((64, 64),),
    ))$C_l (K)$],
  [The Chevalley group of type $C_l$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-025",
      original: ((121, 121),),
    ))$C_l (q)$],
  [The Chevalley group of type $C_l$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-026",
      original: ((29, 29),),
    ))$D_J$],
  [The set of distinguished coset representatives of $W_J$ in $W$],
  [#index-ref(29)],

  [#metadata((
      kind: "index-entry",
      id: "notation-027",
      original: ((130, 130),),
    ))$d_1,dots,d_l$],
  [The degrees of the basic polynomial invariants of $W$],
  [#index-ref(130)],

  [#metadata((
      kind: "index-entry",
      id: "notation-028",
      original: ((43, 43),),
    ))$D_l$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-029",
      original: ((64, 64),),
    ))$D_l (K)$],
  [The Chevalley group of type $D_l$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-030",
      original: ((121, 121),),
    ))$D_l (q)$],
  [The Chevalley group of type $D_l$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-031",
      original: ((251, 251),),
    ))$tw(2, D_l)(K)$],
  [The twisted orthogonal group of type $D_l$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-032",
      original: ((251, 251),),
    ))#source(337, "324")$tw(2, D_l)(q^2)$],
  [The twisted orthogonal group of type $D_l$ over $G F(q^2)$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-033",
      original: ((251, 251),),
    ))$tw(3, D_4)(K)$],
  [The triality twisted group of type $D_4$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-034",
      original: ((251, 251),),
    ))$tw(3, D_4)(q^3)$],
  [The triality twisted group of type $D_4$ over $G F(q^3)$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-035",
      original: ((51, 51),),
    ))$e_r$],
  [A root vector in a simple Lie algebra],
  [#index-ref(51)],

  [#metadata((
      kind: "index-entry",
      id: "notation-036",
      original: ((148, 148),),
    ))$e(Q)$],
  [A multiplicative group isomorphic to the additive group $Q$],
  [#index-ref(148, target: "def:multiplicative-weights")],

  [#metadata((
      kind: "index-entry",
      id: "notation-037",
      original: ((43, 43),),
    ))$E_6$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-038",
      original: ((64, 64),),
    ))$E_6(K)$],
  [The Chevalley group of type $E_6$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-039",
      original: ((121, 121),),
    ))$E_6(q)$],
  [The Chevalley group of type $E_6$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-040",
      original: ((251, 251),),
    ))$tw(2, E_6)(K)$],
  [The twisted group of type $E_6$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-041",
      original: ((251, 251),),
    ))$tw(2, E_6)(q^2)$],
  [The twisted group of type $E_6$ over $G F(q^2)$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-042",
      original: ((43, 43),),
    ))$E_7$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-043",
      original: ((64, 64),),
    ))$E_7(K)$],
  [The Chevalley group of type $E_7$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-044",
      original: ((121, 121),),
    ))$E_7(q)$],
  [The Chevalley group of type $E_7$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-045",
      original: ((43, 43),),
    ))$E_8$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-046",
      original: ((64, 64),),
    ))$E_8(K)$],
  [The Chevalley group of type $E_8$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-047",
      original: ((121, 121),),
    ))$E_8(q)$],
  [The Chevalley group of type $E_8$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-048",
      original: ((43, 43),),
    ))$F_4$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-049",
      original: ((64, 64),),
    ))$F_4(K)$],
  [The Chevalley group of type $F_4$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-050",
      original: ((121, 121),),
    ))$F_4(q)$],
  [The Chevalley group of type $F_4$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-051",
      original: ((251, 251),),
    ))$tw(2, F_4)(K)$],
  [The twisted Ree group of type $F_4$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-052",
      original: ((251, 251),),
    ))$tw(2, F_4)(2^(2m+1))$],
  [The twisted Ree group of type $F_4$ over $G F(2^(2m+1))$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-053",
      original: ((68, 68),),
    ))$G$],
  [A group, usually a Chevalley group],
  [#index-ref(68)],

  [#metadata((
      kind: "index-entry",
      id: "notation-054",
      original: ((190, 190),),
    ))$overline(G)$],
  [The universal Chevalley group associated with $G$],
  [#index-ref(190)],

  [#metadata((
      kind: "index-entry",
      id: "notation-055",
      original: ((118, 118),),
    ))$hat(G)$],
  [The extension of $G$ by its group of diagonal automorphisms],
  [#index-ref(118)],

  [#metadata((
      kind: "index-entry",
      id: "notation-056",
      original: ((170, 170),),
    ))$G'$],
  [The commutator subgroup (derived group) of $G$],
  [#index-ref(170)],

  [#metadata((
      kind: "index-entry",
      id: "notation-057",
      original: ((226, 226),),
    ))$G^1$],
  [A twisted group],
  [#index-ref(226, target: "def:13-4-2")],

  [#metadata((
      kind: "index-entry",
      id: "notation-058",
      original: ((43, 43),),
    ))$G_2$],
  [The type of a simple Lie algebra over $CC$],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-059",
      original: ((64, 64),),
    ))$G_2(K)$],
  [The Chevalley group of type $G_2$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-060",
      original: ((121, 121),),
    ))$G_2(q)$],
  [The Chevalley group of type $G_2$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-061",
      original: ((251, 251),),
    ))$tw(2, G_2)(K)$],
  [The twisted Ree group of type $G_2$ over $K$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-062",
      original: ((251, 251),),
    ))$tw(2, G_2)(3^(2m+1))$],
  [The twisted Ree group of type $G_2$ over $G F(3^(2m+1))$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-063",
      original: ((2, 2),),
    ))$G F(q)$],
  [The Galois field with $q$ elements],
  [#index-ref(2)],

  [#metadata((
      kind: "index-entry",
      id: "notation-064",
      original: ((2, 2),),
    ))$G L_n (K)$],
  [The general linear group of degree $n$ over $K$],
  [#index-ref(2)],

  [#metadata((
      kind: "index-entry",
      id: "notation-065",
      original: ((97, 97),),
    ))$H$],
  [The diagonal subgroup of a Chevalley group $G$],
  [#index-ref(97)],

  [#metadata((
      kind: "index-entry",
      id: "notation-066",
      original: ((35, 35),),
    ))$frak(H)$],
  [A Cartan subalgebra of a simple Lie algebra],
  [#index-ref(35)],

  [#metadata((
      kind: "index-entry",
      id: "notation-067",
      original: ((42, 42),),
    ))$h_r$],
  [The co-root associated to a root $r$],
  [#index-ref(42)],

  [#metadata((
      kind: "index-entry",
      id: "notation-068",
      original: ((83, 83),),
    ))$frak(H)_r$],
  [The 1-dimensional subspace of $frak(H)$ containing $h_r$],
  [#index-ref(83)],

  [#metadata((
      kind: "index-entry",
      id: "notation-069",
      original: ((20, 20),),
    ))$H_r$],
  [The hyperplane orthogonal to a root $r$],
  [#index-ref(20)],

  [#metadata((
      kind: "index-entry",
      id: "notation-070",
      original: ((98, 98),),
    ))$h(chi)$],
  [The automorphism of the Lie algebra $frak(L)_K$ determined by a $K$-character
    $chi$ of $P$],
  [#index-ref(98, target: "def:character-automorphism")],

  [#metadata((
      kind: "index-entry",
      id: "notation-071",
      original: ((98, 98),),
    ))$hat(H)$],
  [The group of automorphisms $h(chi)$ of $frak(L)_K$],
  [#index-ref(98)],

  [#metadata((
      kind: "index-entry",
      id: "notation-072",
      original: ((92, 92),),
    ))$h_r (lambda)$],
  [The element of $H$ associated with a root $r$ and an element $lambda$ of
    $K$],
  [#index-ref(92)],

  [#metadata((
      kind: "index-entry",
      id: "notation-073",
      original: ((16, 16),),
    ))#source(338, "325")$h(r)$],
  [The height of a root $r$],
  [#index-ref(16)],

  [#metadata((
      kind: "index-entry",
      id: "notation-074",
      original: ((226, 226),),
    ))$H^1$],
  [The diagonal subgroup $H inter G^1$ of a twisted group $G^1$],
  [#index-ref(226)],

  [#metadata((
      kind: "index-entry",
      id: "notation-075",
      original: ((124, 124),),
    ))$frak(I)$],
  [The ring of polynomial invariants of a Weyl group $W$],
  [#index-ref(124, target: "def:invariant-ring")],

  [#metadata((
      kind: "index-entry",
      id: "notation-076",
      original: ((125, 125),),
    ))$frak(I)^+$],
  [The set of polynomials in $frak(I)$ with no constant term],
  [#index-ref(125)],

  [#metadata((
      kind: "index-entry",
      id: "notation-077",
      original: ((132, 132),),
    ))$frak(I)_n$],
  [The set of homogeneous polynomials in $frak(I)$ of degree $n$],
  [#index-ref(132)],

  [#metadata((
      kind: "index-entry",
      id: "notation-078",
      original: ((126, 126),),
    ))$I_1,dots,I_l$],
  [A set of basic polynomial invariants of the Weyl group $W$],
  [#index-ref(126)],

  [#metadata((
      kind: "index-entry",
      id: "notation-079",
      original: ((139, 139),),
    ))$hat(frak(I))$],
  [The set of alternating polynomials on $frak(V)$],
  [#index-ref(139)],

  [#metadata((
      kind: "index-entry",
      id: "notation-080",
      original: ((140, 140),),
    ))$hat(frak(I))_n$],
  [The set of homogeneous alternating polynomials of degree $n$],
  [#index-ref(140)],

  [#metadata((
      kind: "index-entry",
      id: "notation-081",
      original: ((140, 140),),
    ))$frak(I)_J$],
  [The set of polynomials on $frak(V)$ invariant under $W_J$],
  [#index-ref(140)],

  [#metadata((
      kind: "index-entry",
      id: "notation-082",
      original: ((140, 140),),
    ))$(frak(I)_J)_n$],
  [The set of homogeneous polynomials in $frak(I)_J$ of degree $n$],
  [#index-ref(140)],

  [#metadata((
      kind: "index-entry",
      id: "notation-083",
      original: ((27, 27),),
    ))$J$],
  [A subset of the set $Pi$ of fundamental roots],
  [#index-ref(27)],

  [#metadata((
      kind: "index-entry",
      id: "notation-084",
      original: ((2, 2),),
    ))$K$],
  [A field],
  [#index-ref(2)],

  [#metadata((
      kind: "index-entry",
      id: "notation-085",
      original: ((97, 97),),
    ))$K^*$],
  [The multiplicative group of non-zero elements of $K$],
  [#index-ref(97)],

  [#metadata((
      kind: "index-entry",
      id: "notation-086",
      original: ((35, 35),),
    ))$l$],
  [The rank of a simple Lie algebra],
  [#index-ref(35)],

  [#metadata((
      kind: "index-entry",
      id: "notation-087",
      original: ((18, 18),),
    ))$l(w)$],
  [The length of an element $w$ of the Weyl group],
  [#index-ref(18)],

  [#metadata((
      kind: "index-entry",
      id: "notation-088",
      original: ((33, 33),),
    ))$frak(L)$],
  [A Lie algebra, usually simple over $CC$],
  [#index-ref(33)],

  [#metadata((
      kind: "index-entry",
      id: "notation-089",
      original: ((36, 36),),
    ))$frak(L)_r$],
  [The 1-dimensional subspace of $frak(L)$ corresponding to the root $r$],
  [#index-ref(36)],

  [#metadata((
      kind: "index-entry",
      id: "notation-090",
      original: ((62, 62),),
    ))$frak(L)_K$],
  [The Lie algebra over $K$ constructed from the simple Lie algebra $frak(L)$
    over $CC$],
  [#index-ref(62, target: "def:lie-algebra-base-change")],

  [#metadata((
      kind: "index-entry",
      id: "notation-091",
      original: ((64, 64),),
    ))$frak(L)(K)$],
  [The Chevalley group of type $frak(L)$ over $K$],
  [#index-ref(64, target: "def:chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-092",
      original: ((121, 121),),
    ))$frak(L)(q)$],
  [The Chevalley group of type $frak(L)$ over $G F(q)$],
  [#index-ref(121, target: "def:finite-chevalley-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-093",
      original: ((251, 251),),
    ))$tw(i, frak(L))(K)$],
  [The twisted group constructed from a Chevalley group $frak(L)(K)$ by means of
    a symmetry of order $i$],
  [#index-ref(251, target: "def:twisted-group-notation")],

  [#metadata((
      kind: "index-entry",
      id: "notation-094",
      original: ((119, 119),),
    ))$L_J$],
  [A Levi subgroup of a parabolic subgroup $P_J$],
  [#index-ref(119)],

  [#metadata((
      kind: "index-entry",
      id: "notation-095",
      original: ((61, 61),),
    ))$M_(r,s,i)$],
  [The integer $1/(i!) N_(r,s) N_(r,r+s) dots N_(r,(i-1)r+s)$],
  [#index-ref(61)],

  [#metadata((
      kind: "index-entry",
      id: "notation-096",
      original: ((155, 155),),
    ))$m_1,dots,m_l$],
  [The exponents of the Weyl group],
  [#index-ref(155)],

  [#metadata((
      kind: "index-entry",
      id: "notation-097",
      original: ((43, 43),),
    ))$N$],
  [The number of positive roots],
  [#index-ref(43, target: "fig:3-6-standard-list")],

  [#metadata((
      kind: "index-entry",
      id: "notation-098",
      original: ((101, 101),),
    ))$N$],
  [The monomial subgroup of a Chevalley group $G$],
  [#index-ref(101)],

  [#metadata((
      kind: "index-entry",
      id: "notation-099",
      original: ((52, 52),),
    ))$N_(r,s)$],
  [The structure constant of a simple Lie algebra determined by a pair of
    roots],
  [#index-ref(52)],

  [#metadata((
      kind: "index-entry",
      id: "notation-100",
      original: ((108, 108),),
    ))$N_J$],
  [The inverse image in $N$ of the subgroup $W_J$ of $W$],
  [#index-ref(108)],

  [#metadata((
      kind: "index-entry",
      id: "notation-101",
      original: ((115, 115),),
    ))$n_w$],
  [An element of $N$ mapping to $w$ in $W$],
  [#index-ref(115)],

  [#metadata((
      kind: "index-entry",
      id: "notation-102",
      original: ((93, 93),),
    ))$n_r$],
  [The generator $x_r (1)x_(-r)(-1)x_r (1)$ of $N$],
  [#index-ref(93)],

  [#metadata((
      kind: "index-entry",
      id: "notation-103",
      original: ((96, 96),),
    ))$n_r (t)$],
  [The element $x_r (t)x_(-r)(-t^(-1))x_r (t)$ of $N$],
  [#index-ref(96)],

  [#metadata((
      kind: "index-entry",
      id: "notation-104",
      original: ((136, 136),),
    ))$n_J (w)$],
  [The number of elements fixed by $w$ in the $W$-orbit containing $C_J$ of the
    Coxeter complex],
  [#index-ref(136)],

  [#metadata((
      kind: "index-entry",
      id: "notation-105",
      original: ((226, 226),),
    ))$N^1$],
  [The monomial subgroup $N inter G^1$ of a twisted group $G^1$],
  [#index-ref(226)],

  [#metadata((
      kind: "index-entry",
      id: "notation-106",
      original: ((254, 254),),
    ))$O_J$],
  [The number of $rho$-orbits in a $rho$-invariant set $J$ of fundamental
    roots],
  [#index-ref(254)],

  [#metadata((
      kind: "index-entry",
      id: "notation-107",
      original: ((4, 4),),
    ))$O_n (K,f)$],
  [The orthogonal group of degree $n$ over $K$ leaving invariant the quadratic
    form $f$],
  [#index-ref(4)],

  [#metadata((
      kind: "index-entry",
      id: "notation-108",
      original: ((6, 6),),
    ))#source(339, "326")$O_(2l)^+(q)$],
  [The orthogonal group of degree $2l$ over $G F(q)$ leaving invariant a
    quadratic form of index $l$],
  [#index-ref(6)],

  [#metadata((
      kind: "index-entry",
      id: "notation-109",
      original: ((6, 6),),
    ))$O_(2l)^-(q)$],
  [The orthogonal group of degree $2l$ over $G F(q)$ leaving invariant a
    quadratic form of index $l-1$],
  [#index-ref(6)],

  [#metadata((
      kind: "index-entry",
      id: "notation-110",
      original: ((38, 38),),
    ))$p_1,dots,p_l$],
  [A system of fundamental roots],
  [#index-ref(38, target: "def:fundamental-roots")],

  [#metadata((
      kind: "index-entry",
      id: "notation-111",
      original: ((97, 97),),
    ))$P$],
  [The additive group generated by $p_1,dots,p_l$],
  [#index-ref(97)],

  [#metadata((
      kind: "index-entry",
      id: "notation-112",
      original: ((108, 108),),
    ))$P_J$],
  [The parabolic subgroup $B N_J B$ associated with a set $J$ of fundamental
    roots],
  [#index-ref(108)],

  [#metadata((
      kind: "index-entry",
      id: "notation-113",
      original: ((135, 135),),
    ))$P_W (t)$],
  [The polynomial $sum_(w in W) t^(l(w))$],
  [#index-ref(135)],

  [#metadata((
      kind: "index-entry",
      id: "notation-114",
      original: ((254, 254),),
    ))$P_(W^1)(t)$],
  [The polynomial $sum_(w in W^1) t^(l(w))$],
  [#index-ref(254)],

  [#metadata((
      kind: "index-entry",
      id: "notation-115",
      original: ((2, 2),),
    ))$P G L_n (K)$],
  [The projective general linear group of degree $n$ over $K$],
  [#index-ref(2)],

  [#metadata((
      kind: "index-entry",
      id: "notation-116",
      original: ((4, 4),),
    ))$P S p_n (K)$],
  [The projective symplectic group of degree $n$ over $K$],
  [#index-ref(4)],

  [#metadata((
      kind: "index-entry",
      id: "notation-117",
      original: ((5, 5),),
    ))$P S O_n (K,f)$],
  [The projective special orthogonal group of degree $n$ over $K$ leaving
    invariant the quadratic form $f$],
  [#index-ref(5)],

  [#metadata((
      kind: "index-entry",
      id: "notation-118",
      original: ((5, 5),),
    ))$P Omega_n (K,f)$],
  [The projective group of the commutator subgroup $Omega_n (K,f)$ of
    $O_n (K,f)$],
  [#index-ref(5)],

  [#metadata((
      kind: "index-entry",
      id: "notation-119",
      original: ((7, 7),),
    ))$P S U_n (K,f)$],
  [The projective special unitary group of degree $n$ over $K$ leaving invariant
    the Hermitian form $f$],
  [#index-ref(7)],

  [#metadata((
      kind: "index-entry",
      id: "notation-120",
      original: ((153, 153),),
    ))$QQ$],
  [The field of rationals],
  [#index-ref(153)],

  [#metadata((
      kind: "index-entry",
      id: "notation-121",
      original: ((98, 98),),
    ))$q_1,dots,q_l$],
  [The fundamental weights of a simple Lie algebra],
  [#index-ref(98)],

  [#metadata((
      kind: "index-entry",
      id: "notation-122",
      original: ((99, 99),),
    ))$Q$],
  [The additive group generated by $q_1,dots,q_l$],
  [#index-ref(99)],

  [#metadata((
      kind: "index-entry",
      id: "notation-123",
      original: ((12, 12),),
    ))$RR$],
  [The real number field],
  [#index-ref(12)],

  [#metadata((
      kind: "index-entry",
      id: "notation-124",
      original: ((156, 156),),
    ))$R$],
  [The root of maximum height],
  [#index-ref(156)],

  [#metadata((
      kind: "index-entry",
      id: "notation-125",
      original: ((145, 145),),
    ))$S$],
  [The sum of the fundamental weights],
  [#index-ref(145)],

  [#metadata((
      kind: "index-entry",
      id: "notation-126",
      original: ((227, 227),),
    ))$S$],
  [An equivalence class in $Phi$],
  [#index-ref(227)],

  [#metadata((
      kind: "index-entry",
      id: "notation-127",
      original: ((123, 123),),
    ))$frak(S)$],
  [The algebra of polynomial functions on $frak(V)$],
  [#index-ref(123)],

  [#metadata((
      kind: "index-entry",
      id: "notation-128",
      original: ((132, 132),),
    ))$frak(S)_n$],
  [The set of homogeneous polynomials in $frak(S)$ of degree $n$],
  [#index-ref(132)],

  [#metadata((
      kind: "index-entry",
      id: "notation-129",
      original: ((2, 2),),
    ))$S L_n (K)$],
  [The special linear group of degree $n$ over $K$],
  [#index-ref(2)],

  [#metadata((
      kind: "index-entry",
      id: "notation-130",
      original: ((2, 2),),
    ))$S p_n (K)$],
  [The symplectic group of degree $n$ over $K$],
  [#index-ref(2, target: "sec:symplectic-groups")],

  [#metadata((
      kind: "index-entry",
      id: "notation-131",
      original: ((5, 5),),
    ))$S O_n (K,f)$],
  [The special orthogonal group of degree $n$ over $K$ leaving invariant the
    quadratic form $f$],
  [#index-ref(5)],

  [#metadata((
      kind: "index-entry",
      id: "notation-132",
      original: ((7, 7),),
    ))$S U_n (K,f)$],
  [The special unitary group of degree $n$ over $K$ leaving invariant the
    Hermitian form $f$],
  [#index-ref(7)],

  [#metadata((
      kind: "index-entry",
      id: "notation-133",
      original: ((274, 274),),
    ))$op("St") A$],
  [The star of an element $A$ in a chamber complex],
  [#index-ref(274)],

  [#metadata((
      kind: "index-entry",
      id: "notation-134",
      original: ((68, 68),),
    ))$U$],
  [The unipotent subgroup of a Chevalley group $G$ generated by the positive
    root subgroups],
  [#index-ref(68)],

  [#metadata((
      kind: "index-entry",
      id: "notation-135",
      original: ((78, 78),),
    ))$U_m$],
  [The subgroup of $U$ generated by the root subgroups corresponding to roots of
    height at least $m$],
  [#index-ref(78)],

  [#metadata((
      kind: "index-entry",
      id: "notation-136",
      original: ((104, 104),),
    ))$U_r$],
  [The product of the root subgroups corresponding to positive roots other than
    $r$],
  [#index-ref(104)],

  [#metadata((
      kind: "index-entry",
      id: "notation-137",
      original: ((115, 115),),
    ))$U_w^+$],
  [The product of the root subgroups corresponding to positive roots transformed
    by $w$ into positive roots],
  [#index-ref(115)],

  [#metadata((
      kind: "index-entry",
      id: "notation-138",
      original: ((115, 115),),
    ))$U_w^-$],
  [The product of the root subgroups corresponding to positive roots transformed
    by $w$ into negative roots],
  [#index-ref(115)],

  [#metadata((
      kind: "index-entry",
      id: "notation-139",
      original: ((119, 119),),
    ))#source(340, "327")$U_J$],
  [The unipotent radical of the parabolic subgroup $P_J$],
  [#index-ref(119)],

  [#metadata((
      kind: "index-entry",
      id: "notation-140",
      original: ((226, 226),),
    ))$U^1$],
  [The unipotent subgroup $U inter G^1$ of a twisted group $G^1$],
  [#index-ref(226)],

  [#metadata((
      kind: "index-entry",
      id: "notation-141",
      original: ((229, 229),),
    ))$(U_w^-)^1$],
  [The subgroup $U_w^- inter G^1$ of a twisted group $G^1$],
  [#index-ref(229)],

  [#metadata((
      kind: "index-entry",
      id: "notation-142",
      original: ((7, 7),),
    ))$U_n (K,f)$],
  [The unitary group of degree $n$ over $K$ leaving invariant the Hermitian form
    $f$],
  [#index-ref(7)],

  [#metadata((
      kind: "index-entry",
      id: "notation-143",
      original: ((2, 2),),
    ))$frak(V)$],
  [A vector space],
  [#index-ref(2)],

  [#metadata((
      kind: "index-entry",
      id: "notation-144",
      original: ((27, 27),),
    ))$frak(V)_J$],
  [The subspace of $frak(V)$ spanned by a set $J$ of fundamental roots],
  [#index-ref(27)],

  [#metadata((
      kind: "index-entry",
      id: "notation-145",
      original: ((68, 68),),
    ))$V$],
  [The unipotent subgroup of a Chevalley group $G$ generated by the negative
    root subgroups],
  [#index-ref(68)],

  [#metadata((
      kind: "index-entry",
      id: "notation-146",
      original: ((105, 105),),
    ))$V_(-r)$],
  [The product of the root subgroups corresponding to negative roots other than
    $-r$],
  [#index-ref(105)],

  [#metadata((
      kind: "index-entry",
      id: "notation-147",
      original: ((123, 123),),
    ))$hat(frak(V))$],
  [The dual space of $frak(V)$],
  [#index-ref(123)],

  [#metadata((
      kind: "index-entry",
      id: "notation-148",
      original: ((217, 217),),
    ))$frak(V)^1$],
  [The set of elements of $frak(V)$ invariant under the isometry $tau$],
  [#index-ref(217)],

  [#metadata((
      kind: "index-entry",
      id: "notation-149",
      original: ((226, 226),),
    ))$V^1$],
  [The unipotent subgroup $V inter G^1$ of a twisted group $G^1$],
  [#index-ref(226)],

  [#metadata((
      kind: "index-entry",
      id: "notation-150",
      original: ((13, 13),),
    ))$W$],
  [A Weyl group],
  [#index-ref(13)],

  [#metadata((
      kind: "index-entry",
      id: "notation-151",
      original: ((12, 12),),
    ))$w_r$],
  [The reflection in the hyperplane orthogonal to the root $r$],
  [#index-ref(12)],

  [#metadata((
      kind: "index-entry",
      id: "notation-152",
      original: ((20, 20),),
    ))$w_0$],
  [The element of $W$ which transforms each positive root to a negative root],
  [#index-ref(20)],

  [#metadata((
      kind: "index-entry",
      id: "notation-153",
      original: ((27, 27),),
    ))$W_J$],
  [The subgroup of $W$ generated by the fundamental reflections $w_r$ for $r$ in
    $J$],
  [#index-ref(27)],

  [#metadata((
      kind: "index-entry",
      id: "notation-154",
      original: ((217, 217),),
    ))$W^1$],
  [The subgroup of elements of $W$ commuting with the isometry $tau$],
  [#index-ref(217)],

  [#metadata((
      kind: "index-entry",
      id: "notation-155",
      original: ((218, 218),),
    ))$w_0^J$],
  [The element of $W_J$ which transforms every positive root in $Phi_J$ to a
    negative root],
  [#index-ref(218)],

  [#metadata((
      kind: "index-entry",
      id: "notation-156",
      original: ((284, 284),),
    ))$W(Sigma)$],
  [The group of type-preserving automorphisms of the abstract Coxeter complex
    $Sigma$],
  [#index-ref(284, target: "def:coxeter-complex-group")],

  [#metadata((
      kind: "index-entry",
      id: "notation-157",
      original: ((64, 64),),
    ))$x_r (t)$],
  [The generator $exp(t op("ad") e_r)$ of a Chevalley group],
  [#index-ref(64)],

  [#metadata((
      kind: "index-entry",
      id: "notation-158",
      original: ((68, 68),),
    ))$X_r$],
  [The root subgroup of a Chevalley group corresponding to the root $r$],
  [#index-ref(68)],

  [#metadata((
      kind: "index-entry",
      id: "notation-159",
      original: ((227, 227),),
    ))$X_S$],
  [The subgroup of a Chevalley group generated by the root subgroups
    corresponding to roots in $S$],
  [#index-ref(227)],

  [#metadata((
      kind: "index-entry",
      id: "notation-160",
      original: ((227, 227),),
    ))$X_S^1$],
  [The root subgroup $X_S inter G^1$ of a twisted group $G^1$],
  [#index-ref(227)],

  [#metadata((
      kind: "index-entry",
      id: "notation-161",
      original: ((50, 50),),
    ))$ZZ$],
  [The ring of rational integers],
  [#index-ref(50)],

  [#metadata((
      kind: "index-entry",
      id: "notation-162",
      original: ((190, 190),),
    ))$overline(Z)$],
  [The centre of the universal Chevalley group $overline(G)$],
  [#index-ref(190)],

  [#metadata((
      kind: "index-entry",
      id: "notation-163",
      original: ((254, 254),),
    ))$epsilon_1,dots,epsilon_l$],
  [The eigenvalues of $tau$ with eigenvectors $I_1,dots,I_l$],
  [#index-ref(254)],

  [#metadata((
      kind: "index-entry",
      id: "notation-164",
      original: ((251, 251),),
    ))$eta_1,dots,eta_l$],
  [The eigenvalues of the isometry $tau$ of $frak(V)$],
  [#index-ref(251)],

  [#metadata((
      kind: "index-entry",
      id: "notation-165",
      original: ((93, 93),),
    ))$eta_(r,s)$],
  [The integer $plus.minus 1$ defined by $n_r dot e_s=eta_(r,s)e_(w_r (s))$],
  [#index-ref(93)],

  [#metadata((
      kind: "index-entry",
      id: "notation-166",
      original: ((204, 204), (206, 206)),
    ))$lambda(r)$],
  [An integer which takes value 1 if $r$ is a short root and 2 or 3 if $r$ is a
    long root],
  [#index-ref(204), #index-ref(206)],

  [#metadata((
      kind: "index-entry",
      id: "notation-167",
      original: ((5, 5),),
    ))$nu(f)$],
  [The Witt index of a form $f$],
  [#index-ref(5)],

  [#metadata((
      kind: "index-entry",
      id: "notation-168",
      original: ((13, 13),),
    ))$Pi$],
  [A fundamental system of roots],
  [#index-ref(13)],

  [#metadata((
      kind: "index-entry",
      id: "notation-169",
      original: ((219, 219),),
    ))$Pi^1$],
  [The set of projections on to $frak(V)^1$ of roots in $Pi$],
  [#index-ref(219)],

  [#metadata((
      kind: "index-entry",
      id: "notation-170",
      original: ((200, 200),),
    ))$rho$],
  [A symmetry of the Dynkin diagram],
  [#index-ref(200)],

  [#metadata((
      kind: "index-entry",
      id: "notation-171",
      original: ((225, 225),),
    ))#source(341, "328")$sigma$],
  [An automorphism of a Chevalley group obtained by combining a graph and a
    field automorphism],
  [#index-ref(225)],

  [#metadata((
      kind: "index-entry",
      id: "notation-172",
      original: ((281, 281),),
    ))$Sigma$],
  [An abstract Coxeter complex],
  [#index-ref(281)],

  [#metadata((
      kind: "index-entry",
      id: "notation-173",
      original: ((288, 288),),
    ))$Sigma(W, Pi)$],
  [The abstract Coxeter complex associated with a Weyl group $W$ and fundamental
    system $Pi$],
  [#index-ref(288)],

  [#metadata((
      kind: "index-entry",
      id: "notation-174",
      original: ((201, 201), (217, 217)),
    ))$tau$],
  [The isometry of $frak(V)$ determined by a symmetry $rho$ of the Dynkin
    diagram],
  [#index-ref(201), #index-ref(217)],

  [#metadata((
      kind: "index-entry",
      id: "notation-175",
      original: ((12, 12),),
    ))$Phi$],
  [A root system],
  [#index-ref(12)],

  [#metadata((
      kind: "index-entry",
      id: "notation-176",
      original: ((14, 14),),
    ))$Phi^+$],
  [The set of positive roots in $Phi$],
  [#index-ref(14)],

  [#metadata((
      kind: "index-entry",
      id: "notation-177",
      original: ((16, 16),),
    ))$Phi^-$],
  [The set of negative roots in $Phi$],
  [#index-ref(16)],

  [#metadata((
      kind: "index-entry",
      id: "notation-178",
      original: ((27, 27),),
    ))$Phi_J$],
  [The set of roots in $Phi$ which lie in the subspace $frak(V)_J$],
  [#index-ref(27)],

  [#metadata((
      kind: "index-entry",
      id: "notation-179",
      original: ((49, 49),),
    ))$Phi^*$],
  [The set of co-roots of roots in $Phi$],
  [#index-ref(49)],

  [#metadata((
      kind: "index-entry",
      id: "notation-180",
      original: ((219, 219),),
    ))$Phi^1$],
  [The set of projections on to $frak(V)^1$ of roots in $Phi$],
  [#index-ref(219)],

  [#metadata((
      kind: "index-entry",
      id: "notation-181",
      original: ((97, 97),),
    ))$chi$],
  [A $K$-character of $P$],
  [#index-ref(97)],

  [#metadata((
      kind: "index-entry",
      id: "notation-182",
      original: ((98, 98),),
    ))$chi_(r,lambda)$],
  [The $K$-character of $P$ taking value $lambda^(A_(r s))$ at the root $s$],
  [#index-ref(98, target: "def:root-character-extension")],

  [#metadata((
      kind: "index-entry",
      id: "notation-183",
      original: ((292, 292),),
    ))$Omega$],
  [A building],
  [#index-ref(292)],

  [#metadata((
      kind: "index-entry",
      id: "notation-184",
      original: ((293, 293),),
    ))$Omega(G; B, N)$],
  [The building associated with a group $G$ with $(B,N)$-pair],
  [#index-ref(293)],

  [#metadata((
      kind: "index-entry",
      id: "notation-185",
      original: ((5, 5),),
    ))$Omega_n (K,f)$],
  [The commutator subgroup of the orthogonal group $O_n (K,f)$],
  [#index-ref(5)],

  [#metadata((
      kind: "index-entry",
      id: "notation-186",
      original: ((13, 13),),
    ))$succ$],
  [A total order relation on $frak(V)$],
  [#index-ref(13)],
)
