// Root systems, Weyl groups and Dynkin diagrams in the book's conventions:
// the Cartan matrix A_ij = 2(p_i, p_j)/(p_i, p_i) with the numbering of the
// matrices in section 3.6. Nodes, roots and coordinates count from 0 here.
#import "@preview/cetz:0.5.2"

// Vectors and matrices.

#let inner(u, v) = u.zip(v).map(((x, y)) => x * y).sum()
#let vadd(u, v) = u.zip(v).map(((x, y)) => x + y)
#let vscale(c, u) = u.map(x => c * x)
#let near(x, y) = calc.abs(x - y) < 1e-9
#let near-point(p, q) = near(p.at(0), q.at(0)) and near(p.at(1), q.at(1))
#let pairs(n) = range(n).map(i => range(n).map(j => (i, j))).join()
#let identity(n) = range(n).map(i => range(n).map(j => int(i == j)))
#let compose(x, y) = x.map(row => range(y.first().len()).map(j => {
  range(row.len()).map(k => row.at(k) * y.at(k).at(j)).sum()
}))

/// The order of a matrix of finite order.
#let order(x) = {
  let (m, y) = (1, x)
  while y != identity(x.len()) {
    (m, y) = (m + 1, compose(y, x))
    assert(m <= 24)
  }
  m
}

// Cartan matrices.

/// The Cartan matrix of type A, …, G (the family) and rank n, as printed in
/// section 3.6.
#let cartan(family, n) = {
  let chain(k) = range(k - 1).map(i => (i, i + 1, -1, -1))
  // Bonds (i, j, A_ij, A_ji). In E_n the node b carries the pendant b + 1
  // and the arm b + 2, b + 3.
  let b = n - 4
  let bonds = (
    A: chain(n),
    B: chain(n - 1) + ((n - 2, n - 1, -1, -2),),
    C: chain(n - 1) + ((n - 2, n - 1, -2, -1),),
    D: chain(n - 1) + ((n - 3, n - 1, -1, -1),),
    E: chain(b + 1)
      + ((b, b + 1, -1, -1), (b, b + 2, -1, -1), (b + 2, b + 3, -1, -1)),
    F: ((0, 1, -1, -1), (1, 2, -1, -2), (2, 3, -1, -1)),
    G: ((0, 1, -1, -3),),
  ).at(family)
  let a = identity(n).map(row => row.map(x => 2 * x))
  for (i, j, x, y) in bonds {
    a.at(i).at(j) = x
    a.at(j).at(i) = y
  }
  a
}

/// The Cartan matrix with the nodes renumbered: node k is `order.at(k)`.
#let permute(a, order) = order.map(i => order.map(j => a.at(i).at(j)))

/// The Cartan matrix of a fundamental system given by vectors.
#let cartan-of(vectors) = vectors.map(u => vectors.map(v => {
  let x = 2 * inner(u, v) / inner(u, u)
  assert(near(x, calc.round(x)), message: "not a fundamental system")
  int(calc.round(x))
}))

/// Bond numbers n_ij = A_ij A_ji = 4 cos² θ_ij of the Dynkin diagram.
#let bonds(a) = range(a.len()).map(i => range(a.len()).map(j => {
  if i == j { 0 } else { a.at(i).at(j) * a.at(j).at(i) }
}))

/// Inner products (p_i, p_j) of the fundamental roots of an indecomposable
/// system, from A_ij (p_i, p_i) = 2 (p_i, p_j) = A_ji (p_j, p_j); the short
/// roots have length 1, so all squared lengths are integers.
#let gram(a) = {
  let n = a.len()
  let norm = (1,) + range(n - 1).map(_ => none)
  for _ in range(n) {
    for (i, j) in pairs(n) {
      if norm.at(i) != none and norm.at(j) == none and a.at(i).at(j) != 0 {
        norm.at(j) = norm.at(i) * a.at(i).at(j) / a.at(j).at(i)
      }
    }
  }
  norm = norm.map(x => x / calc.min(..norm))
  assert(norm.all(x => near(x, calc.round(x))))
  norm = norm.map(x => int(calc.round(x)))
  range(n).map(i => range(n).map(j => a.at(i).at(j) * norm.at(i) / 2))
}

// Roots and the Weyl group.

/// The fundamental reflection w_i on coefficients over the fundamental roots.
#let reflect(a, i, c) = {
  let image = c
  image.at(i) -= range(c.len()).map(j => a.at(i).at(j) * c.at(j)).sum()
  image
}

/// The roots as coefficient vectors over the fundamental roots: the orbit of
/// the fundamental roots under the fundamental reflections.
#let roots(a) = {
  let found = identity(a.len())
  let k = 0
  while k < found.len() {
    for i in range(a.len()) {
      let image = reflect(a, i, found.at(k))
      if image not in found { found.push(image) }
    }
    k += 1
  }
  found
}

/// The matrix of w_i: its column j is w_i(p_j) = p_j − A_ij p_i.
#let reflection(a, i) = range(a.len()).map(r => range(a.len()).map(c => {
  int(r == c) - if r == i { a.at(i).at(c) } else { 0 }
}))

/// The longest element of the subgroup generated by w_j, j ∈ J: multiply by
/// w_j while w(p_j) is positive.
#let longest(a, J) = {
  let w = identity(a.len())
  let rising(w) = J.find(j => w.map(row => row.at(j)).all(x => x >= 0))
  let j = rising(w)
  while j != none {
    w = compose(w, reflection(a, j))
    j = rising(w)
  }
  w
}

// Symmetries and foldings.

/// A symmetry ρ of the Dynkin diagram (section 12.2), given by its images.
#let symmetry(a, rho) = {
  let n = bonds(a)
  for (i, j) in pairs(a.len()) {
    assert(
      n.at(i).at(j) == n.at(rho.at(i)).at(rho.at(j)),
      message: "not a symmetry of the diagram",
    )
  }
  rho
}

/// The ρ-orbits, each in increasing order, ordered by their least node.
#let orbits(rho) = {
  let result = ()
  for i in range(rho.len()) {
    if result.any(orbit => i in orbit) { continue }
    let orbit = (i,)
    while rho.at(orbit.last()) != i { orbit.push(rho.at(orbit.last())) }
    result.push(orbit.sorted())
  }
  result
}

/// The group W^1 of section 13.3 generated by the longest elements w_J of
/// the ρ-orbits J: its Coxeter matrix, m(J, K) the order of w_J w_K.
#let fold(a, rho) = {
  let w = orbits(rho).map(J => longest(a, J))
  w.map(x => w.map(y => order(compose(x, y))))
}

/// The number of bonds 4 cos²(π/m) for generators whose product has order
/// m, if it is an integer.
#let strength(m) = {
  let x = 4 * calc.pow(calc.cos(180deg / m), 2)
  if near(x, calc.round(x)) { int(calc.round(x)) }
}

// Layouts: the view, with the symmetries of the picture built in.

/// Reflection in the vertical line x = c, and in the horizontal axis.
#let across(c) = ((x, y)) => (2 * c - x, y)
#let flip((x, y)) = (x, -y)

/// The longest path from the node `start` in a diagram without cycles.
#let longest-path(n, start) = {
  let walk(i, previous) = {
    let best = ()
    for j in range(n.len()) {
      if j != previous and n.at(i).at(j) > 0 {
        let tail = walk(j, i)
        if tail.len() > best.len() { best = tail }
      }
    }
    (i,) + best
  }
  walk(start, none)
}

/// Positions of the nodes of a diagram with bond numbers `n`, the longest
/// path from `start` along the x-axis: `xs` is the step between path nodes
/// or the x-coordinates of the placed ones in turn; nodes in `skip` are not
/// placed. A node off the path hangs `drop` below its neighbour; with
/// `fork: (dx, dy)` the path ends at a branch node and its two leaves are
/// mirror images at (x + dx, ± dy).
#let path-layout(n, xs, start: 0, skip: (), drop: 0.4, fork: none) = {
  let path = longest-path(n, start)
  if fork != none { path = path.slice(0, -1) }
  let placed = path.filter(i => i not in skip)
  if type(xs) == array { assert(xs.len() == placed.len()) }
  let at = range(n.len()).map(_ => none)
  for (k, i) in path.enumerate() {
    if i in placed {
      let x = if type(xs) == array {
        xs.at(placed.position(j => j == i))
      } else {
        xs * k
      }
      at.at(i) = (x, 0)
    }
  }
  let hanging = range(n.len()).filter(i => i not in path and i not in skip)
  if fork != none { assert(hanging.len() == 2) }
  for i in hanging {
    let (x, y) = at.at(path.find(j => n.at(i).at(j) > 0))
    at.at(i) = if fork == none { (x, y - drop) } else {
      let (dx, dy) = fork
      if i == hanging.first() { (x + dx, dy) } else { flip((x + dx, dy)) }
    }
  }
  at
}

/// Positions showing ρ as the reflection in the x-axis: the ρ-orbits `step`
/// apart along the folded diagram, the nodes of an orbit from dy down to −dy.
#let orbit-layout(n, rho, step, dy, skip: ()) = {
  let parts = orbits(rho)
  let joined = parts.map(J => parts.map(K => int(
    J != K and J.any(j => K.any(k => n.at(j).at(k) > 0)),
  )))
  let at = range(n.len()).map(_ => none)
  for (k, part) in longest-path(joined, 0).enumerate() {
    let J = parts.at(part)
    for (m, j) in J.enumerate() {
      if j not in skip {
        let y = if J.len() == 1 { 0 } else { dy * (1 - 2 * m / (J.len() - 1)) }
        at.at(j) = (step * k, y)
      }
    }
  }
  at
}

/// Positions completed by a reflection realizing the permutation `pi`:
/// at(pi(i)) = mirror(at(i)); what stays unplaced is elided.
#let complete(at, pi, mirror) = {
  let at = at
  for i in range(at.len()) {
    if at.at(i) != none and at.at(pi.at(i)) == none {
      at.at(pi.at(i)) = mirror(at.at(i))
    }
  }
  for i in range(at.len()) {
    let (p, q) = (at.at(i), at.at(pi.at(i)))
    assert(
      (p == none) == (q == none) and (p == none or near-point(mirror(p), q)),
      message: "the reflection does not realize the symmetry",
    )
  }
  at
}

/// The arc for i → ρ(i): it leaves p_i at `gap` with its first control point
/// `bend` further on. Its other half is the image under `mirror`, which must
/// take p_i to p_ρ(i), or is given as `enter: (gap, bend)` at p_ρ(i).
/// Involutions get arrowheads at both ends.
#let symmetry-arc(at, rho, i, gap, bend, mirror: none, enter: none) = {
  let (p, q) = (at.at(i), at.at(rho.at(i)))
  let s = vadd(p, gap)
  let c = vadd(s, bend)
  let (e, d) = if enter == none {
    assert(near-point(mirror(p), q))
    (mirror(s), mirror(c))
  } else {
    let e = vadd(q, enter.first())
    (e, vadd(e, enter.last()))
  }
  (s, e, c, d, rho.at(rho.at(i)) == i)
}

/// The image of an arc under a reflection, traversed backwards.
#let mirror-arc((s, e, c, d, both), mirror) = (
  mirror(e),
  mirror(s),
  mirror(d),
  mirror(c),
  both,
)

// Labels, as strings of math markup.

/// A number printed relative to the nearest anchor (value, symbol): with the
/// anchors (0, "") and (6, "k"), 2 is "2" and 5 is "k-1".
#let relative(i, anchors) = {
  let (v, s) = anchors.sorted(key: ((v, _)) => calc.abs(i - v)).first()
  let d = i - v
  if s == "" { str(i) } else if d == 0 { s } else if d > 0 {
    s + "+" + str(d)
  } else { s + "-" + str(-d) }
}

/// The linear combination of symbols with integer coefficients.
#let linear(terms) = {
  let out = ""
  for (c, x) in terms.filter(((c, _)) => c != 0) {
    out += if c < 0 { "-" } else if out != "" { "+" } else { "" }
    out += if calc.abs(c) == 1 { x } else { str(calc.abs(c)) + x }
  }
  out
}

/// A symbol with a subscript.
#let indexed(symbol, index) = {
  symbol + "_" + if index.len() == 1 { index } else { "(" + index + ")" }
}

/// The vector sum c_k e_k, its indices printed by `index`.
#let vector-label(v, index) = {
  let term((k, c)) = (int(c), indexed("e", index(k)))
  let terms(v) = linear(v.enumerate().map(term))
  if v.all(c => c == v.first()) {
    assert(near(calc.abs(v.first()), 0.5))
    let sign = if v.first() < 0 { "-" } else { "" }
    sign + "1/2 sum_(i=" + index(0) + ")^" + index(v.len() - 1) + " e_i"
  } else if v.any(c => c != calc.round(c)) {
    "1/2(" + terms(vscale(2, v)) + ")"
  } else { terms(v) }
}

/// A root given by its coefficients, written over `names` of a basis of the
/// root lattice given by coefficient vectors (default: the fundamental roots).
#let root-label(c, names, basis: none) = {
  let coordinates = if basis == none { c } else {
    let ((a, b), (x, y)) = basis
    let det = a * y - b * x
    assert(calc.abs(det) == 1, message: "not a basis of the root lattice")
    (
      int((c.at(0) * y - c.at(1) * x) / det),
      int((a * c.at(1) - b * c.at(0)) / det),
    )
  }
  linear(coordinates.zip(names))
}

#let as-math(body) = if type(body) == str { eval(body, mode: "math") } else {
  body
}

// Drawing.

/// A Dynkin diagram with bond numbers `n` and node positions `at` (none for
/// an elided node). Nodes joined through elided nodes only are joined by a
/// dashed line. Labels are (node, body, offset, anchor), the body math
/// markup or content; arcs come from `symmetry-arc`.
#let dynkin(
  n,
  at,
  labels: (),
  arcs: (),
  unit: 1cm,
  stroke: 0.5pt,
  radius: 1.8pt,
  spacing: (0.045, 0.065),
) = cetz.canvas(length: unit, {
  import cetz.draw: bezier, circle, content, line
  let drawn = range(n.len()).filter(i => at.at(i) != none)
  let hidden = range(n.len()).filter(i => at.at(i) == none)
  // A line runs left to right, or downwards, so dashes start at its left end.
  let ends(i, j) = {
    let (p, q) = (at.at(i), at.at(j))
    let reversed = if near(p.at(0), q.at(0)) { p.at(1) < q.at(1) } else {
      p.at(0) > q.at(0)
    }
    if reversed { (q, p) } else { (p, q) }
  }
  for (i, j) in pairs(n.len()) {
    if i >= j or i not in drawn or j not in drawn { continue }
    if n.at(i).at(j) > 0 {
      // n_ij parallel lines.
      let (p, q) = ends(i, j)
      let d = vadd(q, vscale(-1, p))
      let (ux, uy) = vscale(1 / calc.sqrt(inner(d, d)), d)
      let (double, triple) = spacing
      let offsets = ((0,), (-double, double), (-triple, 0, triple))
      for o in offsets.at(n.at(i).at(j) - 1) {
        let shift = (-o * uy, o * ux)
        line(vadd(p, shift), vadd(q, shift), stroke: stroke)
      }
    } else {
      // Nodes reached from i through elided nodes only.
      let (seen, reached, k) = ((i,), (), 0)
      while k < seen.len() {
        for m in range(n.len()).filter(m => n.at(seen.at(k)).at(m) > 0) {
          if m in hidden and m not in seen { seen.push(m) }
          if m in drawn and k > 0 { reached.push(m) }
        }
        k += 1
      }
      if j in reached {
        line(..ends(i, j), stroke: (thickness: stroke, dash: "dashed"))
      }
    }
  }
  for (s, e, c, d, both) in arcs {
    let marks = if both { (start: ">", end: ">") } else { (end: ">") }
    bezier(s, e, c, d, stroke: 0.55pt, mark: (
      ..marks,
      length: 4pt,
      width: 3pt,
    ))
  }
  for i in drawn {
    circle(at.at(i), radius: radius, fill: white, stroke: stroke)
  }
  for (i, body, offset, anchor) in labels {
    content(vadd(at.at(i), offset), as-math(body), anchor: anchor)
  }
})

/// The roots of a system of rank at most two with Cartan matrix `a`, its
/// fundamental roots renumbered short one first: p_0 is horizontal of unit
/// length and p_1 lies above. Each root is drawn with its negative, the
/// outline joins the roots in angular order, and the labels give the
/// coordinates over `names` (see `root-label`). A label stands `gap` above,
/// below or beside its root, and off the axes also `diagonal` aside if
/// given. `bisector: (reach, thickness)` draws the line bisecting p_0 and
/// p_1 up to height ± reach; `origin` marks the origin.
#let root-system(
  a,
  names: ("a", "b"),
  basis: none,
  unit: 1cm,
  stroke: 0.5pt,
  radius: 1.8pt,
  gap: 0.12,
  diagonal: none,
  bisector: none,
  origin: false,
) = cetz.canvas(length: unit, {
  import cetz.draw: circle, content, line
  let short-first = range(a.len()).sorted(key: i => gram(a).at(i).at(i))
  let a = permute(a, short-first)
  let g = gram(a)
  let simple = if a.len() == 1 { ((1, 0),) } else {
    let x = g.at(0).at(1)
    ((1, 0), (x, calc.sqrt(g.at(1).at(1) - x * x)))
  }
  for (i, j) in pairs(a.len()) {
    let (u, v) = (simple.at(i), simple.at(j))
    assert(near(2 * inner(u, v) / inner(u, u), a.at(i).at(j)))
  }
  let point(c) = c.zip(simple).map(((k, p)) => vscale(k, p)).reduce(vadd)
  let angle(c) = {
    let (x, y) = point(c)
    calc.rem-euclid(calc.atan2(x, y) / 1deg, 360)
  }
  let all = roots(a).sorted(key: angle)
  // The dihedral group of order 2m has m reflections, one for each ±r.
  if a.len() == 2 {
    let m = order(compose(reflection(a, 0), reflection(a, 1)))
    assert(all.len() == 2 * m)
  }
  if all.len() > 2 { line(..all.map(point), close: true, stroke: stroke) }
  for c in all.slice(0, calc.quo(all.len(), 2)) {
    line(point(c), point(vscale(-1, c)), stroke: stroke)
  }
  if origin { line((0, -0.08), (0, 0.08), stroke: stroke) }
  if bisector != none {
    let (reach, thickness) = bisector
    let unit-vector(p) = vscale(1 / calc.sqrt(inner(p, p)), p)
    let (x, y) = simple.map(unit-vector).reduce(vadd)
    let end = (reach * x / y, reach)
    line(vscale(-1, end), end, stroke: (thickness: thickness, dash: "dashed"))
  }
  for c in all {
    let (x, y) = point(c)
    circle((x, y), radius: radius, fill: white, stroke: stroke)
    let (offset, anchor) = if near(y, 0) {
      if x > 0 { ((gap, 0), "west") } else { ((-gap, 0), "east") }
    } else {
      let (dy, side) = if y > 0 { (gap, "south") } else { (-gap, "north") }
      if diagonal == none or near(x, 0) { ((0, dy), side) } else if x > 0 {
        ((diagonal, dy), side + "-west")
      } else { ((-diagonal, dy), side + "-east") }
    }
    let body = as-math(root-label(c, names, basis: basis))
    content(vadd((x, y), offset), body, anchor: anchor)
  }
})
